@startjson
{
  "0x00": "string：+0个字符",
  "0x01": "string：+1个字符",
  "0x02": "string：+2个字符",
  "0x03": "string：+3个字符",
  "0x04": "string：+4个字符",
  "0x05": "string：+5个字符",
  "0x06": "string：+6个字符",
  "0x07": "string：+7个字符",
  "0x08": "string：+8个字符",
  "0x09": "string：+9个字符",
  "0x0A": "string：+10个字符",
  "0x0B": "string：+11个字符",
  "0x0C": "string：+12个字符",
  "0x0D": "string：+13个字符",
  "0x0E": "string：+14个字符",
  "0x0F": "string：+15个字符",
  "0x10": "string：+16个字符",
  "0x11": "string：+17个字符",
  "0x12": "string：+18个字符",
  "0x13": "string：+19个字符",
  "0x14": "string：+20个字符",
  "0x15": "string：+21个字符",
  "0x16": "string：+22个字符",
  "0x17": "string：+23个字符",
  "0x18": "string：+24个字符",
  "0x19": "string：+25个字符",
  "0x1A": "string：+26个字符",
  "0x1B": "string：+27个字符",
  "0x1C": "string：+28个字符",
  "0x1D": "string：+29个字符",
  "0x1E": "string：+30个字符",
  "0x1F": "string：+31个字符",
  "0x20": "binary：无数据",
  "0x21": "binary：+1个字节数据",
  "0x22": "binary：+2个字节数据",
  "0x23": "binary：+3个字节数据",
  "0x24": "binary：+4个字节数据",
  "0x25": "binary：+5个字节数据",
  "0x26": "binary：+6个字节数据",
  "0x27": "binary：+7个字节数据",
  "0x28": "binary：+8个字节数据",
  "0x29": "binary：+9个字节数据",
  "0x2A": "binary：+10个字节数据",
  "0x2B": "binary：+11个字节数据",
  "0x2C": "binary：+12个字节数据",
  "0x2D": "binary：+13个字节数据",
  "0x2E": "binary：+14个字节数据",
  "0x2F": "binary：+15个字节数据",
  "0x30": "string：+1个字节长度，+[32, 255]个字符",
  "0x31": "string：+1个字节长度，+[256, 511]个字符",
  "0x32": "string：+1个字节长度，+[512, 767]个字符",
  "0x33": "string：+1个字节长度，+[768, 1023]个字符",
  "0x34": "binary：1个字节长度，[16, 255]个字节数据",
  "0x35": "binary：1个字节长度，[256, 511]个字节数据",
  "0x36": "binary：1个字节长度，[512, 767]个字节数据",
  "0x37": "binary：1个字节长度，[768, 1023]个字节数据",
  "0x38": "long：[-262144, -2049]，+2个字节（更详细划分再研究）",
  "0x39": "long：[-262144, -2049]，+2个字节（更详细划分再研究）",
  "0x3A": "long：[-262144, -2049]，+2个字节（更详细划分再研究）",
  "0x3B": "long：[-262144, -2049]，+2个字节（更详细划分再研究）",
  "0x3C": "long：[2048, 262143]，+2个字节（更详细划分再研究）",
  "0x3D": "long：[2048, 262143]，+2个字节（更详细划分再研究）",
  "0x3E": "long：[2048, 262143]，+2个字节（更详细划分再研究）",
  "0x3F": "long：[2048, 262143]，+2个字节（更详细划分再研究）",
  "0x40": "",
  "0x41": "binary：2个字节长度，+8189个字节数据（注：长度固定，认为可以省略！）",
  "0x42": "binary：2个字节长度，[1024, 8189]个字节数据",
  "0x43": "实例对象",
  "0x44": "double：其余浮点数，+8个字节",
  "0x45": "",
  "0x46": "Boolean： False",
  "0x47": "",
  "0x48": "Map：（HashMap）",
  "0x49": "int：[-2147483648, -262145] 和 [262144, 2147483647]，+4个字节",
  "0x4A": "8字节正常日期",
  "0x4B": "4字节压缩日期",
  "0x4C": "long：[-9223372036854775808, -2147483649] 和 [2147483648, 9223372036854775807]，+8个字节",
  "0x4D": "Map：（除HashMap外，其他 Map 实现类）",
  "0x4E": "null",
  "0x4F": "",
  "0x50": "",
  "0x51": "相同实例对象应用，+int编号",
  "0x52": "string：+2个字节长度，+[32767, 32768]个字符(视最后一个字符是否完整，来决定多少)",
  "0x53": "string：+2个字节长度，+[1024, 32768]个字符",
  "0x54": "Boolean： True",
  "0x55": "",
  "0x56": "集合：[8, ]个元素（非 ArrayList，数组或者其他 Collection 实现类）",
  "0x57": "集合：迭代器（Iterator 或 Enumeration）",
  "0x58": "集合：[8, ]个元素（ArrayList）",
  "0x59": "long： [-2147483648, -262145] 和 [262144, 2147483647]，+4个字节（就是整数范围）",
  "0x5A": "结束标志符",
  "0x5B": "double：0.0",
  "0x5C": "double：1.0",
  "0x5D": "double：[-128.0, 127.0] 浮点数，+1个字节",
  "0x5E": "double：[-32768.0, 32767.0] 浮点数，+1个字节",
  "0x5F": "double：Integer/1000 浮点数，+4个字节",

  "0x60": "",
  "0x61": "",
  "0x62": "",
  "0x63": "",
  "0x64": "",
  "0x65": "",
  "0x66": "D瓜哥 · https://www.diguage.com · 出品",
  "0x67": "",
  "0x68": "",
  "0x69": "",
  "0x6A": "",
  "0x6B": "",
  "0x6C": "",
  "0x6D": "",
  "0x6E": "",
  "0x6F": "",

  "0x70": "集合：0个元素（非 ArrayList，数组或者其他 Collection 实现类）",
  "0x71": "集合：1个元素（非 ArrayList，数组或者其他 Collection 实现类）",
  "0x72": "集合：2个元素（非 ArrayList，数组或者其他 Collection 实现类）",
  "0x73": "集合：3个元素（非 ArrayList，数组或者其他 Collection 实现类）",
  "0x74": "集合：4个元素（非 ArrayList，数组或者其他 Collection 实现类）",
  "0x75": "集合：5个元素（非 ArrayList，数组或者其他 Collection 实现类）",
  "0x76": "集合：6个元素（非 ArrayList，数组或者其他 Collection 实现类）",
  "0x77": "集合：7个元素（非 ArrayList，数组或者其他 Collection 实现类）",
  "0x78": "集合：0个元素（ArrayList）",
  "0x79": "集合：1个元素（ArrayList）",
  "0x7A": "集合：2个元素（ArrayList）",
  "0x7B": "集合：3个元素（ArrayList）",
  "0x7C": "集合：4个元素（ArrayList）",
  "0x7D": "集合：5个元素（ArrayList）",
  "0x7E": "集合：6个元素（ArrayList）",
  "0x7F": "集合：7个元素（ArrayList）",
  "0x80": "int: -16",
  "0x81": "int: -15",
  "0x82": "int: -14",
  "0x83": "int: -13",
  "0x84": "int: -12",
  "0x85": "int: -11",
  "0x86": "int: -10",
  "0x87": "int: -9",
  "0x88": "int: -8",
  "0x89": "int: -7",
  "0x8A": "int: -6",
  "0x8B": "int: -5",
  "0x8C": "int: -4",
  "0x8D": "int: -3",
  "0x8E": "int: -2",
  "0x8F": "int: -1",
  "0x90": "int: 0",
  "0x91": "int: 1",
  "0x92": "int: 2",
  "0x93": "int: 3",
  "0x94": "int: 4",
  "0x95": "int: 5",
  "0x96": "int: 6",
  "0x97": "int: 7",
  "0x98": "int: 8",
  "0x99": "int: 9",
  "0x9A": "int: 10",
  "0x9B": "int: 11",
  "0x9C": "int: 12",
  "0x9D": "int: 13",
  "0x9E": "int: 14",
  "0x9F": "int: 15",
  "0xA0": "int: 16",
  "0xA1": "int: 17",
  "0xA2": "int: 18",
  "0xA3": "int: 19",
  "0xA4": "int: 20",
  "0xA5": "int: 21",
  "0xA6": "int: 22",
  "0xA7": "int: 23",
  "0xA8": "int: 24",
  "0xA9": "int: 25",
  "0xAA": "int: 26",
  "0xAB": "int: 27",
  "0xAC": "int: 28",
  "0xAD": "int: 29",
  "0xAE": "int: 30",
  "0xAF": "int: 31",
  "0xB0": "int: 32",
  "0xB1": "int: 33",
  "0xB2": "int: 34",
  "0xB3": "int: 35",
  "0xB4": "int: 36",
  "0xB5": "int: 37",
  "0xB6": "int: 38",
  "0xB7": "int: 39",
  "0xB8": "int: 40",
  "0xB9": "int: 41",
  "0xBA": "int: 42",
  "0xBB": "int: 43",
  "0xBC": "int: 44",
  "0xBD": "int: 45",
  "0xBE": "int: 46",
  "0xBF": "int: 47",
  "0xC0": "int: [-2048, -17]，+1个字节（更详细划分再研究）",
  "0xC1": "int: [-2048, -17]，+1个字节（更详细划分再研究）",
  "0xC2": "int: [-2048, -17]，+1个字节（更详细划分再研究）",
  "0xC3": "int: [-2048, -17]，+1个字节（更详细划分再研究）",
  "0xC4": "int: [-2048, -17]，+1个字节（更详细划分再研究）",
  "0xC5": "int: [-2048, -17]，+1个字节（更详细划分再研究）",
  "0xC6": "int: [-2048, -17]，+1个字节（更详细划分再研究）",
  "0xC7": "int: [-2048, -17]，+1个字节（更详细划分再研究）",
  "0xC8": "int: [48, 2047]，+1个字节（更详细划分再研究）",
  "0xC9": "int: [48, 2047]，+1个字节（更详细划分再研究）",
  "0xCA": "int: [48, 2047]，+1个字节（更详细划分再研究）",
  "0xCB": "int: [48, 2047]，+1个字节（更详细划分再研究）",
  "0xCC": "int: [48, 2047]，+1个字节（更详细划分再研究）",
  "0xCD": "int: [48, 2047]，+1个字节（更详细划分再研究）",
  "0xCE": "int: [48, 2047]，+1个字节（更详细划分再研究）",
  "0xCF": "int: [48, 2047]，+1个字节（更详细划分再研究）",
  "0xD0": "int: [-262144, -2049]，+2个字节（更详细划分再研究）",
  "0xD1": "int: [-262144, -2049]，+2个字节（更详细划分再研究）",
  "0xD2": "int: [-262144, -2049]，+2个字节（更详细划分再研究）",
  "0xD3": "int: [-262144, -2049]，+2个字节（更详细划分再研究）",
  "0xD4": "int: [2048, 262143]，+2个字节（更详细划分再研究）",
  "0xD5": "int: [2048, 262143]，+2个字节（更详细划分再研究）",
  "0xD6": "int: [2048, 262143]，+2个字节（更详细划分再研究）",
  "0xD7": "int: [2048, 262143]，+2个字节（更详细划分再研究）",
  "0xD8": "long: -8",
  "0xD9": "long: -7",
  "0xDA": "long: -6",
  "0xDB": "long: -5",
  "0xDC": "long: -4",
  "0xDD": "long: -3",
  "0xDE": "long: -2",
  "0xDF": "long: -1",
  "0xE0": "long: 0",
  "0xE1": "long: 1",
  "0xE2": "long: 2",
  "0xE3": "long: 3",
  "0xE4": "long: 4",
  "0xE5": "long: 5",
  "0xE6": "long: 6",
  "0xE7": "long: 7",
  "0xE8": "long: 8",
  "0xE9": "long: 9",
  "0xEA": "long: 10",
  "0xEB": "long: 11",
  "0xEC": "long: 12",
  "0xED": "long: 13",
  "0xEE": "long: 14",
  "0xEF": "long: 15",
  "0xF0": "long：[-2048, -9]，+1个字节（更详细划分再研究）",
  "0xF1": "long：[-2048, -9]，+1个字节（更详细划分再研究）",
  "0xF2": "long：[-2048, -9]，+1个字节（更详细划分再研究）",
  "0xF3": "long：[-2048, -9]，+1个字节（更详细划分再研究）",
  "0xF4": "long：[-2048, -9]，+1个字节（更详细划分再研究）",
  "0xF5": "long：[-2048, -9]，+1个字节（更详细划分再研究）",
  "0xF6": "long：[-2048, -9]，+1个字节（更详细划分再研究）",
  "0xF7": "long：[-2048, -9]，+1个字节（更详细划分再研究）",
  "0xF8": "long：[16, 2047]，+1个字节（更详细划分再研究）",
  "0xF9": "long：[16, 2047]，+1个字节（更详细划分再研究）",
  "0xFA": "long：[16, 2047]，+1个字节（更详细划分再研究）",
  "0xFB": "long：[16, 2047]，+1个字节（更详细划分再研究）",
  "0xFC": "long：[16, 2047]，+1个字节（更详细划分再研究）",
  "0xFD": "long：[16, 2047]，+1个字节（更详细划分再研究）",
  "0xFE": "long：[16, 2047]，+1个字节（更详细划分再研究）",
  "0xFF": "long：[16, 2047]，+1个字节（更详细划分再研究）"
}
@endjson