---
title: "《卡片笔记写作法》之读书笔记（一）：绪论"
date: 2021-08-09T06:48:10+08:00
draft: false
categories: ["阅读摘要"]
tags: ["书籍", "方法论"]
thumbnail: "images/books/how-to-take-smart-notes.jpg"

weight: 1
---

:icons: font

[quote, 卢曼 1992，53]
____
不写，就无法思考。
____

最近把 https://book.douban.com/subject/35503571/[《卡片笔记写作法》^] 读完了，深受启发，相见恨晚。

先分享一个小趣闻：看完这本书，想实践一下，就去购物网站搜合适的活页卡片。考虑到便利性，就选择了 A6 大小的活页。上网找了一圈，也没有找到标准尺寸的 A6 活页。考虑以后直接拿 A4 纸进行裁剪。现在的问题变成了如何把 A4 纸裁剪得标准一些。

看完全书，纵观卡曼的发展过程，特别叹服的一点是，他会不断反思自己的行为和学习方法，并且反复尝试改进自己的学习方法，以求达到最好的效率。反思自己，虽然总是耕读不断，虽然过程中也许捡了不少好砖，但是就像那个捡玉米的猴子，随捡随丢，终究没能垒起我的阅读城堡！可惜可惜！

闲言少叙，书归正传。读这本书，有几点印象特别深刻：

. 书中将记忆区分为两种机智：**存储强度（storage strength）与提取强度（retrieval strength）。并且“存储与提取负相关”，也就是说，存入记忆越容易，提取出来越困难；反之，如果你有些吃力地存入，知识提取会更方便。**这点有点意思。
. 书中一个比喻特别形象：**卢曼卡片盒就像是复利投资，而特罗洛普的技术就像是储蓄罐。**复利投资可以滚雪球，越滚越大，而且是指数增长。
. 书中还有一个概念很有意思：“思维网格”，**如果知识既不是被孤立地保存，也不是被孤立地学习，而是聚集在一个思想网络中，或者说是“思维模型的网格”中，那么理解新的信息就变得更容易了。**
. 卡片笔记学习法自然而然产生的自下而上写作法拥有一个巨大优势：**我们所使用的想法都嵌入了丰富的上下文中，并且附带了可以使用的素材，而不是凭空产生的。这样做会带来另一个意想不到的收获，那就是我们会对新的想法持更加开放的态度。**可以轻松避免由于预设结论导致的认知偏误。
. 卡片盒笔记的精华所在：**以新的和意想不到的方式，将不同的想法汇集在一起，从而产生新的想法。**卢曼的卡片不是简简单单地摘抄，而是自己组织语言的转述，需要加工再输出。不仅仅是摘录原文，更是思想的录像机与连接器，记录下当下的思想，建立与已有思想的链接。
. **一个巨大的误解是：如果不制订计划，就只能是漫无目的地乱写一气。其实我们真正该做的是构建适合自己的工作流程，让洞见和新想法成为推动我们前进的驱动力。**
. **记笔记也不是最关键的工作，思考、阅读、理解和提出想法才是，笔记只是它们的具体成果。写，无疑是我们思考、阅读、学习、理解和产生想法的最佳催化剂。**

书中的真知灼见数不胜数，可以通过D瓜哥的这几篇读书笔记“管中窥豹”。当然，更推荐大家去阅读原文。D瓜哥是在“微信读书”中阅读的免费版，礼尚往来，推荐一下。

D瓜哥把读书笔记整理一下。按照章节，分三篇来分享：

* https://www.diguage.com/post/how-to-take-smart-notes-1/[《卡片笔记写作法》之读书笔记（一）：绪论^]
* https://www.diguage.com/post/how-to-take-smart-notes-2/[《卡片笔记写作法》之读书笔记（二）：有效写作的四个基本原则^]
* https://www.diguage.com/post/how-to-take-smart-notes-3/[《卡片笔记写作法》之读书笔记（三）：成功写作的六个步骤^]

== 中文版序

卡片盒笔记依赖一种非线性的方式，即缓慢而稳定的改进，促进思维产生持续、微妙的变化，并且事物间相生相依。朱利安发现这些主题在中国哲学中被讨论得更为广泛。

我欣喜地发现，并非我一人有此体验：卡片盒笔记法——关联的、分散的、自下而上的方法不仅比一些教育者们所推崇的线性的、自上而下的方法更为自然，而且衍生出了诸多写作及笔记记录工具。

卡片盒笔记的精华所在：以新的和意想不到的方式，将不同的想法汇集在一起，从而产生新的想法。

随着可使用工具的快速变化，我决定让这本书尽可能地与工具无关。书籍有着不同的生命周期，因此应该更多地关注不受时间影响的方面。

== 推荐序一 像卢曼一样写卡片

我写作时，手边会放着纸质的卡片。我一般会先在卡片上写下一些灵感，然后再用卡片写作软件将它们正式整合成文章。同样，在阅读时，我也会不断地使用纸质卡片盒与卡片写作软件写下读书心得。

日本知名学者梅棹忠夫在《智识的生产技术》中提到的“京大卡”，他认为卡片要大一些，大概是B6开本大小，更容易保存写作灵感。而我带队研发的“写匠”，更多地参考了美国知名作家纳博科夫的卡片写作法——使用索引卡，通过任意打乱卡片次序完成自己的写作。

尼克拉斯·卢曼是20世纪德国重要的社会学家，而且其影响力已远远超出了社会学领域。

传统的卡片写作法，像纳博科夫，是只使用一个盒子，用一个盒子来保存自己写作的内容。而卢曼多了一个盒子，对自己卡片写作的内容进行索引和整理。

比约克率先区分了记忆竞争的两种不同类型：存储强度（storage strength）与提取强度（retrieval strength）。

“存储与提取负相关”，也就是说，存入记忆越容易，提取出来越困难；反之，如果你有些吃力地存入，知识提取会更方便。

第一类是主题索引。当某个主题的内容积累得足够丰富，卢曼就会做一张主题索引卡，对这个主题进行概览。主题索引卡上会汇集所有相关笔记的编码或链接，每条笔记会用一两个词或一个短句简要说明核心内容。这类索引，相当于给了你一个进入某一主题的入口。第二类与主题索引类似，只不过不是对某一主题的概览，而是针对盒子里相近位置的卡片所涉及的所有不同主题进行概览。第三类是在当前卡片上做索引，标明这条笔记逻辑上的前一条是什么、后一条是什么（这些卡片在盒子里的位置可能并不挨着）。第四类，也是最常用的索引形式，就是简单的“笔记-笔记”连接。两条笔记可能完全没有关系，把它们关联在一起，往往会产生出乎意料的新思路。

我经常推荐的是德国科学家丹尼尔·卢德克（Daniel Lüdecke）开发的开源软件——卡片盒笔记（Zettelkasten）。

一是将文本的颗粒度拆分得更细。组块（block）是认知科学上的一个常用概念，文本组块正是这个概念的具象化。

以大的单位很难记住，拆分成小的单位就更容易记住。写作时，用大脑直接记住的东西越多，写作就越不容易被打断，节省的脑力就越多。

二是建立了一个“双向引用”关系。什么是“双向引用”？

== 推荐序二 外脑思考，突破思维局限的写作法

我和作者的兴趣一样，也是外脑思考（Thinking Outside the Brain）。

但工具功能很难改变人的思维习惯，而需要配合课程、书籍或教练服务。

千里之行始于跬步的道理中国人都懂，但没人教过我们在一步一步地、枯燥地踏在探索未知的路上时如何保持热情，如何坚持，如何充满信心，如何时刻和自己对话，以及如何走好每一步。书中介绍的工作流和原则，是卢曼等人利用卡片盒实践过的，他们完全无须坚持就充满乐趣地达成了非凡成就。

深知全世界的人仅凭意志力和坚持，绝无可能完成那种极限挑战。只有完全换另一种思维方式，才能心情愉悦地、安全地达成目标。创业如此，做产品如此，写论文亦如此。

把诸如拖延、坚持、压力、焦虑、知识管理、时间管理等热词从脑海里划掉。

使用卡片笔记写作法，我们可以不定期地提取先前的想法和事实，并将它们与其他信息联系起来，这正是专家们推荐的学习方式。

== 推荐序三 用卡片笔记积累你的知识复利

书中主要介绍的是德国社会学家尼克拉斯·卢曼自创的一套笔记方法，利用这套方法，他一生积累了90000个知识卡片，写了58本书和其他大量出版物。

就是把你感兴趣或者将来可能会用到的知识收集起来，然后用一种像集装箱一样标准化的方式，去处理这些笔记，建立笔记之间的联系，供你使用。

重要的不是记录，而是更好地思考。

比如拒绝做知识的搬运工，必须用自己的话写下来；比如需要记录的是知识，而非信息；比如不需要进行机械分类，而是让关系慢慢地自动生长出来等。

也希望这本书能让你开始写下第一张知识卡片，积累起属于自己的知识复利。未来已至，只是分布得还不均匀。

== 译者序

以往教授笔记方法的图书多以两类为主：一类是教授记笔记的形式，比如一页纸法、九宫格法、思维导图法；另一类则以教授原理为主，如费曼笔记法、康奈尔笔记法、PQ4R法等。

这也正是本书所说的“自下而上”和“自上而下”两种工作流程的区别之一。前者是把功夫花在平时，当我们前期学习时，就以一种聪明的方式记笔记，这些笔记会成为我们日后的生产性资料。后者常常是以计划开始，然后围绕某个主题去搜集资料，这样就难免有很大的随机性，甚至经常要持续面临阶段性的风险和可能最终失败的代价。

记笔记可以巩固我们的思考成果。自己的思考并不意味着完全不同于原始的知识，有时哪怕是精简一下语言，调整一下语序，使得下一次再查看时不需要花费和第一次一样多的时间，那么我们花在第一次学习上的时间也就有了价值。

为了形成这套工作流程，我们需要先自己阅读本书，然后用自己的话记下自己的理解，并要巩固这些思考成果。之后选择一项不得不做的学习任务或工作任务，借助某个工具将书中的部分方法付诸实践。

学习时，我们需要像剥洋葱一样，一层又一层地解构书中的原理；而运用时，则需要像在故宫修漆器类文物一样，分多次、分层地复原书中的原理。

。其实哪有什么惊人绝技，有的只是把简单有效的方法用到极致罢了。

本书的核心，将记笔记分为闪念笔记、文献笔记和永久笔记三类，

学习心理学上关于成功模仿的四要素——观察、保持、复现和动机。

== 导论

当需要记住些什么时，无论是一个想法、一句话，还是一项研究成果，我们往往都需要写下来，还会借助写来组织自己的思想，或者与他人交流。

每一点脑力耕耘都是从一条笔记开始的。

改善写作的组织过程才是最重要的。

如何将你的想法和发现，高效地转化为令人信服的书面作品，并在此过程中建立起一个卡片盒笔记宝库。

写作并不是学习、研究和探究之后的事情，而是这些工作的媒介。每天的写作、记笔记和打草稿就像我们的呼吸一样，它对我们所做的工作至关重要。

人们不重视记笔记的另一个原因是，即使笔记记得不好，也不会立即得到任何负面的反馈。

让太多的人忽略了成功的写作策略和不太成功的写作策略之间真正的区别在于——笔记做得好还是不好。

其实你是谁并不重要，重要的是你的行动力。

如果做一件事不是因为你有意志力，而是根本不需要使用意志力，那就意味着你离成功不远了。而组织写作和记笔记就能发挥这样的作用。

从长远来看，依赖用意志力来完成一件事情是一种非常糟糕的策略。

== 第一章 绪论

=== 关于写作，你需要知道的

我从不强迫自己做任何我不喜欢的事情。每当我思路卡顿的时候，我就会转头去做别的事情。”好的安排可以让你做到在不同的任务间自如切换，而不会破坏整体安排，也不会漏掉重点部分。

如果把“写论文”这个无定式的任务分解成一个个小而清晰的独立任务，你就可以一次只专注于一件事，完成一件事之后，再做下一件事。

制订计划是给自己强加条条框框，进度变得按部就班。如果想按照计划推进，你就得用意志力逼迫自己，这样容易导致自己陷入意志消沉的状态，而且这种方式也不适合像研究、思考或持续学习这样的开放式过程。

一个巨大的误解是：如果不制订计划，就只能是漫无目的地乱写一气。其实我们真正该做的是构建适合自己的工作流程，让洞见和新想法成为推动我们前进的驱动力。

真正的高手则不会考虑主动放弃已经被证明是有价值和有趣的事情，而是会用一种能够真正产生洞见、积累和激发新想法的方式学习。

事实上，成绩差的学生往往自我感觉良好（直到他们参加考试时才露出原形），因为他们不会有太多的自我怀疑。在心理学上，这被称为邓宁—克鲁格效应（Kruger and Dunning,1999）。

[sidebar]
****
我成绩不好，还经常自我怀疑，这怎么解释？😂
****

那些在某方面不是很擅长的人往往过于自信，而那些努力过的人往往低估了自己的能力。

优秀的学生会专注于尚未学到和掌握的东西，并因此不断提高自己的标准。这就是为什么那些接触到外部大量知识的高分者反而很可能会患上心理学家所说的“冒牌货综合征”，也就是说，他们感觉自己并不能真正胜任这份工作，尽管在所有的人中，自己是最有资格胜任的（Clance and Imes,1978;Brems et al.,1994）。

==== 好的解决方案往往简单且出人意料

恰恰相反，处理复杂的事情最好的方法是尽可能地保持简单，并遵循一些基本原则。我们可以用简化的结构搭建复杂的内容。

不需要重做以前做过的事情，而是从现在开始改变工作方式就行。不需要重新组织已有的任何东西，只要在必须处理事情的那一刻，换一种方式来处理就行了。

[sidebar]
****
如果有更好的学习方法，我倒是愿意脱胎换骨，把自己的学习方法和习惯给打破重塑！
****

第一个方法是简单的卢曼卡片盒技术，这是本书的核心。

如果你不改变工具所涉及的日常工作，即使是最好的工具也不会大幅提升工作效率，就像如果没有合适的道路来驾驶汽车，就算最快的汽车也不会有什么帮助。正如每一种行为的改变一样，工作习惯的改变也会有一个反复的过程。新的做法一开始可能会让你感到别扭，觉得不像凭直觉去做那样有必要性，这很正常。

只有当所有相关的工作都相互衔接成为一个整体，所有的瓶颈都被消除时，才能发生显著的变化

戴维·艾伦（David Allen）在《搞定》（Getting Things Done,2001）一书中强调了“总体工作流程的重要性”。

GTD的原则是把所有需要处理的事情收集到一起，并以标准化的方式进行处理。

大多数注意力分散的情况并不是源于我们的环境，而是源于我们自己的思想。

所有的事情都需要处理好，否则被忽视的那部分会绊住我们，导致不重要的任务也变得紧急。即使是最好的工具，孤立使用它也不会有太好的效果，只有把它们嵌入精心策划的工作流程中，工具才能发挥出它们的优势。

只有当信任系统，而且知道一切都可以处理好的时候，大脑才会放开，才能专注于手头的任务。

==== 卢曼卡片盒

每当遇到不同寻常的事情，或者对所读内容有想法时，他都会记下来。

一个想法、一条笔记只有在它的上下文语境中才有价值，而上下文并不一定是它的出处。

但卢曼没有这样。仅仅在卡片盒的帮助下，在不到一年的时间，就完成了博士论文和定职论文，这期间他还上了社会学的课。也就是不久后的1968年，卢曼就被选为比勒菲尔德大学的社会学教授，并且终身担任这一职位。

[sidebar]
****
纵观卡曼的发展过程，特别叹服的一点是，他会不断反思自己的行为和学习方法，并且反复尝试改进自己的学习方法，以求达到最好的效率。反思自己，虽然总是耕读不断，虽然过程中也许捡了不少好砖，但是就像那个捡玉米的猴子，随捡随丢，终究没能垒起我的阅读城堡！可惜可惜！
****

30年间，他出版了58本著作和数百篇文章（不包括译本），许多都成为各领域的经典之作。甚至在他去世之后，他办公室里留下的快完成的手稿被整理出来，又有六七本关于宗教、教育或政治等不同主题的书以他的署名出版。我身边的很多同事都愿意穷尽一生所能，像卢曼一样著作等身。

他那源源不断的想法比他能够写下来的还要多，他的文字读起来就像他在努力通过一本出版物展现出尽可能多的见解和想法。

如果说我想要什么，那就是更多的时间，但令人遗憾的是时间实在太少了

唯一真正能够帮助卢曼的是一名管家，平时为他和孩子们做饭，因为妻子早逝后卢曼独自抚养三个孩子。

保持掌控感的最好方法就是保持控制。

对成功人士的研究一再证明，成功不是源于强大的意志力和克服阻力的能力，而是源于高明的工作环境事先避免了阻力（Neal et al.,2012;Painter et al.,2002;Hearn et al.,1998）。

主要的误解源于人们对卢曼卡片盒的孤立关注，而忽视了它所嵌入的实际工作流程。

与亨利·福特同时代的人不明白，为什么像传送带这样简单的东西会有那么大的革命性——把汽车从一个工人运到另一个工人面前，和让工人从一台汽车走到另一台汽车跟前有什么不同呢？

[sidebar]
****
蝴蝶扇了扇翅膀，在远方就引发了一场暴风。一个微不足道的改变，却引发了全世界的升级。事实就是这么难以置信。类似的例子有本书提到的集装箱的发明。
****

==== 卡片盒使用手册

卢曼有两类卡片盒：一类是文献卡片盒，里面有文献和对文献内容的简要说明；另一类是主卡片盒，主要是他针对所阅读的内容收集和产生的想法。这些笔记都写在索引卡片上，存放在木质卡片盒里。

卢曼并不只是照抄他所读过的文章中的观点或引文，而是将其从一个语境转化到另一个语境。

卢曼笔记的诀窍在于，他并不是按主题来组织他的笔记，而是以相当抽象的方式给它们编上数字。

每当卢曼添加一条笔记时，他都会检查他的卡片盒中是否有其他相关的笔记，以便在它们之间建立可能的联系。在这条笔记和（或）其他笔记之间添加一个链接，另一条笔记可以在系统中的任何地方。

卢曼笔记系统的最后一个元素是索引，他会从这个索引中引用一两条笔记，作为进入某个思路或主题的切入点。

=== 关于写作，你需要做的

试想一下如果你的文章并不是从一张白纸开始写起，而是已经有某个友好的精灵（或者是高薪聘请的助理——随便可以利用的人或工具）为你准备了论文初稿。这个初稿已经有一个完全成熟的论点，包括所有的参考资料、引文和一些非常高明的想法。唯一要做的就是修改这个初稿，然后把它寄出去。

你只需要把笔记集中起来并将它们整理好，把这些笔记变成文稿，复查一下就行了。

记笔记也不是最关键的工作，思考、阅读、理解和提出想法才是，笔记只是它们的具体成果。

在做最关键的工作的同时记笔记，如果做得好，二者能够相辅相成。写，无疑是我们思考、阅读、学习、理解和产生想法的最佳催化剂。

如果你想好好地思考、阅读、理解和产生想法，你手里必须有一支笔。如果你想长期学习某样东西，就必须把它写下来。如果你想真正理解某件事情，你就必须把它转化为自己的语言。

*撰写论文的步骤*

. 记闪念笔记（fleeting notes）。你手边需要随时有记笔记的工具，以捕捉脑海中闪现的每一个想法。不
. 记文献笔记（literature notes）。无论你读什么，都要做笔记，写下你不想忘记的内容，或者你认为可能会在自己的思考或写作中使用的内容。文献笔记要非常简短，精心选择，并使用自己语言记录，对引文要格外挑剔，不要只是抄写，而不去真正理解其含义。最后把这些笔记和参考书目的细节一起保存在你的文献管理系统中。
. 记永久笔记（permanent notes）。
. 现在把你新写的永久笔记添加到卡片盒中，方法如下：
.. 把每一条笔记都归档在一个或多个相关的笔记后面。
.. 给相关笔记添加链接。
.. 这样做是为了确保你以后能够找到这条笔记，可以从索引页链接到它，也可以在你用来作为某个讨论或话题的切入点的笔记上做一个链接。
. 从系统内部自下而上发展主题、问题和研究课题。
+
不要为一个主题进行头脑风暴，而是要看一下卡片盒，看看哪里已经形成了笔记链，哪里已经建立了想法群；如果另一个更有希望的想法已经成型，就不要执着于前一个想法。你对某件事情越感兴趣，就会阅读得越多，思考得越多，进而收集的笔记越多，最终越有可能从中提出问题和想法。
+
. 一段时间后，会积攒到足够多的想法去确定一个写作主题。这时，你的主题是基于你所拥有的素材，而不是基于即将阅读的文献可能提供的未知想法。思考一下这个主题的内在联系，收集所有与之相关的笔记（大部分的相关笔记已经有了一定顺序），把它们复制到大纲软件中[3]，并把它们按顺序排列好。看看哪些还不够，哪些是多余的。不要等着所有的东西都集齐，而是要积极思考，给自己足够的时间去阅读和记笔记，以改进你的想法、论点和架构。
. 把你的笔记变成初稿。不要简单地把笔记复制到手稿里，要把它们转化成连贯的内容，并将它们嵌入到你论点的上下文中，同时从笔记中得出你的论点。检查论点中的漏洞，想办法完善或改变论点。
. 编辑、校对你的稿子。拍拍自己的肩膀，然后开始写下一篇文稿。

典型的日常工作包括以下全部或部分环节，比如阅读并记笔记；对卡片盒中的笔记建立关联，这个过程又会激发你新的想法；记下这些想法，并将它们添加到讨论中；写到纸上时，你又发现论点中有一个漏洞，于是到卡片笔记系统中去查找缺失的链接；你关注到一个脚注，细加研究，可能会为正在写的论文中加上一条合适的引用。

=== 关于写作，你需要具备的能力

专注于事情的根本，而不是把事情不必要地复杂化。

突然之间，每一个小步骤本身就变成了一个任务，却没有把整个项目向前推进多少。就这样增加一项功能强大的技术反而让事情变得更糟。

好的工具并不是在我们已有的工具基础上增加功能和更多的选择，而是帮助我们减少对主要工作的干扰，这里的主要工作就是思考。

==== 工具箱

阅读和书写时，需要四种工具。

* 书写工具（纸和笔亦可）。
* 文献管理工具（如Zotero，Citavi，或者其他最适合的软件工具）。
+
使用文献管理系统有两个目的：收集参考文献和你在阅读过程中做的笔记。
+
* 卡片盒（纸质或者应用程序形式）。
* 编辑工具（Word，LaTex，或者其他最适合的工具）。这些工具多了没用，少了则不能顺利完成工作。

=== 关于写作，你需要注意的几个问题

不仅要知道它是如何工作的，或者如何使用它，而且还要知道它为什么有效，这才是至关重要的。

我认为只要记住几个基本原则，并了解文档系统背后的逻辑，任何人都可以复制卢曼的方法，从而取得学习、写作和研究上的成功。

