---
title: "《卡片笔记写作法》之读书笔记（二）：有效写作的四个基本原则"
date: 2021-08-10T06:17:30+08:00
draft: false
categories: ["阅读摘要"]
tags: ["书籍", "方法论"]
thumbnail: "images/books/how-to-take-smart-notes.jpg"

weight: 1
---

:source-highlighter: rouge
:rouge-style: monokai
:source_attr: indent=0,subs="attributes,verbatim,quotes"
:image_attr: align=center,width=100%
:icons: font

[quote, 卢曼 1992，53]
____
不写，就无法思考。
____

最近把 https://book.douban.com/subject/35503571/[《卡片笔记写作法》^] 读完了，深受启发，相见恨晚。

先分享一个小趣闻：看完这本书，想实践一下，就去购物网站搜合适的活页卡片。考虑到便利性，就选择了 A6 大小的活页。上网找了一圈，也没有找到标准尺寸的 A6 活页。考虑以后直接拿 A4 纸进行裁剪。现在的问题变成了如何把 A4 纸裁剪得标准一些。

看完全书，纵观卡曼的发展过程，特别叹服的一点是，他会不断反思自己的行为和学习方法，并且反复尝试改进自己的学习方法，以求达到最好的效率。反思自己，虽然总是耕读不断，虽然过程中也许捡了不少好砖，但是就像那个捡玉米的猴子，随捡随丢，终究没能垒起我的阅读城堡！可惜可惜！

闲言少叙，书归正传。读这本书，有几点印象特别深刻：

. 书中将记忆区分为两种机智：**存储强度（storage strength）与提取强度（retrieval strength）。并且“存储与提取负相关”，也就是说，存入记忆越容易，提取出来越困难；反之，如果你有些吃力地存入，知识提取会更方便。**这点有点意思。
. 书中一个比喻特别形象：**卢曼卡片盒就像是复利投资，而特罗洛普的技术就像是储蓄罐。**复利投资可以滚雪球，越滚越大，而且是指数增长。
. 书中还有一个概念很有意思：“思维网格”，**如果知识既不是被孤立地保存，也不是被孤立地学习，而是聚集在一个思想网络中，或者说是“思维模型的网格”中，那么理解新的信息就变得更容易了。**
. 卡片笔记学习法自然而然产生的自下而上写作法拥有一个巨大优势：**我们所使用的想法都嵌入了丰富的上下文中，并且附带了可以使用的素材，而不是凭空产生的。这样做会带来另一个意想不到的收获，那就是我们会对新的想法持更加开放的态度。**可以轻松避免由于预设结论导致的认知偏误。
. 卡片盒笔记的精华所在：**以新的和意想不到的方式，将不同的想法汇集在一起，从而产生新的想法。**卢曼的卡片不是简简单单地摘抄，而是自己组织语言的转述，需要加工再输出。不仅仅是摘录原文，更是思想的录像机与连接器，记录下当下的思想，建立与已有思想的链接。
. **一个巨大的误解是：如果不制订计划，就只能是漫无目的地乱写一气。其实我们真正该做的是构建适合自己的工作流程，让洞见和新想法成为推动我们前进的驱动力。**
. **记笔记也不是最关键的工作，思考、阅读、理解和提出想法才是，笔记只是它们的具体成果。写，无疑是我们思考、阅读、学习、理解和产生想法的最佳催化剂。**

书中的真知灼见数不胜数，可以通过D瓜哥的这几篇读书笔记“管中窥豹”。当然，更推荐大家去阅读原文。D瓜哥是在“微信读书”中阅读的免费版，礼尚往来，推荐一下。

D瓜哥把读书笔记整理一下。按照章节，分三篇来分享：

* https://www.diguage.com/post/how-to-take-smart-notes-1/[《卡片笔记写作法》之读书笔记（一）：绪论^]
* https://www.diguage.com/post/how-to-take-smart-notes-2/[《卡片笔记写作法》之读书笔记（二）：有效写作的四个基本原则^]
* https://www.diguage.com/post/how-to-take-smart-notes-3/[《卡片笔记写作法》之读书笔记（三）：成功写作的六个步骤^]

== 第二章 有效写作的四个基本原则

=== 写作是唯一重要的事情

有了想法只有自己知道，就等于没想法，而无法重现的论据也根本算不上论据。

教授不是为了学生而存在的，学生也不是为了教授而存在的，两者都只为真理而存在，而真理永远属于公共事务。

专注于写作，并不意味着要减少阅读量，因为它是写作材料的主要来源；专注于写作，并不意味着要少参加讲座或研讨会，因为它们不但能为你提供写作的思路和值得解答的问题，而且是了解研究现状的最佳途径之一，更不用说它为提出和讨论问题提供了平台；专注于写作也并不意味着要停止做演讲或寻找其他方式将自己的想法公之于众——没有什么比这更好的途径为你的想法提供反馈了。

努力找寻你“应该”做的事情并不是在浪费时间，相反，借助于此，你会努力以尽可能高的效率去学习，从而迅速找到那个开放性的问题，也是唯一值得写作的问题。

=== 简洁是最重要的

越简单的想法往往具有越强大的效果（并且在一开始总被忽视）。

马尔科姆·麦克莱恩（Malcom McLean）的集装箱思想和实践，改变了世界贸易格局。

1956年4月26日，麦克莱恩把“理想X号（Ideal X）”邮轮改装成可以装载58个集装箱的邮轮起航的时候，仅仅是因为这种直接装卸集装箱的分装方式比整船装卸货物的方式便捷，能免于在港口漫长的等待几天。

麦克莱恩比别人更明白，重要的不是船东的观点，而是整个贸易的目的，即把货物从生产者那里带到最终目的地。只有将运输链的每一个环节——从包装到运送，从设计船舶到设计港口——都统一起来之后，集装箱的潜力才能够得到充分释放。

[sidebar]
****
从这个地方也可以看出，不要只谋求一城的得失，要从战略的高度看全局的胜负。做笔记也一样，不是写完就完事了，整理输出再加工更加重要。
****

当他们读到一个有趣的句子，就在下面画线；当他们想要评论时，就写到空白处；当他们有一个想法时，就写进笔记本；当他们觉得一篇文章足够重要，就努力摘抄。

传统的笔记系统中，主要问题是人们把某条笔记存放在了哪个主题下；而卢曼卡片盒笔记系统中，主要问题则是考虑想在哪个主题下再见到它。

[sidebar]
****
有点举一反三的灵动，也有反其道而行之的逆向思维。

这里还有一个问题：一些潜在关联不能及时发现，需要后续逐步探索才能慢慢展示出来。
****

所有的努力只为一个目的：发表有价值的观点。

传统的笔记系统是为了找到你意图搜索的东西，让你的大脑疲于回忆，而卢曼卡片盒笔记系统则是为了给你呈现你已经忘记的想法，让你的大脑专注于思考。

要达到群聚效应的最佳点，关键是要分清楚三类笔记。

. 闪念笔记（Fleeting Notes）：这类笔记只是对收集信息起提醒作用，可以用任何一种方式来写，最后会在一两天内被扔进垃圾桶。
. 永久笔记（Permanent Notes）：这种笔记以一种永久可以理解的方式包含了必要的信息，并且永远不会被扔掉。它们总是以同样的方式存放在同一个地方，或者是在文献管理系统中，或者按出版标准写好放在卡片盒中。
. 项目笔记（Project Notes）：它们只与某一特定项目有关，保存在特定项目的文件夹内，项目结束后即可丢弃或存档。

第一个典型的错误是很多勤奋的学生都会遵循“要像写科学杂志一样记笔记”的建议。

由于他把每一条笔记都划分到“永久笔记”的范畴，导致优秀的笔记被其他或许只与特定项目有关、或许实际上不那么好的笔记淹没了，因此永远也无法实现群聚效应。

第二个典型的错误是只收集与特定项目有关的笔记。

第三个典型的错误当然是把所有的笔记都当作闪念笔记。

这三种类别的混乱有一个共同点，那就是记笔记的好处会随着你保存笔记数量的增加而减少，笔记记得越多，就越难找到恰当的那个，越难以自如地将相关的笔记整合到一起。

闪念笔记只有在你能在一两天内回顾它们，并将它们变成以后可以使用的适当的笔记时才有价值。

永久笔记不只是思想或观点的备忘录，而是以书面形式包含实际思想或观点的文本，这是一个至关重要的区别。

*与项目有关的笔记可以是以下内容：*

* 手稿中的评论；
* 与项目有关的文献收集；
* 大纲；
* 草稿片段；
* 备忘录；
* 待办事项；
* 草稿本身。

我建议为每个项目准备一个实体文件夹，将所有相关的手写笔记和打印稿从其他文件中分出来存放在一起。

=== 没有人完全从零开始写作

“从一张白纸或者空白的屏幕开始写作，是一个彻头彻尾的误解。”（Nassehi,2015）

写作不可能符合线性规划。

真正长久并广泛适用的建议是，我们必须拿着笔阅读，把思想的发展过程落实到纸上，并建立一个不断增长的外部思想库。我们不会被不可靠的大脑盲目编造的计划所引导，而是被我们的兴趣、好奇心和直觉所引导，这种直觉是在阅读、思考、讨论、写作和发展思想等实质工作中形成的，这是一种不断增长的能力，并从外部反映出我们的知识和理解。

[sidebar]
****
反思一下，我总觉得这样漫无目的的阅读会让学习过程拉得特别漫长。坦白讲，我有些急于求成。
****

如果我们把注意力集中在感兴趣的事物上，并对自己的知识发展过程进行书面记录，题目、问题和论点就会自然而然地从材料中涌现出来。

如果你认识到“写作不是一个线性过程，而是一个循环过程”，并以此来安排自己的工作流程，“如何找到一个主题来写”的问题就会变成“如何处理可写主题太多”的问题。

而那些已经通过写作培养了思维的人，则可以把注意力放在自己当下感兴趣的事情上，只要做自己最想做的事情，就能积累大量的素材。

去做那些为得出明智决定所必需的事，即阅读、思考和写作。

=== 让工作推动你前进

有时候，我们会觉得工作正在消耗我们的能量，只有投入越来越多的能量才能前进。有时却恰恰相反，一旦我们进入工作状态，工作本身就好像获得了动力，拉着我们前进，有时甚至让我们充满活力。这就是我们所追求的动力。

[sidebar]
****
这就是心流的状态。在做自己喜欢的事情上，会无比投入和专注。
****

如果不能从长远考虑，建立积极反馈循环，任何试图用外部奖励（比如在完成一章后做一些喜欢做的事）哄骗自己去工作的尝试都只是短期的解决方案，非常脆弱。只有当工作本身就是激励时，驱动力和奖励才能可持续动态循环，从而推动整个任务前进（DePasque and Tricomi,2015）。

唯一能提高我们做一件事的能力的就是及时而具体的反馈。

长期成功的最可靠预测因素是拥有“成长型思维”。积极寻求并接受反馈，是长期成功（和幸福）的最重要因素之一，无论这些反馈是积极的还是消极的。反之，对个人成长最大的阻碍是抱有“固定型思维”。

拥抱成长的心态意味着要从变得更好中获得快乐（内在回报），而不是从接受赞美中获得快乐（外在回报）。

[sidebar]
****
赞美是别人的商业互吹！成长才是自己实实在在的内功。
****

拥有成长的心态是至关重要的，但这只是一方面。同样重要的是，建立一个学习系统，以实际的方式实现反馈循环。

如果我们不用自己的话重写一遍，往往就会误以为自己已经理解了所读到的东西，因此写作是检验我们是否理解所读内容的最简单方法。

[sidebar]
****
用自己的话复述，相当于输入加工再输出，本身也是一个提高输入难度的强化学习过程。
****

用自己的语言去表达所理解的内容是每一个写作者应当具备的基本能力，并且只有借助这个过程意识到自己不理解的内容，我们才能变得在这方面更擅长，做笔记也就变得更快更容易，并进一步增加学习经验。

写永久笔记也是一样，它还内置了另一个反馈循环：用文字表达自己的想法，会让我们思考自己是否真的想清楚了。

使用卡片盒，与其说是为了提取具体的笔记，不如说是为了指向相关的论据，并通过让思想交融而产生洞见。

如果知识既不是被孤立地保存，也不是被孤立地学习，而是聚集在一个思想网络中，或者说是“思维模型的网格”中（Munger,1994），那么理解新的信息就变得更容易了。这不仅使学习和记忆变得更容易，而且提取信息及其可用之处变得更容易了。

[sidebar]
****
知识网格，或者叫思维网格，把各个孤立的知识点联系起来，让其交织成一张网格，这样就会随着网越来越密实，能网到的知识财富也会越来越多。
****

让我们的工作变得如此富有成效的因素，并非是孤立的卡片盒或我们的大脑本身，而是两者之间的动态关系。

