---
title: "《如何阅读一本书？》之读书笔记"
date: 2020-01-08T22:23:51+08:00
draft: false
categories: ["阅读摘要"]
tags: ["书籍", "方法论"]
thumbnail: "images/books-on-book-day/how-to-read-a-book.jpg"

weight: 1
---

:icons: font

D瓜哥在 https://www.diguage.com/post/goodbye-2019-hello-2020/#how-to-read-a-book[“告别 2019，迎接 2020”^] 中已经提过，今年的一个重要改进就是把书读透，学以致用，不求速度但求质量。并且，还提到要重读《如何阅读一本书》和《如何有效阅读一本书》，以求提高读书技能，把书读透。

最近在读《如何阅读一本书》，大概读了五分之一。最近有个想法，何不用《如何阅读一本书》中介绍的方法来阅读《如何阅读一本书》呢？熟悉编程（尤其是 Ruby）的朋友估计该会心一笑，有点元编程的感觉。

D瓜哥这里先大概介绍一下书中的内容，然后再根据读书方法来剖析这本书。

作者在全书第一章就开宗明义地写道：这本书为那些想把读书的主要目的当作是增进理解能力的人而写。

我们的目标就是：第一提醒读者，阅读可以是一件多少主动的事。第二要指出的是，阅读越主动，效果越好。

阅读艺术是一个凭借着头脑运作，除了玩味读物中的一些字句之外，不假任何外助，以一己之力来提升自我的过程。

蒙田说：“初学者的无知在于未学，而学者的无知在于学后。”

阅读的艺术包括了所有非辅助型自我发现学习的技巧：敏锐的观察、灵敏可靠的记忆、想象的空间，再者当然就是训练有素的分析、省思能力。

要避免这样的错误 —— 以为读得多就是读得好的错误。

== 做一个自我要求的读者

主动阅读的核心就是：你在阅读时要提出问题来 — 在阅读的过程中，你自己必须尝试去回答的问题。

=== 四个基本问题

一个阅读者要提出的四个基本问题:

. 整体来说，这本书到底在谈些什么？你一定要想办法找出这本书的主题，作者如何依次发展这个主题，如何逐步从核心主题分解出从属的关键议题来。
. 作者细部说了什么，怎么说的？你一定要想办法找出主要的想法、声明与论点。这些组合成作者想要传达的特殊讯息。
. 这本书说得有道理吗？是全部有道理，还是部分有道理？
. 这本书跟你有什么关系？

=== 做笔记的方法

. 画底线 —— 在主要的重点，或重要又有力量的句子下画线。
. 在画底线处的栏外再加画一道线。
. 在空白处做星号或其他符号 —— 要慎用。
. 在空白处编号 —— 作者的某个论点发展出一连串的重要陈述时，可以做顺序编号。
. 在空白处记下其他的页码 —— 强调作者在书中其他部分也有过同样的论点，或相关的要点，或是与此处观点不同的地方。
. 将关键字或句子圈出来 —— 这跟画底线是同样的功能。
. 在书页的空白处做笔记 —— 在阅读某一章节时，你可能会有些问题 （ 或答案 ），在空白处记下来，这样可以帮你回想起你的问题或答案。
. 

=== 三种笔记

. 笔记主要的重点是全书的架构，而不是内容 —— 至少不是细节。因此我们称这样的笔记为结构笔记（Structural Note-making）。
. 概念笔记（Conceptual Note-making）。
. 针对一场讨论情境的笔记 —— 辩证笔记 （ Dialectical Note-making）。

你在做这件事时，每一个分开来的步骤都需要你全神贯注地去做。在你分别练习过这些分开来的步骤后，你不但能放下你的注意力，很有效地将每个步骤做好，还能将所有的动作结合起来，表现出一个整体的顺畅行动。

一个人只要学习过一种复杂的技巧，就会知道要学习一项新技巧，一开始的复杂过程是不足为惧的。等所有分开的动作不再分离，渐渐融为一体时，学习者便能将注意力转移到目标上，而他也具备了要达成目标的能力了。

== 阅读的四个层次

第一层次的阅读为基础阅读（Elementary Reading）。这个层次的任务就是识文认字。

第二层次的阅读为检视阅读（Inspectional Reading）。特点在强调时间。在这个阅读层次，学生必须在规定的时间内完成一项阅读的功课。在一定的时间之内，抓出一本书的重点。检视阅读是系统化略读 （Skimming Systematically） 的一门艺术。

第三种层次的阅读为分析阅读（ Analytical Reading）。分析阅读就是全盘的阅读、完整的阅读，或是说优质的阅读。如果说检视阅读是在有限的时间内，最好也最完整的阅读，那么分析阅读就是在无限的时间里，最好也最完整的阅读。一个分析型的阅读者一定会对自己所读的东西提出许多有系统的问题。分析阅读就是特别在追寻理解的。

第四种，也是最高层次的阅读，称之为主题阅读（Syntopical Reading）。在做主题阅读时，阅读者会读很多书，而不是一本书，并列举出这些书之间相关之处，提出一个所有的书都谈到的主题。借助他所阅读的书籍，主题阅读者要能够架构出一个可能在哪一本书里都没提过的主题分析。

== 基础阅读

基础阅读又分为四个阶段：

第一个阶段，阅读准备阶段。包含身体方面、智力方面、语言方面、个人能力等。

第二阶段，认字。孩子会学习读一些简单的读物。

第三阶段，字汇的增长及对课文的运用。特征是快速简历字汇的能力；学会不同目标与不同领域的阅读法。

第四阶段，特征是精炼与增进前面所学的技巧。最重要的是，学生能开始消化他的阅读经验。

== 检视阅读

检视阅读主要为了回答如下问题：

. 这是什么样的书？
. 整本书在谈的是什么？
. 作者借用怎样的整体架构来发展他的观点或陈诉他对主题的理解？

=== 有系统的略读或粗读

1. 先看书名页，然后如果有序就先看序。
2. 研究目录页，对这本书的基本架构做概括性的理解。
3. 如果书中附有索引，也要检阅一下。
4. 读一下出版者的介绍。
5. 挑几个看来跟主题息息相关的篇章来看。
6. 把书打开，东翻翻西翻翻，念个一两段，有时候连续读几页，但不要太多。

最重要的是，不要忽略最后的两三页。

=== 粗浅的阅读

规则：头一次面对一本难读的书的时候，从头到尾先读完一遍，碰到不懂的地方不要停下来查询或思索。

NOTE: 不要为一些没法立即了解的东西而停顿。

这里还要重点介绍一个训练阅读速度的方法：

将大拇指与食指、中指合并在一起，用这个 “ 指针 ” 顺着一行一行的字移动下去，速度要比你眼睛感觉的还要快一点。强迫自己的眼睛跟着手部的动作移动。一旦你的眼睛能跟着手移动时，你就能读到那些字句了。继续练习下去，继续增快手的动作，等到你发觉以前，你的速度已经可以比以前快两三倍了。

D瓜哥这里有个疑问：读多快才算是合格呢？

== 分析阅读

=== 第一阶段：找出一本书在谈些什么的规则，告诉你一本书的内容是关于什么，要如何将架构列出纲要。

. 依照书的种类与主题来分类。
. 使用最简短的文字说明整本书在谈些什么。
. 将主要部分按顺序与关联性列举出来。将全书的大纲列举出来，并将各个部分的大纲也列出来。
. 确定作者想要解决的问题。

=== 第二阶段：诠释一本书的内容规则，告诉你这本书的详细内容是什么，如何叙述的。

[start=5]
. 诠释作者的关键字，与他达成共识。
. 由最重要的句子中，抓住作者的重要主旨。
. 知道作者的论述是什么，从内容中找出相关的句子，再重新架构出来。
. 确定作者已经解决了哪些问题，还有哪些是没解决的。再判断哪些是作者知道他没解决的问题。

=== 第三阶段：像是沟通知识一样地评论一本书的规则

==== A：智慧礼节的一般规则

[start=9]
. 除非你已经完成大纲架构，也能诠释整本书了，否则不要轻易批评。（在你说出：“我读懂了!”之前，不要说你同意、不同意或暂缓评论。） 
. 不要争强好胜，非辩到底不可。
. 在说出评论之前，你要能证明自己区别得出真正的知识与个人观点的不同。

==== B：批评观点的特别标准

[start=12]
. 证明作者的知识不足。
. 证明作者的知识错误。 
. 证明作者不合逻辑。
. 证明作者的分析与理由是不完整的。

== 主题阅读

在作主题阅读时，第一个要求就是知道：对一个特定的问题来说，所牵涉的绝对不是一本书而已。第二个要求则是：要知道就总的来说，应该读的是哪些书？第二个要求比第一个要求还难做到。

收集好书目之后，要做的第一件事是检视书单上所有的书。

* 第一，它会让你对自己想要研究的主题有个清晰的概念，
* 第二，它会简化你的书目到一个合理的程度。

你在分析阅读一本书时，你就像是把书当作主人，供他使唤。而你在做主题阅读时，却一定要做书的主人。

总体来讲，在主题阅读中有两个阶段。一个是准备阶段，另一个是主题阅读本身。

让我们复习一下这些不同的步骤：

=== 一、观察研究范围：主题阅读的准备阶段

. **针对你要研究的主题，设计一份试验性的书目。**你可以参考图书馆目录、专家的建议与书中的书目索引。
. **浏览这份书目上所有的书，确定哪些与你的主题相关，并就你的主题建立起清楚的概念。**

=== 二、主题阅读：阅读所有第一阶段收集到的书籍

. *浏览所有在第一阶段被认定与你主题相关的书，找出最相关的章节。*
. **根据主题创造出一套中立的词汇，带引作者与你达成共识**——无论作者是否实际用到这些词汇，所有的作者，或至少绝大部分的作者都可以用这套词汇来诠释。
. **建立一个中立的主旨，列出一连串的问题**——无论作者是否明白谈过这些问题，所有的作者，或者至少大多数的作者都要能解读为针对这些问题提供了他们的回答。
. **界定主要及次要的议题。**然后将作者针对各个问题的不同意见整理陈列在各个议题之旁。你要记住，各个作者之间或之中，不见得一定存在着某个议题。有时候，你需要针对一些不是作者主要关心范围的事情，把他的观点解读，才能建构出这种议题。
. **分析这些讨论。**这得把问题和议题按顺序排列，以求突显主题。比较有共通性的议题，要放在比较没有共通性的议题之前。各个议题之间的关系也要清楚地界定出来。

注意：理想上，要一直保持对话式的疏离与客观。要做到这一点，每当你要解读某个作家对一个议题的观点时，必须从他自己的文章中引一段话来并列。

NOTE: D瓜哥认为，所谓主题阅读，其实就是对知识的先做整体吸收，然后再加工，最后输出的一个过程。当然这个输出可以是文字输出，也可以是脑子中对主题认知的升华。

接下来，D瓜哥就用这本书介绍的方法再来会看这本书，有机会再补充读书笔记。
