---
title: "Versions Maven 插件简介"
date: 2023-04-21T22:07:37+08:00
draft: false
keywords: ["Java","依赖管理","Maven","Plugin","插件","版本管理"]
tags: ["Java","Spring","最佳实践"]
categories: ["开发工具","软件工程"]
thumbnail: "images/logos/maven.svg"

weight: 1
---

在 https://www.diguage.com/post/specification-for-maven-bom/[制定组织内 Maven BOM 的一些规范^] 中，D瓜哥 介绍了一些组织内指定 Maven BOM 的一些规范。根据这些规范，D瓜哥 创建并维护了部门内部的 Maven BOM。今年，要求对部门内的陈旧依赖做一些升级工作。所以，在 https://www.diguage.com/post/experience-about-upgrading-java-dependencies/[关于升级 Spring 等依赖的一些经验^] 中介绍了一些升级开源依赖的经验；在上一篇文章 https://www.diguage.com/post/upgrade-maven-plugins/[升级 Maven 插件^] 中介绍了升级 Maven 插件的一些注意事项。

D瓜哥一直坚持“机器可以干的事情，就应该交给机器干”。对于依赖管理，Maven Enforcer 插件就可以对依赖做必要的检查，所以，在 https://www.diguage.com/post/use-maven-enforcer-plugin-to-check-dependencies/[使用 Maven Enforcer 插件检查依赖^] 中，介绍了如何使用 Apache Maven Enforcer 来管理依赖。由于要维护部门内部的 Maven BOM，同时由于版本控的特质，所以，需要时长检查依赖升级情况。原来都是手动检查，需要一个一个去搜索各个依赖，不仅费时费力，而且还低效。最近，Maven 有一个插件可以胜任这个工作，它就是： https://www.mojohaus.org/versions/versions-maven-plugin/index.html[Versions Maven Plugin^]。


== 依赖检查

Versions Maven Plugin 支持两种配置方式：

. 外置配置文件 `maven-version-rules.xml`；
. 内置在 POM 文件中，直接写在插件的 `<configuration>` 标签中。

第一种方案不方便迁移。还要额外管理一个配置文件。推荐使用第二种方式。另外，直接将这些配置放在 Maven BOM 中，使用继承的方式使用 Maven BOM，那么子项目就自动继承了这些配置。后续也只需要一个地方的配置即可。示例配置如下：

[source%nowrap,xml,{source_attr}]
----
<!-- @author: D瓜哥 · https://www.diguage.com -->
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>versions-maven-plugin</artifactId>
    <version>2.15.0</version>
    <configuration>
        <ruleSet>
            <ignoreVersions>
                <!-- 可以使用 ignoreVersion 配置忽略 SNAPSHOT、alpha、beta 版等 -->
                <ignoreVersion>
                    <!-- 'exact' (默认) 或 'regex' -->
                    <type>regex</type>
                    <version>(.+-SNAPSHOT|.+-M\d)</version>
                </ignoreVersion>
                <ignoreVersion>
                    <type>regex</type>
                    <version>.+-(alpha|beta)</version>
                </ignoreVersion>
            </ignoreVersions>
            <rules>
                <!-- 可以使用 rule 指定忽略的具体依赖及相关版本 -->
                <!-- 例如：如果面向 Java 8 的应用，就不能升级到 Spring 6+。 -->
                <rule>
                    <groupId>org.springframework</groupId>
                    <ignoreVersion>
                        <type>regex</type>
                        <version>[6-9].*</version>
                    </ignoreVersion>
                </rule>
                <rule>
                    <groupId>org.springframework.boot</groupId>
                    <ignoreVersion>
                        <type>regex</type>
                        <version>[3-9].*</version>
                    </ignoreVersion>
                </rule>
                <rule>
                    <groupId>org.slf4j</groupId>
                    <ignoreVersion>
                        <type>regex</type>
                        <version>[2-9].*</version>
                    </ignoreVersion>
                </rule>
                <rule>
                    <groupId>ch.qos.logback</groupId>
                    <ignoreVersion>
                        <type>regex</type>
                        <version>1.[4-9].*</version>
                    </ignoreVersion>
                </rule>
                <rule>
                    <groupId>com.zaxxer</groupId>
                    <ignoreVersion>
                        <type>regex</type>
                        <version>[5-9].*</version>
                    </ignoreVersion>
                </rule>
                <rule>
                    <groupId>org.mybatis</groupId>
                    <artifactId>mybatis-spring</artifactId>
                    <ignoreVersion>
                        <type>regex</type>
                        <version>[3-9].*</version>
                    </ignoreVersion>
                </rule>
            </rules>
        </ruleSet>
    </configuration>
</plugin>
----

NOTE: 这里给大家提个醒，外置配置文件的配置语法与 POM 文件中的 `<configuration>` 中的配置语法不同，不可混用。D瓜哥混用了一下，就一直报错。后来，在 GitHub 上给项目提 Issue 才解决这个问题。

== 升级项目版本

现在的 Maven 项目，一般都会用多模块开发。升级项目版本时，就需要一个一个 POM 文件去改，费时费劲。这个操作，也可以让 Versions Maven Plugin 来完成。在项目的根目录执行如下命令

[source%nowrap,bash,{source_attr}]
----
# 这里假设要发布 1.0.0 正式版
$ mvn versions:set -DnewVersion=1.0.0
----

执行完后，该项目及子模块的版本都会给修改为 `1.0.0`；同时，每个 POM 文件都会生成一个对应的 `pom.xml.versionsBackup`，该文件是用于回滚的。

如果发现什么问题，想要回滚到上一个版本，则可以使用以下命令回滚到备份的 `pom.xml`：

[source%nowrap,bash,{source_attr}]
----
$ mvn versions:revert
----

如果一些OK，则可以执行以下命令会删除备份文件，完成版本升级：

[source%nowrap,bash,{source_attr}]
----
$ mvn versions:commit
----

如果想省事，也可以增加参数 `-DgenerateBackupPoms=false` 不产生备份文件：

[source%nowrap,bash,{source_attr}]
----
# 这里假设要发布 1.0.0 正式版
$ mvn versions:set -DgenerateBackupPoms=false -DnewVersion=1.0.0
----

Versions Maven Plugin 还有升级插件等其他功能，感兴趣可以自行去探索。这里就不再赘述。

== 参考资料

. https://www.mojohaus.org/versions/versions-maven-plugin/index.html[Versions Maven Plugin – Introduction^]
. https://www.mojohaus.org/versions/versions-maven-plugin/version-rules.html[Versions Maven Plugin – Version Rules^]
. https://www.mojohaus.org/versions/versions-maven-plugin/set-mojo.html[Versions Maven Plugin – versions:set^]
. https://www.cnblogs.com/LQBlog/p/16227930.html[maven versions-maven-plugin插件^]