---
title: "killercoda CKA：Troubleshooting - 2"
date: 2024-12-24T19:54:28+08:00
draft: true
keywords: ["Kubernetes", "CKA"]
tags: ["Kubernetes","Linux"]
categories: ["系统架构"]
thumbnail: "images/logos/kubernetes.svg"
weight: 1
---

// * https://killercoda.com/killer-shell-cka[Killer Shell CKA | Killercoda^]
// * https://killercoda.com/sachin/course/CKA
// * https://killer.sh/[Killer Shell - Exam Simulators^] -- 收费，30刀

// 不足之处：
//
// . 对 Pod 定义中 `command`、 `args`、 `volumes` 等不熟悉
// . 对 ConfigMap 的使用不是很熟练。
// . apt 查询可升级版本不熟悉
// . Secret 各种创建不熟悉
// . kubectl -o jsonpath='<jsonpath>' 用法
// . 各个常用资源的 apiGroup 不是特别清楚
// . Pod 对 Volume 的使用，以及结合 ConfigMap 的使用
// . etcd 的基本运维操作

:sectnums:
// TODO 如何设置章节起始数


== Troubleshooting - Persistent Volume, Persistent Volume Claim - Issue

https://killercoda.com/sachin/course/CKA/pv-pvc-issue[Troubleshooting - Persistent Volume, Persistent Volume Claim - Issue^]

****

****

[source%nowrap,bash,{source_attr}]
----
# @author D瓜哥 · https://www.diguage.com


----


== Troubleshooting - CronJob Issue

https://killercoda.com/sachin/course/CKA/cronjob-issue[Troubleshooting - CronJob Issue^]

****

****

[source%nowrap,bash,{source_attr}]
----
# @author D瓜哥 · https://www.diguage.com


----


== Troubleshooting - DaemonSet Issue

https://killercoda.com/sachin/course/CKA/ds-issue[Troubleshooting - DaemonSet Issue^]

****

****

[source%nowrap,bash,{source_attr}]
----
# @author D瓜哥 · https://www.diguage.com


----


== Troubleshooting - Deployment Issue

https://killercoda.com/sachin/course/CKA/deployment-issue[Troubleshooting - Deployment Issue^]

****

****

[source%nowrap,bash,{source_attr}]
----
# @author D瓜哥 · https://www.diguage.com


----


== Troubleshooting - Deployment Issue 1

https://killercoda.com/sachin/course/CKA/deployment-issue-1[Troubleshooting - Deployment Issue 1^]

****

****

[source%nowrap,bash,{source_attr}]
----
# @author D瓜哥 · https://www.diguage.com


----


== Troubleshooting - Deployment Issue 2

https://killercoda.com/sachin/course/CKA/deployment-issue-2[Troubleshooting - Deployment Issue 2^]

****

****

[source%nowrap,bash,{source_attr}]
----
# @author D瓜哥 · https://www.diguage.com


----


== Troubleshooting - Deployment Issue 3

https://killercoda.com/sachin/course/CKA/deployment-issue-3[Troubleshooting - Deployment Issue 3^]

****

****

[source%nowrap,bash,{source_attr}]
----
# @author D瓜哥 · https://www.diguage.com


----


== Troubleshooting - Deployment Issue 4

https://killercoda.com/sachin/course/CKA/deployment-issue-4[Troubleshooting - Deployment Issue 4^]

****

****

[source%nowrap,bash,{source_attr}]
----
# @author D瓜哥 · https://www.diguage.com


----


== Troubleshooting - Deployment Not UP-TO-DATE

https://killercoda.com/sachin/course/CKA/deployment-rollout-resume[Troubleshooting - Deployment Not UP-TO-DATE^]

****

****

[source%nowrap,bash,{source_attr}]
----
# @author D瓜哥 · https://www.diguage.com


----

