---
title: "关于高中求学的一些问答及提醒"
date: 2024-08-17T15:30:12+08:00
draft: false
keywords: ["高中"]
tags: ["个人提升"]
categories: ["个人成长"]
thumbnail: "images/life/gaozhong.jpg"

weight: 1
---

家里一个亲戚今年参加中招考高中，由于成绩不是很理想，所以，就面临一个问题：**选择哪所高中去求学？**由此引发的一系列思考和讨论，D瓜哥觉得非常有共性，分享出来，希望给需要的家长一个参考。

:sectnums:

== 去重点高中怕跟不上，选择去上私立高中

一些家长可能会有这样的想法：孩子中考成绩不理想，如果去重点高中，担心孩子跟不上课程，所以，选择去上私立高中。

关于这个问题，是一个伪命题。**高中最重要的考核就是三年以后的高考。**高考对所有参加的考生都是一视同仁的，不会因为私立高中和公立高中而有什么差别。（同一个省的高考生是一样的，跨省则不一定。这里不予讨论。）所以，**只要上高中，就必须努力跟上，尽力向前冲！**否则，就会掉队，考不上大学，考不上大学，就失去了上高中的主要意义。所以，根本无需考虑能不能跟上的问题。这个问题只有一个选择：**只要求学，就只能加油往前冲！**

== 选择高中的关注点

由于孩子成绩不理想，那么可能无法进入理想的中学。接下来的一个问题就是：*如何选择高中？*

对于这个问题，私以为**对于高中的的考察标准只有一条：就是高考录取率，各个层次本科的录取率。**但是在选择高中时，有一些值得关注的点，下面一一说明。

=== 生源质量

聪明的学生在任何高中都有好的成绩。脑瓜子不灵的学生，即使送到人大附中这样全国最好的高中也难有好的成绩。

另外，如果身边有一些成绩好的同学，那么当自己学习有问题时，可以更方便地找同学帮忙解答。如果身边事一群瓜娃子，出现学习问题，也无法及时解决，日积月累，成绩自然难以提高！

=== 学校的历史成绩

成绩好的学校大概率会一如既往地好下去。而差的学校想变好，却需要付出非常巨大的努力和相当长的时间来改善。它还需要时间，逐步向社会来证实它的实力，以求获取更好的生源。对于学校来说，这个时间是可以耗得起的。但是，作为学生，上学的时间段时是卡死的，耗不起，也等不起。

=== 老师资历

好的老师有更好的教学方法，对学生学习更有帮助。

但是，好的师资也需要好的学生来衬托。**老师和学生是相互成就的。**只有伯乐，没有千里马，伯乐只能悲叹“英雄无用武之地”！

=== 学习氛围

大多数人都从众。所以，学习氛围好的地方，大部分人会被带动起来学习。但是，如果学习氛围一般，大多数人就会随波逐流，逐步落伍。

=== 私立高中的困境

目前，国内大多数人更愿意相信公立高中。认为公立高中有政府托底，更有保障。而对私立高中，大多数人缺乏足够的信任。

当然，还有一个原因是私立高中普遍学费高昂，这对于很多家长来说，也是一个不小的负担。

=== 小结

所以，综合上述情况，导致的结果是，大多数情况下私立高中的生源质量普遍一般，甚至不好。由于生源质量问题，导致无论是学校的历史成绩，还是学校氛围，可能都会差强人意。所以，如果家长希望通过上私立高中来提高孩子成绩。综合来看，个人觉得很难实现，甚至基本不可能（可能比买彩票中大奖的概率要高一点）。最后的结果，可能钱也花了，时间也耽误了，孩子也没有太大的起色，最后高考成绩也不理想。

还有一个种情况，从小就一直上私立学校的情况，这种大多数是双语教学，面向的也是国外的大学，大部分是不把高考作为第一选项的。这种情况，不在此讨论范围。

== 转学

如果一个学校不行，在条件允许的情况下，尽快转学，转到更好的学校。这个时候，由于入学晚的原因，可能不容易合群，家长要多鼓励和开导，提供足够的情绪价值，帮助孩子早日完成过渡。

另外，学生也不要太在意，一般情况下，等到上高二会进行二次分班，大家又都从新开始了。

== 培优班

如果一个学生没有考进更好的中学，去了一所一般的高中，而且还进培优班了。这里有三点需要注意：

. 如果不是托关系进培优班，那么只能说明这个高中生源质量确实一般。
. 成绩一般的学生在培优班里，有可能每次考试都是班里垫底。这就要多去关注一下学生在整个高中的整体成绩排名。好的情况是，在班级垫底，但在年级总体排名靠前，这种情况家长要多鼓励学生，培养学生有一颗强大的心脏。
. 另外一种情况是，由于可能长时间在班级成绩排名垫底，这对学生来说，无形中会带来很大的压力，导致有些学生可能会自暴自弃。所以，家长要做好安慰和支持，多发现学生的优点和长处，多鼓励孩子。

== 相比私立高中的更优解

如果有能力支付私立高中的钱，相对来说，另外一条路可操作性更大一些：*尽力去层次更好的公立高中，把省下来的学费给孩子请一对一的私教辅导。*

== 私教辅导

学生有各种各样的性格，老师也有跟种各样的教法，所以，孔子提出要“因材施教”。如果学生和私教老师不是很契合，那么请私教老师不一定就能提高成绩。如果已经请私教的情况下，家长一定要多关注学生的反馈，了解学生的学习情况，判断是否合拍，*如果不合适，要尽早更换私教老师。*

== 高中成绩可以突飞猛进

无需太过担心孩子的高中入学成绩排名。以D瓜哥的上学经历来看，在高一，学生的成绩排名会有剧烈的波动，有人入学成绩很差，后来迎头赶上的；也有人入学成绩很好，但后来却跌落谷底。所以，只要学生初中不掉队，*上了高中肯下功夫学习，成绩就会逐步提高。*（掉队的学生可能就不会想着去上高中了）

== 不要选择职高或“3+2”大专

还有一个选项：选择职高或者是“3+2”的大专。私以为，这个选项可以直接忽略，除非迫不得已。

大多数成绩还可以的学生都去上高中了，所以，能选择去上职高或者大专的，大部分成绩都一般，甚至很差。结果，大部分人可能就会不学无术，聚众打架斗殴。最后，孩子不仅可能没学好，甚至沾染了一堆坏毛病。

另外，现在学历贬值严重，满大街都是本科生，大专生更没出路（可以看看现在公务员招聘都要求什么学历）。上了大专，如果想有出路，还要考专升本，相当于一次高考，那为何不直接上高中呢？

当然，在职高或者大专里面，也不乏一些学有所成的人才，但这样的概率太低了。这个问题，不再争论，争论就是你对。

:!sectnums:

== 总结

综合上述的讨论，*对于孩子上学，最优解就是上尽可能好的高中。如果上不了最好的高中，那就选次一点的公立高中。如果家庭条件允许，可以给孩子请一些私教辅导，来帮助孩子提高成绩。*

最后，送给正在求学的学子们一句话：**你充满了潜能，但你的努力还远远不够！**祝福每一个学子学有所成！

