---
title: "《远见》之读书笔记"
date: 2020-08-14T20:58:23+08:00
draft: false
tags: ["读书","笔记"]
categories: ["方法论","个人成长"]
thumbnail: "images/books-on-book-day/the-long-view.jpg"
weight: 1
---

最近向一个朋友了解一家公司情况时，聊到职业发展的问题。就随手推荐了《远见：如何规划职业生涯3大阶段》这本书。正好利用这个机会，把以前的读书摘要发布出来。

这本书，D瓜哥在 https://www.diguage.com/post/goodbye-2019-hello-2020/#the-long-view[告别 2019，迎接 2020：《远见》] 中也提到过。这里把当时写的读书笔记直接拷贝过来：

本书讲人生的职业生涯分为三个阶段：

第一阶段是强势开局的时候。你在职业上的努力必须着重于为前方的漫长道路挖掘和装备自己。你的学习曲线要比职位、职称更加重要。在这一阶段，要为职业生涯打好基础并建立起良好的早期习惯。

第二阶段是聚焦长板的时候。该阶段的首要目标是寻找自己的甜蜜区，即你所擅长的、所热爱的和这个世界所需要的这三者之间的交集。这个时候你要展现自我，让自己鹤立鸡群，想方设法平稳地走在那条收获最大的职场路径上。你要专注于自己的长板，且大可忽略自己的短板。

第三阶段致力于实现持续的影响力，以及寻找一条可以稳定延续到60多岁甚至70多岁的新的可持续职业道路。你要在第三阶段完成三个关键任务：完成继任计划、保持关联性，以及为自己点燃一团新的职业之火。


用一句话来总结：第一阶段：加添燃料，强势开局； 第二阶段：聚焦长板，达到高点； 第三阶段：优化长尾，持续发挥影响力。

三大职场燃料来源：可迁移技能、有意义的经验和持久的关系。

5个数字，树立正确的职场思维

. 职业生涯的长度：用62减去你目前的年龄。
. 精通一项技能所需的时间：要花多少小时才能在某一方面达到“精通”？
. 40岁之后能赚到的个人财富百分比：在40岁之后，你赚到的钱会占你一生个人财富的百分之多少？大部分人的估计是60%。
. 社交货币：你有多少社交网络好友？
. 职场支持者的人数：你认为能在“职业生涯的天堂”里遇到多少人，也就是说有多少人能对你的职业生涯和人生带来真正的变化？

*这本书强烈推荐给对未来职业有追求的小伙伴！*

好戏开始，下面👇是读书摘要：

---
// 
---




== PART 1　远见思维与工具箱

=== 远见思维：多行动，少忧虑

. 职业生涯的持续时间长得惊人，包括了三个截然不同的阶段。
+
第一阶段是强势开局的时候。你在职业上的努力必须着重于为前方的漫长道路挖掘和装备自己。你的学习曲线要比职位、职称更加重要。
+
第二阶段是聚焦长板的时候。该阶段的首要目标是寻找自己的甜蜜区，即你所擅长的、所热爱的和这个世界所需要的这三者之间的交集。
+
第三阶段致力于实现持续的影响力，以及寻找一条可以稳定延续到 60多岁甚至 70多岁的新的可持续职业道路。
+
. 职场燃料很重要，因为职业生涯的基础决定结果。
+
这种燃料有三个主要来源：可迁移技能、有意义的经验和持久的关系。
+
. 职业生涯需要通过对时间的巧妙投资来构建。
. 职业生涯并不是以线性或者可预测的方式发展的。
. 职业生涯远不止于一份工作，而是生活的一大部分。

*实现职业规划要做到的5件事*

. 学习职场数学，树立正确的长期思维方式。
. 盘点职场清单，梳理你最有用处的技能、经验和关系。
. 进行“ 100小时测试”并完成一份“个人时间档案”，从而了解你目前的时间投资状况。
. 在尝试建立新的职场路径或者在多个选项中抉择时，运用“职场路径向导”（ Career Path Navigator）。
. 时刻更新你的职业生涯
+
--
* 我如何避免被机器取代？
* 我能在哪里以什么方式找到工作？
* 未来我将如何分配时间？
* 我会把钱花光吗？
* 工作如何能让我更幸福？
--

=== 三大阶段，聚焦 45 年职业生涯

* 第一阶段：加添燃料，强势开局；
* 第二阶段：聚焦长板，达到高点；
* 第三阶段：优化长尾，持续发挥影响力。

*第一阶段：加添燃料，强势开局*

职业生涯前 15年的唯一目标就是为接下来的两个阶段打好基础。

第一阶段是探索和弥补自身短板的时候。如果你是个糟糕的演讲者，那就去参加相关的培训课程。如果你对待团队成员过于强势或弱势，那就去参加领导力培训。学习要比纯粹的成功更重要。有时跌倒并不可怕，只要你能吸取教训，并将这些经验加以利用就行。

*第二阶段：锚点甜蜜区，聚焦长板*

第二阶段是在你的长板、你的爱好以及这个世界的需求之间寻找交集的时候。

坦率地承认自己的短板，针对它们招募盟友，你就可以把大多数时间放在核心长板上了。

*第三阶段：优化长尾，持续发挥影响力*

第三阶段的主要目的是确定接班人，即给继任计划画上完美的句号，从执行或领导的角色转变成顾问或辅助的角色。

保持关联性是你在第三阶段的工作之一。

=== 储备三大职场燃料

[quote, 伊斯雷尔莫尔·艾瓦（IsraelmoreAyivor）]
____
你的领导力是由你的学习意愿助燃前行的。
____

聪明的职业策略应该是，在整个职业生涯中积累职场燃料并不断更新，同时精明地消费它们。

职业生涯中存在三种基本形式的职场燃料，每一种对获得长远的成功都非常重要。

* 可迁移技能；
* 有意义的经验；
* 持久的关系。

*1号燃料：可迁移技能*

* 解决问题的能力
* 说服式沟通技巧
+
--
无论你最后进入哪个行业，说服力都是一种受用一生的关键技能。

那些无法说服别人接受他们想法的人在职业生涯中都会受挫、贬值。

在测试讲故事的能力时，你会发现一件事：简单制胜。

你应该使用人们听得懂且能戳中他们痛点的文字和形象。

下次你遇到什么棘手的挑战时，也可以试试“给妈妈写信”。

说服力的一部分来自令人叹服的事实，它能让人们真正有理由相信你。

当你谈到自己如何想方设法找到可靠的信息来源并加以记录时，就会传达给听众一个信号：你做了充分的准备，你的观点具备可信度。

如果你无法确保自己能在面对面沟通、书面表达与在台上和镜头前发言时做到说服式沟通，那就不如将它当成一项基本的职业挑战，从现在开始就投入时间。
--
+
* 完成任务的能力：
+
但如果你能持续完成任务，这就是一项强大的受用一生的职业技能。
+
* “人才引力”：
+
--
有能力吸引和调动尖端人才的个人领袖通常都能成功。将优秀的人才招揽到身边能让你把工作做得更好，并扩大影响力。这个能力是区分优秀与顶尖的因素之一。“人才引力”不仅能让人在个人业务上表现出色，而且能培养和发展下一代明星人才，并将新鲜血液吸引到组织里。

要培养“人才引力”，首先要有正确的思维方式，即认识到，没有人需要为你工作，必须是他们想要为你工作。

我鼓励年轻的领导者在加入一个团队几年后评估一下自己的“人才账户”。你们可以审视自己的每一次关键时刻，试着评定自己的行为对“人才账户”起到了增益还是衰减的效果。
--
+
* 帮助和求助的能力：
+
--
在畅销书《沃顿商学院最受欢迎的成功课》（ Give and Take）中，亚当·格兰特用令人信服的证据说明，成为一个成功的“付出者”（ Giver）能让你在生意和生活中都更有效率。

“获取”是只索取不付出，“互利”是在付出的同时期望得到某种回报，而“付出”是无条件地给予，对收获回报并没有太大的期望。付出者是净输出者，在利他性、责任心、社会正义和同情心这几点上比较突出。据格兰特所说，成功的付出者就是付出超过获取的人，跻身最杰出和最幸福行列的机会会比别人大得多。

学习如何寻求帮助和如何提供帮助，会成为职场持久战中一项强大的可迁移技能，而且后者是最重要的。
--
+
* 情商（ EQ）：
+
--
丹尼尔·戈尔曼（ Daniel Goleman）是情商领域的先驱者，在他的著作《情商 3》（ Working with Emotional Intelligence）中，戈尔曼指出，影响业绩和优秀程度最重要的因素就是情商。

戈尔曼得出了一个惊人的结论：在每个领域要想成为业绩精英，情商的重要性比智商或专业技能高一倍。对领导者而言，区分精英与普通人的标准几乎 90%都在于情商。

培养情商是个很实际的问题，但也会为具备职业生涯思维的人提供一个切实的机会。

我向他推荐了一些这方面的好书，其中包括丹尼尔·戈尔曼的《情商 3》与布拉德伯利（ Bradberry）和格里夫斯（ Greaves）的《成功 EQ密码》（ Emotional Intelligence 2. 0）。
--

另外三个我最喜欢的迁移技能：

. 如何与别人进行眼神交流和握手。
. 如何搜索信息。
. 如何呼吸。

*2号燃料：有意义的经验*

我通常会在候选人的背景中寻找多样性经验，确保他们拥有适应性和灵活度。

在不同的环境中尝试不同的事情、试验不同的做事方法，这样能创造出更强的决策技能。

在遗传学中，一定程度的遗传多样性和基因突变会创造出更有活力的物种。也许一个拥有多样经验的“职场杂种”要比只能做同一件事的“职场纯种”更有优势。

如果我现在要开始自己的职业生涯，那么一定会把至少一个阶段放在电子商务上。

*3号燃料：持久的关系*

* 你的上司。
* 你的客户。
+
“eBay因素”也适用于客户关系。我时常问奥美的领导者：“如果把你放在网上拍卖，会有哪些客户为你‘竞价’，点名要你呢？”
+
* 商业伙伴。
* 身边的人才。
* 找到你的同类。

社会学家查尔斯·汉迪（ Charles Handy）提出了一项很好的假设性练习：想象一下，当你 40岁时不得不永远告别自己的工作，以一己之力创立一家公司，你会怎么做？这是一个很好的测试自主力的练习。

=== 五个数字，树立正确的职场思维

[quote, 约翰·汉茨（ John Hanc）, 马拉松运动员兼作家]
____
我认识到能完成一场马拉松不仅是一项运动成就，而且是一种心理状态，一种一切皆有可能的心理状态。
____

*5个数字带给我们的思考*

. 职业生涯的长度：用62减去你目前的年龄。
. 精通一项技能所需的时间：要花多少小时才能在某一方面达到“精通”？
+
仅有天赋是不够的，无论你拥有多高的智商或天赋，成功都需要花费超乎想象的时间进行高强度的练习。
+
. 40岁之后能赚到的个人财富百分比：在40岁之后，你赚到的钱会占你一生个人财富的百分之多少？
. 社交货币：你有多少社交网络好友？ 
. 职场支持者的人数：你认为能在“职业生涯的天堂”里遇到多少人，也就是说有多少人能对你的职业生涯和人生带来真正的变化？

*职场望远镜*

职业生涯的长度：用 62减去你目前的年龄。

精通一项技能所需的时间：到至少需要 10 000小时的密集训练和练习。 

40岁之后能赚到的个人财富百分比： 85%～ 90%，因为大多数人的财富积累要蓄力到 40岁、 50岁甚至 60岁才爆发出来。

社交货币：并不是越多越好。

职场支持者的人数：找到 3～ 5个真正能称为导师的人。


=== 四大黄金问题，评估职业价值


[quote, 马尔科姆·格拉德威尔, 《异类》]
____
没有人能孤军奋战，摇滚明星不行，职业运动员不行，软件业的亿万富翁不行，就连天才也不行。
____

. **联系人**是职业生态系统中未经改良的原料，包括我们的领英联系人、邮箱联系人、校友、同事等。
+
在建立人脉关系网和真正的人际关系之间存在重要的区别。人脉关系网的构建者的心态是交易性的，他们在追求人际关系时只考虑其他人能为他们做什么。而人际关系的构建者会首先尝试帮助别人，他们不会有所保留。虽然他们心里清楚大部分好意都会得到回报，但是并不会精于算计。他们还会时刻维护自己的人际关系，而不是在需要的时候才想起来。
+
. **专家团**处于职业生态系统中一个较高的层次。
. **关键同事**是在目前的公司里对你的发展拥有决定性影响力的 5～ 10个人。
. **支持者**是在职业生涯中帮忙提建议、拥护你、激励你的导师和帮手。
+
蟋蟀文化公司（ Cricket Media）的首席执行官卡佳·安德烈森（ Katya Andresen）为我们定义了三类人生导师：明星，他们是成功的行为榜样，告诉我们如何成功；贤者，他们就像苏格拉底，并不为我们提供答案，而是教我们如何思考；策动者，他们激励我们，鞭策我们，偶尔迫使我们踏出关键的一步。
+
阿尔瓦罗说：“你得确保自己的导师不仅拥有过去的智慧，而且能在你的过去、现在和未来提供助力。”
+
. **你自己。**任何职业生态系统的核心都是你自己。

*四个黄金问题*

. 我是否正在学习和成长？
. 我是否正在对某些人、现在的公司，乃至整个社会拥有影响力？
. 我体验到乐趣了吗？
. 我是否得到了适当的奖励，并创造了经济价值？


*职场望远镜*

职场燃料之可迁移技能：学术学位、专业证书，语言，优点，情商，“人才账户”。

职场燃料之有意义的经验：个人旅行，海外工作经验，企业管理、创业经验，社区、志愿者活动，做出个人贡献的项目，公开演讲、写作、表演的经验，教学、咨询、指导的经验，工作之余的热情所在……

职场燃料之持久的关系：联系人，专家团，关键同事，支持者。

年度职业价值评估问题1：我是否正在学习和成长？

年度职业价值评估问题2：我是否正在对某些人、现在的公司，乃至整个社会拥有影响力？

年度职业价值评估问题3：我体验到乐趣了吗？

年度职业价值评估问题4：我是否得到了适当的奖励，并创造了经济价值？

=== 一百小时测试，合理投资时间

[quote, 卡尔·桑德堡（ Carl Sandburg）]
____

时间是你的人生货币。它是你唯一拥有的货币，而且也只有你能决定如何消费它。
____

=== 职场路径向导，做出正确的职业决策

[quote, 罗伊·迪士尼（ Roy E. Disney）]
____
如果你的价值观很明确，做决定就变得更简单了。
____


[quote, A． J．雅各布斯（ A. J. Jacobs）]
____
做出有益决定的关键是尊重未来的自己。 
____


学习职场数学能帮你树立起正确的思维框架；思考职业生涯的三个主要阶段能提醒你当前在这漫长旅程中的位置；盘点一下职场清单，总结目前的职业生态系统，这会让你了解自己的技能和关系的状态；仔细审视你的时间档案能帮你弄清在职场和生活中可以做出什么样的平衡调整。做完这些，你就万事俱备，可以做出一些明智的决定了。

. 你的职业理想是什么，或者至少假设一个你可能想要达到的目标。
. 你目前手上有什么职场燃料？
. 你需要什么职场燃料才能实现这个终极理想？

奥朗认为，长期成功的基础是快速的成长。

如果要成长得再快一点，你就需要一份满足以下条件的工作：

* 你周围都是比你聪明的人；
* 你有失败的机会；
* 公司有让你这样的人肩负重大责任的传统。

奥朗·霍夫曼还说：“当你有 33%～ 66%的概率失败时，成长的速度也是最快的。要想精进，就得主动站在可能失败的立场上。

“假设你是一个有远大目标的人，想要持续不断地成长，那就一定要找机会晋升，并承担越来越重的责任。那些有相应的机制并且增长速度很快的公司是最有可能快速提拔你的。寻找一些与你背景相似又加入了该公司的人，看看是否有人被赋予了重大的职责。”

“我们总是会低估在未来才能兑现的好处，这种现象被称为‘时间贴现’（ temporal discounting）。

克里斯还在观察中发现了“损失厌恶”（ loss aversion）的效应：“人们对后果和风险看得比好的方面更加清楚。我们的美梦很模糊，但噩梦却很清晰。”

发现新机会是有益的，毫无意义的变化则是有害的。

== PART 2　三大职业生涯阶段

=== 第一阶段：加添燃料，强势开局

[quote, J． R. R．托尔金（ J. R. R. Tolkien）]
____
流浪者未必都迷茫。 
____

很少有人能确切地知道自己想要干什么，尤其是在刚刚起步的时候。

亚当·格兰特在《沃顿商学院最受欢迎的成功课》中说：“如果人们对职业生涯早期的期望能更现实一些就好了。”

并不是为了找到一份你每天都津津乐道的神话般的工作，而是要找出你擅长什么、不擅长什么、喜欢做什么，以及不喜欢做什么。

司徒慕德爵士（ Mark Moody— Stuart）说过：“职业生涯绝不是一条笔直上升的路线。我们常常需要为了前进而后退，为了变得更好而变得更坏，为了获得进步而投入资本。最好的旅途总是发生在迷路时。”第一阶段的策略很简单：步入职场、迎接新发现，并为前方的漫长旅程储备职场燃料。

*给首次求职者的8个小提示*

. 利用在读的时间储备早期形式的职场燃料。
. 制订求职作战计划。
. 积极参与校园招聘。
. 高效地进行在线申请。
. 最重要的是，用好你的联系人。
+
是有关系可以大幅提高你的反馈率.
+
有一种极好的建立新关系的方法，那就是好好利用校友网络和领英这样的人才数据库。
+
. 在与联系人见面之前，做些功课。
+
--
在与别人的交谈中，我被问过一些很有意思的问题：

* 这个行业有什么特别之处？
* 你喜欢或不喜欢这份工作的哪些方面？
* 在你的公司取得成功需要哪类技能？
* 你是怎么得到这份工作的？
* 你们公司的企业文化是什么样的，与其他公司的有何不同？
* 人们现在都是如何进入你这个行业的？（可能与过去有所不同。）
* 有什么挑战会让你彻夜难眠？
* 你认为这个行业的引领者是谁？
* 你知道你的公司有什么合适的职位空缺吗？（直接问，没关系。）

还有一个你每次都必须提出的万能问题：

* 你能不能再推荐一家公司或一个人，让我跟它或他聊一聊？
--
+
. 但是，找到第一份工作依然难于上青天！
+
--
善意实业的团队找到了所谓“基于长板的模型”（ strengths— based model）的成功方法。

琳达说：“在每一次成功的求职背后都有两个关键点：成功的意愿以及联系人与支持者组成的后援团。”

善意实业发现，微小的成功对于培养动力和信心能起到很大的作用，

外面的世界困难重重，但是没有人有资格抱怨这一点，总有人的情况比你更艰难。勇敢参战，坚持执行计划，你一定能成功步入职场。
--
+
. 探索。
+
格林观察后发现，每一次成功都必得先经历 10次尝试和前 9次的失败。通过不断试验，才能发现真正的热情、道路或目标。他强烈建议人们在职业生涯的早期多多关注眼前出现的机遇和自己的反应，即你关注什么、你把精力放在哪里、你听信谁的声音，以及你选择阅读谁的文字。

“如果你只是为了入选《福布斯》 30岁以下富豪榜而创建自己的公司的话，这么做就不值得。如果你想要成为企业家赚大钱，就别走这条路。如果你发现了某样让你着迷、让你夜不能寐的东西，那么这就是你应该追求的一条路。”

“白天严格遵循计划才能给夜晚带来开放的选择。”

**如果你认真对待自己的职业生涯，那就需要了解更多的情况，搞清楚公司是怎么运转的：它怎么建立的，它的理念是什么，它如何赢利，它的关键人物有哪些，以及它的愿景如何。**如果你从公司的常规宣讲中得不到这些问题的解答，那就把它当成入职100天的一个任务吧。做好本职工作，阅读公司的年报，如果能找到外部分析机构对公司的评估就更好了；在茶歇时间，在新老员工中打听公司的内部消息；通过加入公司内部的俱乐部、团队或职业社交网络来提高参与度；主动在公司的活动中帮忙，并且尽心尽力；慢慢地建立由你的联系人、专家团、关键同事和支持者组成的职业生态系统。

何不拿出一个高层领导或客户正在苦思冥想的具体问题，跟你的老板讨论讨论呢？

另一项值得培养的早期习惯是高效沟通。

* 首先，话题是什么？
* 其次，写下你的三个重点，加上用于佐证的事实和原因加强说服力。这意味着你既有观点，又有支撑它的证据。
* 最后，直白地说出你希望听众接下来怎么做。

要想真正地出类拔萃，你就得成为一个能把故事讲好的人。

想象一下一张你亲笔书写的小小纸片会给别人带来多大的冲击力。

第一阶段的最后一项技能是理解自身的价值，以及为自己的贡献争取公平的奖励。

判断报酬和获得的认可合不合适，看的是贡献，而不是资历。

找你的上司一对一地聊一聊，最好再找至少一名导师沟通一下。问问他们，你所关注的优先事项和目标是否正确，也就是说，它们是不是对于公司及其业务有真正价值的东西，而不是细枝末节的小项目。

“生活不是线性的，它无法在教室里学会，而是要在实践中学。而最好的作品是在你不工作的时候诞生的。”

“年轻人是未来。对公司而言，在接下来 5年左右的时间里，将有超过 50%的劳动力都是千禧一代。各大品牌在数字和社会化营销上耗费了数百万美元，而主宰其成败的就是千禧一代。全世界的政府正在迎来由年轻人决定投票结果的选举，”他解释说，“当你看到这一变化时，就会意识到让年轻人更好地分享想法、收获思想和踏出第一步是多么重要了。”

*职场望远镜*

步入职场策略1：利用在读的时间储备早期形式的职场燃料。

步入职场策略2：制订求职作战计划。

步入职场策略3：积极参与校园招聘。

步入职场策略4：高效地进行在线申请。

步入职场策略5：用好你的关系。

步入职场策略6：与联系人见面之前，做些功课。

步入职场策略7：做好心理准备，找到第一份工作难于上青天。

步入职场策略8：不断探索。


=== 第二阶段：锚定甜蜜区，聚焦长板

[quote, 彼得·德鲁克（ Peter Drucker）]
____
高效管理者的基础是他们的长板。
____

如果说第一阶段是寻找你的甜蜜区，那么第二阶段就是锚定它。**你要不断问自己这三个难题：我擅长什么？我爱好什么？这个世界需要什么？**

在第二阶段则要创造真正的差异。


格林补充说，**创造精通技能的秘方就是意愿和时间。**“我们都知道，当我们充满干劲时能钻研得多深。如果这个主题令我们感到兴奋，如果它能激起我们最深的好奇心，或者如果我们为了丰厚的利益而必须学习，那么我们就会投入明显更多的注意力。我们吸收的东西会沉淀下来。如果我们身在法国，需要学会他们的语言，或者突然爱上了一个不怎么会说英文的法国美女，那么我们在几个月内学会的东西就会比在 4年的法语课程中学到的更多，而不管当时的法语课老师有多厉害。换句话说，我们的专注度决定了学习的深度。”

保持一直向前的动力，就能持续成功

“梦想要大，但前进的步子要小”。

领导者必须飞得足够高，才能用战略的眼光俯瞰全局。

能力强的领导者还需要有极度关注细节的能力，这样才能解决棘手的问题或谈下一笔生意。

不要一直做飞在高空的宇航员，也不要一直做飞在低空的扫地机。

*给初任管理者的6条建议*

. 你的仪容、态度和举止正受到高度的关注和广泛的效仿。
. 一旦你确定了某个愿景，就应该简洁地表达出来，并且不停地重复重复再重复。
. 早早决定让谁上船。
. 每一个有意义的商业问题都是少数人在一间安静的小会议室里解决的。
. 你要表现得像个被人信赖的解答者，而不是高高在上的老板。
. 你并不是无所不知。

// 

* **学习**：我是否正在积累有助于成长的新的技能、经验和关系？
* **影响力**：我是否正在改变个人、公司，甚至整个社会？
* **乐趣**：我的职业总体上算不算我生活中正能量和乐趣的来源？
* **奖励**：我是否正在积累经济价值？

*顶级首席执行官需要具备的5大特质*

. 诚实和契合。
. 智力上的好奇和敏捷。
. 提升业务业绩的历史记录。
+
提升首席执行官业绩的一项潜在因素就是“决心和自控力”。决心是不畏艰险专注于某一目标的能力，自控力指抵抗分心和诱惑的能力。拥有极强的决心和自控力的领导者总是能取得更好的成果。
+
. 真实、自我意识以及平衡。
. 活力和热情。

*职场望远镜*

初任管理者的建议 1：时刻注意你的仪容、态度和举止。

初任管理者的建议 2：简洁地表达你的愿景，并且不停地重复。

初任管理者的建议 3：尽快选好团队成员。

初任管理者的建议 4：每一个有意义的商业问题最好能在较小的团队中解决。

初任管理者的建议 5：表现得像个被人信赖的解答者。

初任管理者的建议 6：你并不需要无所不知，而是应该多多找人咨询。

首席执行官的特质 1：诚实，与公司的文化契合度。

首席执行官的特质 2：智力上的好奇和敏捷。

首席执行官的特质 3：有提升业务业绩的经验。

首席执行官的特质 4：真实、自我意识以及平衡。

首席执行官的特质 5：活力和热情。



=== 第三阶段：优化长尾，发挥持续影响力

[quote, 阿尔贝特·施韦泽（ Albert Schweitzer）]
____
有时，当我们自己的火焰熄灭，会有人用他们的火花将其重新点燃。每个人都应该对那些点燃我们内心之火的人满怀谢意。
____

“我从来没有喘息的机会。如果你真的擅长某件事情，他们就会给你更多的责任和工作，而不是更少。公司要看到的不是顺从，而是业绩。要想让你的老板和公司取得成功，除了努力工作，别无他法。”

“重要的不是管理你的职业生涯，而是管理你的学习曲线。你要让自己的学习曲线陡峭，要勇敢面对困难的问题，并自愿接受挑战。”

停车熄火一定要慎重再慎重。但似乎只有少数人能够把这一点真正做好。对大多数人而言，能减速就最好只减速，不要完全停下来。这条建议还有后半句：“下车的时候音乐不能停。”也就是说，要在你过去这些年建立起来的乐趣和声誉还没失效之前行动。

*职场望远镜*

合理规划第三阶段的建议1：试验，自愿接受挑战。

合理规划第三阶段的建议2：创业，开辟全新疆域。

合理规划第三阶段的建议3：管理学习曲线，保持关联性。


== PART 3　应对职场和生活的冲突

=== 如何做好职场父母？

*职业生涯与为人父母的共存之道*

. 不要让职业生涯和为人父母成为非此即彼的选项。
. 找到一个热爱家庭的雇主。
. 如果没有后方的恰当支持，你就无法生存。
. 设立现实的期望和严格的界限。
+
永不拒绝可能最终会招致灾难，你需要掌握“有条件地接受”的技能。
+
“你要让他们放心，知道他们才是你生命中最重要的东西。重要的不是时间，而是感觉。”
+
最善于划定界限的人都能清晰地指出，哪里有余地，哪里又有阻力。“
+
. 管理你的时间和精力。

*成功回归的4个关键*

. 重新包装你的技能。
. 重新组织你的经验。
+
你必须重新组织自己知道的东西，并将其与现在和未来客观地联系起来。研究一下你想要重新进入的行业的未来愿景，订阅一些潮流的行业出版物和博客，将你的技能、智慧和经验与雇主的情况及他们的目标适当地加以结合。只有当你的过去能够帮助潜在雇主取得成功时，它才有意义。
+
在更新了行业与公司的相关知识和语言之后，就该确定你与它们的契合点了。
+
. 重新连接职业生态系统。
. 重新建立你的自信。

“回归生”理应成为一个全球现象，其原则是重构过去的经验、重塑技能集合、重新连接职业生态系统和重建自信。配平职业生涯和为人父母的方程式会给你带来巨大的回报：更高的生产力、更强的创造力和更幸福的生活。

*职场望远镜*

职业生涯与为人父母共存之道 1：不要让职业生涯和为人父母成为非此即彼的选项。

职业生涯与为人父母共存之道 2：找到一个热爱家庭的雇主。

职业生涯与为人父母共存之道 3：找到后方的恰当支持。

职业生涯与为人父母共存之道 4：设立现实的期望和严格的界限。

职业生涯与为人父母共存之道 5：管理你的时间和精力。

回归正轨之法 1：重新组织你的经验。

回归正轨之法 2：重新包装你的技能。

回归正轨之法 3：重新连接职业生态系统。

回归正轨之法 4：重新建立自信。


=== 如何看待跨国工作？

环游世界的愿望一直都是人们最高的人生目标之一。

国际化思维是一项可迁移性非常强的技能，因为它让我们能欣赏多种多样的思想和文化。它有助于开启新的机会之门，带来全新的经历。

=== 如何应对职场危机？


[quote, 迈克·泰森, 世界重量级拳王]
____
每个人都有一个计划，直到被打掉牙的那一刻。
____

*应对职场危机需要知道的5件事*

. 应对职场危机的第一步应该是清晰客观地认识问题。
. 有时候，职场危机可能是由他人对你的技能、目标或业绩的错误认识引起的。
. 在其他情况中，你的不足之处可能并不只是认知上的，而且是真实存在的。
. 有的职场危机是可以预见并规避的。
. 无论你的职场危机是不可预知的还是可以预料的，你都需要从逆境中快速恢复的方法。

健康的自信心是好的，虚张声势、否认一切和痴心妄想却都是毁灭性的。脆弱是过度保护的恶果，逆境和压力是有益的。

在太空的失重环境下，我们的骨骼失去了压力，于是就会变得脆弱。你的自信心必须建立在有市场竞争力的东西上面。

在遭遇职场危机时，请将骄傲放在一边，它会碍事的。

利用好奇和探索的武器培养技能和经验，建立起能抵挡不可避免的挫折的免疫系统；不断寻找自己的理想，如果不知道什么才是重要的，那么就回归人性；确保你的信心是有根据的，如果你的失败并不主要源于坏运气，那么就得采取行动，找出欠缺的关系或技能；不要让骄傲阻挡了重获新生的道路；你可能需要退一步才能海阔天空；坚持自己的核心价值观和真正的自我。

== 尾声　工作的未来

[quote, 查尔斯·凯特林（ Charles Kettering）]
____
我只对未来感兴趣，因为我的余生将在那里度过。
____

[quote, 威廉·阿瑟·沃德（ William Arthur Ward）]
____
发明家幸福感源自内心。
____

最脆弱的工作大部分本质上都是机械性和重复性的。

克莱尔·凯恩·米勒（ Claire Cain Miller）在《纽约时报》上写道：“合作能力、做事灵活、有同理心，这样的技能在现代工作中的重要性已越来越强。最新的研究表明，需要强大社交技能的职位在 1980年后的增长要比其他职位更加突出。在 2000年之后，工资保持持续增长的少数职位都既需要认知技能，也需要社交技能……

你需要确保能拥有一些与机器的工作不同或互补的人类技能。

我们可以将世界上所有的活动分成“重复性”事情和“创造性”事情。这里的重复性是指像大规模生产、程序式计算和其他机械性任务。在这个领域，机器占据了统治地位，它们更强大、更准确、更快速、更可靠，也更高效。在创造性领域，人类依然是主宰，我们擅长像发明、分辨歧义和建立人际信任这样的事情。

在未来的世界里，具有职业思维的人将需要更牢固地掌控他们的职业生涯，即顺应内心、顺应职场，并成为一个技能和工作方面聪明的买家。

时间是人生的唯一货币。

*改进3个要素，享受幸福的工作*

. 我们的基因固定值。
. 生活环境。
. 主动的行为。
+
虽然我们无法改变基因的固定值，生活环境的改变又不会对幸福程度带来持久的影响，但是我们可以通过主动的行为来提高和维持幸福水平。

《幸福有方法》大致描绘了12种“基于证据、得到科学研究支持的提高幸福感的策略”。其中包括： 

* 表达感恩；
* 培养乐观的心态；
* 避免思虑过度和社会攀比；
* 多行善事；
* 维护人际关系；
* 发展合作的策略；
* 学会原谅；
* 增加心流体验；
* 享受生活的乐趣；
* 努力实现目标；
* 信仰宗教，寻找精神寄托；
* 关注身体健康。

//

. 增加心流体验。
+
“心流”（ flow）的概念最初是由现任克莱蒙特研究大学特聘心理学教授的米哈里·希斯赞特米哈伊( 32)提出的。在《当下的幸福》（ Flow： The Psychology of Optimal Experience）中，作者将心流描述为：“一个人的技能足以应付眼前挑战的一种感觉。此时，人的精力高度集中，以至于没有任何多余的注意力可以用来思考无关的事情或为其他问题忧心。这个人的自我意识消失了，而对时间的感觉也会发生扭曲。”
+
. 努力实现目标。
. 表达感恩。


*职场望远镜*

面临机器的竞争：明智之举是培养情商、创造力、协作能力和建立信任关系的技能。 

在哪里找工作：像领英这样的在线平台将成为公司寻找人才、个人寻找工作的主要场所。 

将时间投资在哪里：创业和自由职业将在不久的将来蓬勃发展，工作目标也将更多样化。
怎样保持收入稳定：退休并不代表就能安享晚年，继续工作才能获得稳定的收入。 

享受工作的快乐：想在工作中更快乐，就需要提高幸福感，试一试文中的12种策略吧！
