---
title: "《投资中最简单的事》之读书笔记（四）：投资心理学"
date: 2022-02-27T08:38:00+08:00
draft: false
categories: ["阅读摘要"]
tags: ["书籍", "方法论", "投资理财","股票","金融"]
thumbnail: "images/books/the-simple-things-in-investment.jpg"

weight: 1
---

最近一位同事离职，在践行宴会上，大家聊到投资理财，D瓜哥推荐了 https://book.douban.com/subject/35000951/[《投资中最简单的事》^]。去年已经把这本书读完了，下班后把这本书的摘要笔记整理一下，按照章节，分四篇来分享：

* https://www.diguage.com/post/the-simple-things-in-investment-1/[《投资中最简单的事》之读书笔记（一）：投资理念^]
* https://www.diguage.com/post/the-simple-things-in-investment-2/[《投资中最简单的事》之读书笔记（二）：投资方法^]
* https://www.diguage.com/post/the-simple-things-in-investment-3/[《投资中最简单的事》之读书笔记（三）：投资风险^]
* https://www.diguage.com/post/the-simple-things-in-investment-4/[《投资中最简单的事》之读书笔记（四）：投资心理学^]

== 第四部分　投资心理学

=== 11　人性的弱点：投资者常见的心理误区

一个股票便宜与否，看估值比看近期涨跌更可靠：基本面大幅超预期时会越涨越便宜，反之会越跌越贵。

美国消费股多，适合价值投资；加拿大资源股多，适合趋势投资。互联网赢家通吃，买龙头；休闲服装百花齐放，买成长。差异化产品，买品牌；同质化产品，买成本低的。

俾斯麦说，每个笨蛋都会从自己的教训中吸取经验，聪明人则会从别人的经验中获益。

同样是错过航班，错过 3分钟的比错过 30分钟的更沮丧；同样是彩票没中，号码与头奖号码只差一点的是最痛苦的。

与成功擦肩而过比从未接近成功更令人难以接受，更令人想再试一次，所以，许多赌博形式正是包含大量“差点就赢”的设计，才吸引了这么多赌徒不惜倾家荡产屡败屡战。

=== 12　后视镜

应该跑向球将要去的地方，而不是球现在所在的地方。

=== 13　傻瓜定价说

对市场敬畏但不屈服，逆市场而动但懂得自我保护。

=== 14　这次不同了

人们从历史中学到的唯一教训就是人们从来不吸取任何教训。

每一次危机或泡沫都感觉像是史无前例，其实不过是历史长河中的一朵浪花。

当人们在为“黄金十年”找论据时，市场离见顶就不远了；当人们在为长期的悲观寻找理由时，市场已经在底部区域了。投资者的悲哀，永远是轻易地放弃和错误地坚持。

=== 15　树动风动心动

短期来说，股价波动是人心与人心博弈的结果，是心在动，难以预测。中期来说，股价更多是由政策面决定：吹的是政策宽松的暖风，股价就上涨；刮的是政策紧缩的寒风，股价就下跌。所以说，中期是风在动。

长期来说，股价是由基本面决定的。那些根基不稳的病树，难以避免在风中被连根拔起的命运；而那些有稳固根基的好树，不管人心冷暖，风向东西，终将成长为参天大树。所以说，长期是树在动。

“心在动”常对“风在动”推波助澜，把五级风放大为十级，此时人们已不关心“树动”与否，反正玩的是击鼓传花的游戏。

== 附录　投资访谈：顺应规律投资，才能事半功倍

过去 10年，人家问我看好什么行业，我在任何时候都是讲三大类行业：金融地产、品牌消费、先进制造。

有“霸王条款”的行业都不会太差。

便宜是硬道理，股票的回报并不取决于它未来的增长快还是慢，而是取决于未来增长比当前股价反映的增长预期更快还是更慢。

我们找白酒的顺序是先找高端，再找次高端，再到平价酒，因为中国经济的复苏通常是先重点扶持基建，商务应酬增加，对高端酒的需求会增加，之后经济恢复，老百姓有钱了，中端酒开始起来，然后再到低端酒。

市场是一个拍卖系统，最后的顶点总是最疯狂的人在定价，就像在拍卖会上面，最后的买主肯定是那个最狂热的、愿意出最高价的人。

一个投资人说过，当一家公司的创始人和管理者，主要是做好两点：一个是算命，即想清楚一些大的战略性的问题；第二是相面，就是选人。

== 后记

大佬为什么对科技股长期持谨慎的态度？为什么热衷科技股的基金经理鲜有长时间业绩突出者？

* 第一，科技进步内在的突变性决定了科技股投资人业绩内在的不可延续性。
* 第二，科学技术是不断变化的。
* 第三，虽然新技术的前景广阔，初期的行业格局却非常散乱，绝大多数投资人很难在事前判断出谁是最终赢家。

临渊羡鱼不如退而结网，投资必须把握你能把握的东西。

知道自己的能力边界，发挥自己的优势，买便宜的好公司，注意安全边际，注重定价权，人弃我取，在胜负已分的行业里找赢家，这些貌似投资中最简单的事，其实也是投资中最本质的东西。
