---
title: "《投资中最简单的事》之读书笔记（二）：投资方法"
date: 2022-02-25T22:34:00+08:00
draft: false
categories: ["阅读摘要"]
tags: ["书籍", "方法论", "投资理财","股票","金融"]
thumbnail: "images/books/the-simple-things-in-investment.jpg"

weight: 1
---


最近一位同事离职，在践行宴会上，大家聊到投资理财，D瓜哥推荐了 https://book.douban.com/subject/35000951/[《投资中最简单的事》^]。去年已经把这本书读完了，下班后把这本书的摘要笔记整理一下，按照章节，分四篇来分享：

* https://www.diguage.com/post/the-simple-things-in-investment-1/[《投资中最简单的事》之读书笔记（一）：投资理念^]
* https://www.diguage.com/post/the-simple-things-in-investment-2/[《投资中最简单的事》之读书笔记（二）：投资方法^]
* https://www.diguage.com/post/the-simple-things-in-investment-3/[《投资中最简单的事》之读书笔记（三）：投资风险^]
* https://www.diguage.com/post/the-simple-things-in-investment-4/[《投资中最简单的事》之读书笔记（四）：投资心理学^]

== 第二部分　投资方法

=== 04　投资的三个基本问题

如果把我过去十几年的投资分析方法做一个简单的概括，最根本的就是要回答三个问题：为什么认为一家公司便宜，为什么认为一家公司好，以及为什么要现在买。这三个问题中，第一个是估值的问题，第二个是公司品质的问题，第三个是买卖时机的问题。

==== 问题1：估值

世界上不存在每年都有效的投资方法。

在好行业中挑选好公司，然后等待好价格出现时买入。

*三板斧：*

. 波特五力分析。不要孤立地看待一只股票，而要把一个公司放到行业的上下游产业链和行业竞争格局的大背景中分析，重点搞清三个问题：公司对上下游的议价权、与竞争对手的比较优势、行业对潜在进入者的门槛。
. 杜邦分析。弄清公司过去 5年究竟是靠什么模式赚钱的（高利润、高周转还是高杠杆），然后看公司战略规划、团队背景和管理执行力等是否与其商业模式一致。例如，高利润模式的看其广告投入、研发投入、产品定位、差异化营销是否合理有效，高周转模式的看其运营管理能力、渠道管控能力、成本控制能力等是否具备，高杠杆模式的看其风险控制能力、融资成本高低等。
. 估值分析。通过同业横比和历史纵比，加上市值与未来成长空间比，在显著低估时买入。

这“三板斧”分别解决的是好行业、好公司和好价格的问题，挑出来的“三好学生”就是值得长期持有的好股票了。

不要被上市公司讲的“美好未来”忽悠了，一定要看现在看得见摸得着的利润、现金流和资产。

==== 问题2：品质

便宜不便宜大多数人都能够判断，因此关键的区别在于搞清楚公司的品质。

三个要素中，投资者真正需要下大力气搞清楚的就是品质。

马和骑师，选马比选骑师重要。

我认为选一个好行业是成功投资的基本条件。

公司的品质好坏，关键是看能不能具有定价权。

你对你的竞争对手怎么看？最近竞争对手有没有什么做法让你特别难受？你最近有没有什么做法让你的竞争对手感到难受？

我为什么不太喜欢政府支持的新兴行业？因为政府的支持其实是增加了供应，增加了行业的竞争对手。

*如何判断公司的品质？*

* 是不是一个好行业？首先是看行业的格局，不要有太多人做，做的人多了，竞争自然就激烈了。
+
扶持其实是鼓励更多的人进入行业而加剧了竞争，打压却限制了新增供给，反而改善了竞争格局并且让行业龙头做大。
+
* 第二个要注意的是差异化竞争和同质化竞争的区别。
** 差异化的第一个标志是品牌。差异化、定价权的一个来源是品牌，而且最好是请客送礼的品牌。
** 差异化的第二个标志是有回头客，即用户黏度高。
** 差异化的第三个标志是单价不要太高。
** 差异化的第四个标志是转换成本。
+
差异化的关键在于能不能提价，提价之后是不是影响销售。
+
** 差异化的第五个标志是服务网络。
** 差异化的第六个标志是先发优势。

对行业格局的分析和对公司核心竞争力的理解是“道”，财务分析只是“术”，但是后者对前者起着验证和把关的作用。

判断一个公司所在的行业好不好，首先是看行业竞争格局是不是清晰，领先者有没有品牌的美誉度，领先者产品的售价是不是显著高于其他竞争者，领先者有没有网络服务的优势，有没有规模效应，产品的销售半径是不是相对比较小（不用参与全球竞争），是不是有回头客，是不是低单价（下游对价格不敏感），是不是转换成本高，领先者是不是有先发优势，技术变化是不是没有那么快。对品质的评判有很多指标，核心是“这是不是一门好生意，有没有定价权，是不是一门容易赚钱的生意”。

我一直强调胜而后求战，愿意买已经把竞争对手打趴下的公司，而不是战而后求胜，在百舸争流中猜赢家。

我认为行业研究员能够给基金经理提供的附加值在于讲出这个行业的特点。

我分析公司、分析行业，更看重的是行业的内在特质和公司的长期经济特征这一类静态的信息，这些是规律性的东西，只有对行业真正理解了才能够说得出来。

一个成功的投资者应该能够把行业到底竞争的是什么说清楚，把这个行业是得什么东西得天下弄明白。

在不同的细分子行业中竞争的东西也是不一样的，投资之前必须把每个细分子行业中决定胜负的因素研究清楚。

即使是同一个行业，投资者也得明白在不同阶段，到底什么因素是决定胜负的关键。

要认识一个行业，不妨做一道填空题：得___者得天下，用一个词来概括这个行业竞争的是什么。例如，基金业是得人才者得天下，高端消费品是得品牌者得天下，低端消费品是得渠道者得天下，无差异中间品是得成本者得天下，制造业是得规模者得天下，大宗品是得资源者得天下。

==== 问题3：时机

投资的第三个大问题是时机。

投资是科学加艺术，在投资的三个基本问题中，估值是最接近科学的，有一整套的方法和规律可以学习；而选时是最接近艺术的，只可悟、不可学，只可意会、不可言传。

对于多数人而言，对待选时的正确态度应该是避免把大量的时间花在试图“抄底”或者“逃顶”上。

彼得·林奇说的“如果你每年花 10分钟在宏观分析上，你就浪费了 10分钟”

*如何在合适的时候加仓？*

* 第一种办法是看估值。
* 第二种办法，是根据各种指标之间的领先和滞后关系进行分析（具体请参读 https://www.diguage.com/post/the-simple-things-in-investment-3/#chapter-10[本书第 10章：四种周期、三种杠杆，行业轮动时机的把握^]）。 
* 第三种办法，是根据对市场情绪的把握和逆向思考进行分析。

“表弟指标”

对于多数人而言，只要把估值掌握好，把基本面分析好，淡化选时，长期来看投资回报就不会差。

历史上的股市见底信号 1．市场估值在历史低位； 2. M1见底回升； 3．降存准或降息； 4．成交量极度萎缩； 5．社保汇金入市； 6．大股东和高管增持； 7．机构大幅超配非周期类股票； 8．强周期股在跌时抗跌，涨时领涨； 9．机构仓位在历史低点； 10．新股停发或降印花税。

估值分析加基本面分析长期来看是行之有效的，

对大公司的分析，我经常需要看这个公司中层的关键绩效指标（ Key Performance Indicater， KPI）是怎么定的。

投资也有一些更为本质的东西是共性的，是放之四海而皆准的，并不会因为国家和行业的不同而不同。作为一个职业投资人，我们要研究的就是这些共性的、本质的、规律性的东西。

如果把投资比成项链，那么投资理念就是线，对公司、行业的具体知识就是珠子。

投资就是要杀鸡用牛刀，因为杀鸡用鸡刀不能一刀毙命，反而容易伤到手，必须集中兵力深度调研打歼灭战。

带兵打仗，人是第一位的，因此即使目前经营环境恶劣，也不能减少对员工和团队的投入。

=== 05　宁数月亮，不数星星

买黑马股的人有点像赌石：买块不起眼的石头，期待能开出好玉来。

市场低迷时，周期性成长股是最值得关注的，因为它们的估值会因其周期性而被恐慌性杀跌，但业绩增长却能因其成长性而跨越周期。

数月亮的行业一般门槛高，参与竞争的企业少，所以竞争有序，坐地收钱，旱涝保收；数星星的行业门槛低，谁都能进来，竞争激烈，经济好时担心成本上升，经济差时担心需求下降，好日子总是不长久。

最好也最容易研究的竞争格局是“月朗星稀”，就是一家独大，其他竞争对手都不成气候。

稍差一些的竞争格局是“一超多强”，彼此之间虽然有竞争，但老大的优势还是很明显，例如工程机械、客车以及某些汽车零配件，

再次一些的竞争格局则是“两分天下”和“三足鼎立”。

最差的竞争格局就是“百花齐放”“百舸争流”的高度竞争行业。

“数月亮”的行业还有一个不太好听的名字：寡头垄断行业。

行业是细分子行业的概念。有些大行业内貌似竞争者多如繁星，但是在细分子行业的竞争格局中已经实现了“三分天下”甚至“一超多强”。

我们说的竞争是区域市场的概念，有的行业从全国的范围看好像市场挺分散，但是在某个特定的区域，市场已经形成了寡头垄断。

投资收益与智商高低无关。

*四个原则：*

* 第一个原则是，便宜是硬道理。
* 第二个原则是，定价权是核心竞争力。
+
好公司跟坏公司的一个区别在于是否拥有定价权。
+
* 第三个原则是，胜而后求战，不要战而后求胜。
* 第四个原则是，人弃我取，逆向投资。

研究股票时我通常会先从行业入手，总结行业的规律和特性，重视行业格局，因为行业格局往往决定结局。

好行业如果格局分散，大家都赚不到钱；差行业如果集中度较高，也有可能赚钱。

我们要关注行业格局的演化，思考哪些行业是有“月亮”的，哪些行业正在形成“月亮”，哪些行业永远都是“繁星满空”。

这其中的关键是先发优势。

另一个关键是规模优势。

有规模优势的行业就容易产生规模效应。

我经常问研究员一句话：“这个行业是越大越强还是越大越难？”

行业格局本身并没有直接的意义，重要的是格局背后的定价权，那是舍我其谁的不可替代性带来的定价权，这才是区分赚钱不辛苦和辛苦不赚钱的分水岭。

如果出现跨界的降维打击，现有天空里的“月亮”可能就被掩盖了，就像天空中原有一个月亮，突然又闯入一个太阳，那月亮的光就看不见了。

=== 06　经验就像旧衣服

格林布拉特认为，选股有两个最好的指标，一个是资本回报率，另一个是 EV/ EBIT（ EV是指企业价值， Enterprise Value的缩写，等于股票市值和长期净负债之和； EBIT即息税前利润）。

企业估值倍数则适用于制造业和各种周期性行业，因为这些行业的利润波动大，市盈率在亏损或者微利时没有意义，用市净率、市销率则难以及时反映企业的经营状况，此时使用企业估值倍数常有事半功倍之效。

价值投资的原则是放之四海而皆准的，然而，具体到分析方法和分析指标，一定要按照各国国情和各个行业的具体情况因地制宜地变化。

只要认真思考不同投资者投资的国别、行业的不同，以及投资风格、期限、规模等的不同，就会发觉每个成功者在自己特定的投资背景下的投资逻辑都是经得起推敲的。

=== 投资随想录

其实，在市场的底部区域，便宜的好公司俯拾皆是，只可惜此时往往有钱的没胆了，有胆的没钱了。
