---
title: "《远见》之读书笔记"
date: 2020-08-14T20:58:23+08:00
draft: false
tags: ["读书","笔记"]
categories: ["方法论","个人成长"]
thumbnail: "images/books-on-book-day/the-long-view.jpg"
weight: 1
---




最近向一个朋友了解一家公司情况时，聊到职业发展的问题。就随手推荐了《远见：如何规划职业生涯3大阶段》这本书。正好利用这个机会，把以前的读书摘要发布出来。

这本书，D瓜哥在 https://www.diguage.com/post/goodbye-2019-hello-2020/#the-long-view[告别 2019，迎接 2020：《远见》] 中也提到过。这里把当时写的读书笔记直接拷贝过来：

本书讲人生的职业生涯分为三个阶段：

第一阶段是强势开局的时候。你在职业上的努力必须着重于为前方的漫长道路挖掘和装备自己。你的学习曲线要比职位、职称更加重要。在这一阶段，要为职业生涯打好基础并建立起良好的早期习惯。

第二阶段是聚焦长板的时候。该阶段的首要目标是寻找自己的甜蜜区，即你所擅长的、所热爱的和这个世界所需要的这三者之间的交集。这个时候你要展现自我，让自己鹤立鸡群，想方设法平稳地走在那条收获最大的职场路径上。你要专注于自己的长板，且大可忽略自己的短板。

第三阶段致力于实现持续的影响力，以及寻找一条可以稳定延续到60多岁甚至70多岁的新的可持续职业道路。你要在第三阶段完成三个关键任务：完成继任计划、保持关联性，以及为自己点燃一团新的职业之火。


用一句话来总结：第一阶段：加添燃料，强势开局； 第二阶段：聚焦长板，达到高点； 第三阶段：优化长尾，持续发挥影响力。

三大职场燃料来源：可迁移技能、有意义的经验和持久的关系。

5个数字，树立正确的职场思维

. 职业生涯的长度：用62减去你目前的年龄。
. 精通一项技能所需的时间：要花多少小时才能在某一方面达到“精通”？
. 40岁之后能赚到的个人财富百分比：在40岁之后，你赚到的钱会占你一生个人财富的百分之多少？大部分人的估计是60%。
. 社交货币：你有多少社交网络好友？
. 职场支持者的人数：你认为能在“职业生涯的天堂”里遇到多少人，也就是说有多少人能对你的职业生涯和人生带来真正的变化？

*这本书强烈推荐给对未来职业有追求的小伙伴！*

好戏开始，下面👇是读书摘要：

---
// 
---


== PART 1　远见思维与工具箱

=== 远见思维：多行动，少忧虑

1．职业生涯的持续时间长得惊人，包括了三个截然不同的阶段。职业生涯的持续时间比人们想象的长得多，至少有45年之久，而且未来很可能会进一步延长。对大部分人而言，40岁之后的工作年数要比之前的更多。职业生涯由三个主要阶段组成，分别持续大约15年时间。这三个阶段之间紧密关联，你在一个阶段的所作所为既可能为接下来的阶段创造机会，也可能带来恶果。你会在第2章中详细了解这些职业阶段。

第一阶段是强势开局的时候。你在职业上的努力必须着重于为前方的漫长道路挖掘和装备自己。你的学习曲线要比职位、职称更加重要。在这一阶段，要为职业生涯打好基础并建立起良好的早期习惯。在第8章，我们会深入探讨第一阶段，即通过实践课程学习如何踏入职场、赢在起跑线上。

第二阶段是聚焦长板的时候。该阶段的首要目标是寻找自己的甜蜜区，即你所擅长的、所热爱的和这个世界所需要的这三者之间的交集。这个时候你要展现自我，让自己鹤立鸡群，想方设法平稳地走在那条收获最大的职场路径上。你要专注于自己的长板，且大可忽略自己的短板。要想了解第二阶段的更多策略和案例，请翻阅第9章。

第三阶段致力于实现持续的影响力，以及寻找一条可以稳定延续到60多岁甚至70多岁的新的可持续职业道路。你要在第三阶段完成三个关键任务：完成继任计划、保持关联性，以及为自己点燃一团新的职业之火。

2．职场燃料很重要，因为职业生涯的基础决定结果。为了推动自己走完这段漫长的旅程，你需要大量的职场燃料。这种燃料有三个主要来源：可迁移技能、有意义的经验和持久的关系。随着全球的就业市场不断以不可预测的方式转变，如果没有这样的职场燃料，你就有可能变得不堪一击。职场燃料对于整个职业生涯的各个时期都至关重要。在第一阶段，你需要积累它；在第二阶段，你需要利用它；而在第三阶段，你需要更新和维护它。第3章将会让你进一步了解不同形式的职场燃料。

2．职场燃料很重要，因为职业生涯的基础决定结果。为了推动自己走完这段漫长的旅程，你需要大量的职场燃料。这种燃料有三个主要来源：可迁移技能、有意义的经验和持久的关系。随着全球的就业市场不断以不可预测的方式转变，如果没有这样的职场燃料，你就有可能变得不堪一击。职场燃料对于整个职业生涯的各个时期都至关重要。在第一阶段，你需要积累它；在第二阶段，你需要利用它；而在第三阶段，你需要更新和维护它。第3章将会让你进一步了解不同形式的职场燃料。

3．职业生涯需要通过对时间的巧妙投资来构建。职场燃料的可持续供应需要耐心和坚持。有人之所以能成为精通某一方面的专家或者“大师”，不仅是因为有天赋，而且是因为数千小时的学习、体验和实践。你在工作和生活中如何投资时间对你的成功和幸福有深远的影响。

4．职业生涯并不是以线性或者可预测的方式发展的。你必须时刻保持探索和学习的状态。职业机遇会变化，你的人生目标也会变化。当你遇到了新的路径和机会时，要保持冷静，有策略地思考。时刻准备好迎接无法避免的变化，并让自己的职业策略随机应变。成功的职业生涯既需要自我的规划，也需要良好的运气。自我的规划之所以必不可少，是因为它能让你抓住机遇。

5．职业生涯远不止于一份工作，而是生活的一大部分。这就是为什么你需要一个职业规划的框架的原因，它不仅可以用来甄选工作，而且是一种让职业生涯融入更广阔的人生追求里的整体方法，那些人生追求包括你的亲子关系、跨国工作、未来发展以及终极幸福。你欠自己一份职业策略和职业规划，而且制订它们的人选是毋庸置疑的。在这星球上的70亿人中，只有一个人能够陪伴你走完整个职业生涯，那就是你自己。

1．学习职场数学，树立正确的长期思维方式。第4章有一些简单但意义深远的问题，能帮助你认识职业规划的整体图景。

2．盘点职场清单，梳理你最有用处的技能、经验和关系。作为这份清单的一部分，你需要评估目前所处的职业生涯阶段，并描绘出职业生态系统。职业生态系统由对你获得的职业生涯成功至关重要的因素构成，包括你的联系人、专家团、同事和支持者。树立职业生涯目标，并根据以下4大黄金问题来得出年度职业价值评估报告：在接下来的一年里，你最大的追求是学习新东西、获得影响力、体验乐趣，还是收获奖励？具体内容请阅读第5章。

3．进行“100小时测试”并完成一份“个人时间档案”，从而了解你目前的时间投资状况。你是否将足够多的时间投入到让你变得最成功和快乐的事情上了呢？具体内容请阅读第6章。

4．在尝试建立新的职场路径或者在多个选项中抉择时，运用“职场路径向导”（Career Path Navigator）。具体内容请阅读第7章。

我如何避免被机器取代？ 我能在哪里以什么方式找到工作？ 未来我将如何分配时间？ 我会把钱花光吗？ 工作如何能让我更幸福？

=== 三大阶段，聚焦 45 年执业生涯

第一阶段：加添燃料，强势开局； 第二阶段：聚焦长板，达到高点； 第三阶段：优化长尾，持续发挥影响力。

职业生涯前15年的唯一目标就是为接下来的两个阶段打好基础。第一阶段不仅要有耐心，而且要不断行动，为之后收获果实播下种子。这是初出茅庐的时候，是找到自己的长板和热情所在的时候，是树立良好工作习惯的时候。最重要的是，这是储存职场燃料的时候。很多人都没有花足够多的时间尽早建立起自己的技能、经验和关系，因此在本该变得最有趣和回报最大的职业生涯的中间阶段就丧失了动力。

第一阶段是探索和弥补自身短板的时候。如果你是个糟糕的演讲者，那就去参加相关的培训课程。如果你对待团队成员过于强势或弱势，那就去参加领导力培训。学习要比纯粹的成功更重要。有时跌倒并不可怕，只要你能吸取教训，并将这些经验加以利用就行。

第二阶段是在你的长板、你的爱好以及这个世界的需求之间寻找交集的时候。第二阶段可能是职业生涯中段的15年，它是确认甜蜜区、确实更高追求、投资职场燃料以拓展长板，以及想方设法脱颖而出的时候。

着眼于核心长板，突破自我，更进一步吧。当你进入第二阶段时，补足短板已经难上加难了。更好的办法常常是专注于自己的长板，与能够帮助你、弥补你短板的人为伴。没有哪个卓越领袖可以面面俱到。如果你善于制订战略，对未来具有洞察力，那就可能需要找一个行动派专家帮忙。如果你善于执行，那就可能需要在团队中加入一个更有创造力和洞察力的人。坦率地承认自己的短板，针对它们招募盟友，你就可以把大多数时间放在核心长板上了。

传统意义上，职业生涯最后几年的标志就是明显的衰退（退休日）或者随波逐流。但在我看来，职业生涯的第三个阶段却可能异乎寻常地充实和持久。不过这需要恰当的思维方式、预期与准备。第三阶段的主要目的是确定接班人，即给继任计划画上完美的句号，从执行或领导的角色转变成顾问或辅助的角色。此时，学生变成了老师，学员变成了导师，领导变成了有价值的辅助者。

要想在第三阶段保持影响力，你就必须保有活力和关联性。人们看重历史，但前提条件是它对现在的状况和挑战有所借鉴。如果你连大致了解现状并保持关联性都做不到的话，就别妄想别人会听你的了，更别提雇用你了。保持关联性是你在第三阶段的工作之一。

=== 储备三大职场燃料

你的领导力是由你的学习意愿助燃前行的。

作为首席执行官和职业咨询师，我经常会看到一个现象：人们低估了职业生涯这段旅程的长度，中途就把燃料耗尽了。许多人关注的是职业生涯的表相：头衔、晋升、办公环境、薪水和奖励。这些可以算是职业生涯的重要里程碑，但并不是尾声。如果说读了这本书你需要记住什么的话，那就是真正成功的可持续职业生涯是靠职场燃料推动的。聪明的职业策略应该是，在整个职业生涯中积累职场燃料并不断更新，同时精明地消费它们。

解决问题的能力：从某种程度上说，世界上任何一份工作都是为了解决某个问题而存在的。你能够分析问题并制订解决方案吗？当你面对一项挑战和一张白纸时，你是否有一两套能解决问题的可靠方法呢？职业生涯的早期，我有幸在宝洁工作过。他们为我掌握解决问题的基本方法和原理打下了坚实的基础，这让我在整个职场生活中都受益匪浅。在奥美的培训和与客户的合作经验中，我又学到了其他东西。

说服式沟通技巧：无论你最后进入哪个行业，说服力都是一种受用一生的关键技能。发明家和创意工作者需要它来推销自己的点子，医生需要它让别人信任自己的诊断，商人需要它来销售自己的产品和服务，社区志愿者和社会活动家需要它来为自己的使命赢得支持者，音乐家和画家需要它来获得工作和招揽粉丝。不管你的交流对象是客户、同事、朋友还是陌生人，能将自己的观点以清晰、简洁的方式呈现出来都是一种基本技能。有的人觉得说服力是一种肤浅或低劣的伎俩。试着改观吧。说服的风格没有定式，从强硬、张扬的步步紧逼到冷静、可信的循循善诱，不一而足。苏珊·凯恩（Susan

说服式沟通技巧：无论你最后进入哪个行业，说服力都是一种受用一生的关键技能。发明家和创意工作者需要它来推销自己的点子，医生需要它让别人信任自己的诊断，商人需要它来销售自己的产品和服务，社区志愿者和社会活动家需要它来为自己的使命赢得支持者，音乐家和画家需要它来获得工作和招揽粉丝。不管你的交流对象是客户、同事、朋友还是陌生人，能将自己的观点以清晰、简洁的方式呈现出来都是一种基本技能。有的人觉得说服力是一种肤浅或低劣的伎俩。试着改观吧。说服的风格没有定式，从强硬、张扬的步步紧逼到冷静、可信的循循善诱，不一而足。苏珊·凯恩（Susan

Cain）在她的著作《内向性格的竞争力》（Quiet）中就阐释了内向者的潜力。无论你天生外向还是内向，都可以找到自己的风格，但前提是你必须学习如何说服别人。从我的个人经验来看，那些无法说服别人接受他们想法的人在职业生涯中都会受挫、贬值。

在测试讲故事的能力时，你会发现一件事：简单制胜。很多人，尤其是在他们初入职场时，会认为行业术语、高深辞藻和简称能显得自己更聪明。其实恰恰相反，行业术语和高深辞藻并不能赢得听众，反而会失去他们。你应该使用人们听得懂且能戳中他们痛点的文字和形象。有的时候，如果我要解决一个复杂的问题，就会做一个名为“给妈妈写信”的练习。我会真的起草一封给妈妈的信，解释眼前的问题和我想采取的行动。由于我妈妈未曾涉足过我的行业，所以这一练习就会迫使我使用简单明了的语言，从而让关键点呈现得尤为清晰。下次你遇到什么棘手的挑战时，也可以试试“给妈妈写信”。

在测试讲故事的能力时，你会发现一件事：简单制胜。很多人，尤其是在他们初入职场时，会认为行业术语、高深辞藻和简称能显得自己更聪明。其实恰恰相反，行业术语和高深辞藻并不能赢得听众，反而会失去他们。你应该使用人们听得懂且能戳中他们痛点的文字和形象。有的时候，如果我要解决一个复杂的问题，就会做一个名为“给妈妈写信”的练习。我会真的起草一封给妈妈的信，解释眼前的问题和我想采取的行动。由于我妈妈未曾涉足过我的行业，所以这一练习就会迫使我使用简单明了的语言，从而让关键点呈现得尤为清晰。下次你遇到什么棘手的挑战时，也可以试试“给妈妈写信”。

在测试讲故事的能力时，你会发现一件事：简单制胜。很多人，尤其是在他们初入职场时，会认为行业术语、高深辞藻和简称能显得自己更聪明。其实恰恰相反，行业术语和高深辞藻并不能赢得听众，反而会失去他们。你应该使用人们听得懂且能戳中他们痛点的文字和形象。有的时候，如果我要解决一个复杂的问题，就会做一个名为“给妈妈写信”的练习。我会真的起草一封给妈妈的信，解释眼前的问题和我想采取的行动。由于我妈妈未曾涉足过我的行业，所以这一练习就会迫使我使用简单明了的语言，从而让关键点呈现得尤为清晰。下次你遇到什么棘手的挑战时，也可以试试“给妈妈写信”。

说服力并不会只来自被大声表达的观点。虽然这么做或许一时能够奏效，但并不是长久之计。说服力的一部分来自令人叹服的事实，它能让人们真正有理由相信你。但在这个信息无处不在的世界里存在太多的选择和半真半假的故事，可靠的信息来源却少之又少。当与公司里年轻的专业人员合作时，我总是鼓励他们给每一个关键点标记脚注和信息来源。这是一种到了今天仍行之有效的老方法。当你谈到自己如何想方设法找到可靠的信息来源并加以记录时，就会传达给听众一个信号：你做了充分的准备，你的观点具备可信度。

说服力并不会只来自被大声表达的观点。虽然这么做或许一时能够奏效，但并不是长久之计。说服力的一部分来自令人叹服的事实，它能让人们真正有理由相信你。但在这个信息无处不在的世界里存在太多的选择和半真半假的故事，可靠的信息来源却少之又少。当与公司里年轻的专业人员合作时，我总是鼓励他们给每一个关键点标记脚注和信息来源。这是一种到了今天仍行之有效的老方法。当你谈到自己如何想方设法找到可靠的信息来源并加以记录时，就会传达给听众一个信号：你做了充分的准备，你的观点具备可信度。

Selling）的研究论文。我们已了解到，尽管有一些幸运儿是“天生的销售员”，但对大部分人而言，这种技能必须被后天开发出来。毫不脸红地说，我在离开宝洁时非常擅长用短短两页的建议书来表达自己的观点，因为这是宝洁偏好的沟通方式。但是在离开宝洁之后，我发现自己的公开演讲能力非常糟糕。每当我试着跟4个以上的人交谈时，就会从头到脚感到不舒服。如果不能解决这个问题，我在这个职位上就相当于一个废人。于是，我参加了公司的一些培训，努力进行实战演练。我尽量每周都至少做一次公开演讲，哪怕是上班的时候对一群同事宣布今天是某人的生日。最后，在一大群人面前和各种讨论会上，我也能泰然处之了。现在，只要我开口了，你就再也阻止不了我了。但我依然在不断实践和演练，每次演讲之前也依然会感到紧张。对于正式的演讲，我会至少花费5个小时去准备台上的20分钟。如果你无法确保自己能在面对面沟通、书面表达与在台上和镜头前发言时做到说服式沟通，那就不如将它当成一项基本的职业挑战，从现在开始就投入时间。

完成任务的能力：执行并完成任务的能力虽然再基础不过，但对于漫长的职业生涯具有巨大的价值。尽管每个人都具备一定的执行力，但只有那些能不畏艰难、持续产出的人才能真正脱颖而出。你能保证自己永远不会虎头蛇尾吗？你是否已学会如何不畏眼前的干扰和障碍，披荆斩棘实现终极目标？你的同事是将难度越来越高的项目交付给你，还是给别人呢？如果你能完成一次任务，那只能算是当了一次英雄。但如果你能持续完成任务，这就是一项强大的受用一生的职业技能。你可以在自己公司里寻找那些能不断完成任务的达人，他们是你最好的老师。执行，学习，如此往复。

完成任务的能力：执行并完成任务的能力虽然再基础不过，但对于漫长的职业生涯具有巨大的价值。尽管每个人都具备一定的执行力，但只有那些能不畏艰难、持续产出的人才能真正脱颖而出。你能保证自己永远不会虎头蛇尾吗？你是否已学会如何不畏眼前的干扰和障碍，披荆斩棘实现终极目标？你的同事是将难度越来越高的项目交付给你，还是给别人呢？如果你能完成一次任务，那只能算是当了一次英雄。但如果你能持续完成任务，这就是一项强大的受用一生的职业技能。你可以在自己公司里寻找那些能不断完成任务的达人，他们是你最好的老师。执行，学习，如此往复。

“人才引力”：有一种说法是，拥有最优秀人才的公司通常都能成功。我同意这个说法。与此对应的还有一条真理：有能力吸引和调动尖端人才的个人领袖通常都能成功。将优秀的人才招揽到身边能让你把工作做得更好，并扩大影响力。这个能力是区分优秀与顶尖的因素之一。“人才引力”不仅能让人在个人业务上表现出色，而且能培养和发展下一代明星人才，并将新鲜血液吸引到组织里。

“人才引力”：有一种说法是，拥有最优秀人才的公司通常都能成功。我同意这个说法。与此对应的还有一条真理：有能力吸引和调动尖端人才的个人领袖通常都能成功。将优秀的人才招揽到身边能让你把工作做得更好，并扩大影响力。这个能力是区分优秀与顶尖的因素之一。“人才引力”不仅能让人在个人业务上表现出色，而且能培养和发展下一代明星人才，并将新鲜血液吸引到组织里。

要培养“人才引力”，首先要有正确的思维方式，即认识到，没有人需要为你工作，必须是他们想要为你工作。我将其称为“eBay因素”（eBay

我鼓励年轻的领导者在加入一个团队几年后评估一下自己的“人才账户”。你们可以审视自己的每一次关键时刻，试着评定自己的行为对“人才账户”起到了增益还是衰减的效果。例如，当初雇用第一位助理时，做的选择是否合适？那个人在公司里是表现出色、持续进步，还是激情退却、原地踏步？在面临艰难的选择，决定如何分配稀有的晋升或加薪机会时，你们有没有挑中那匹千里马？你们是青睐于有能力、有潜力的候选人，还是被引向了“会哭的孩子”？

帮助和求助的能力：在畅销书《沃顿商学院最受欢迎的成功课》（ Give and Take）中，亚当·格兰特用令人信服的证据说明，成为一个成功的“付出者”（Giver）能让你在生意和生活中都更有效率。虽然许多人觉得这违背常理，但是格兰特提供了足以支撑这一观点的研究和案例。格兰特观察了三种社交风格，将它们与工作业绩和幸福指标关联起来。“获取”是只索取不付出，“互利”是在付出的同时期望得到某种回报，而“付出”是无条件地给予，对收获回报并没有太大的期望。付出者是净输出者，在利他性、责任心、社会正义和同情心这几点上比较突出。据格兰特所说，成功的付出者就是付出超过获取的人，跻身最杰出和最幸福行列的机会会比别人大得多。

Take）中，亚当·格兰特用令人信服的证据说明，成为一个成功的“付出者”（Giver）能让你在生意和生活中都更有效率。虽然许多人觉得这违背常理，但是格兰特提供了足以支撑这一观点的研究和案例。格兰特观察了三种社交风格，将它们与工作业绩和幸福指标关联起来。“获取”是只索取不付出，“互利”是在付出的同时期望得到某种回报，而“付出”是无条件地给予，对收获回报并没有太大的期望。付出者是净输出者，在利他性、责任心、社会正义和同情心这几点上比较突出。据格兰特所说，成功的付出者就是付出超过获取的人，跻身最杰出和最幸福行列的机会会比别人大得多。

我也赞成格兰特的观点，效率最高的管理人员有能力通过某种方式的付出来扩大自己的影响力，同时让他人尽可能受益。比较自私的“获取”风格是很诱人的，而且常常能在一段时间内奏效。但是正如格兰特所观察到的，也是我所看到的，随着这个世界变得越来越透明，职业生涯变得越来越长，越来越多的获取者将被曝光，而付出者将会获得更高的成就。就我个人经验而言，人们会朝着他们信任的领导者靠拢。而“付出”的行为就是一种建立信任的强有力的方法。学习如何寻求帮助和如何提供帮助，会成为职场持久战中一项强大的可迁移技能，而且后者是最重要的。

情商（EQ）：在工作中，我总是在寻找情商起作用的线索。情商是你理解和连接他人情绪状态的能力。例如，通过阅读某人的肢体语言发现对方的不适或愤怒，或者知道如何解读周围人的社交线索、情绪和非语言的信号。丹尼尔·戈尔曼（Daniel

情商（EQ）：在工作中，我总是在寻找情商起作用的线索。情商是你理解和连接他人情绪状态的能力。例如，通过阅读某人的肢体语言发现对方的不适或愤怒，或者知道如何解读周围人的社交线索、情绪和非语言的信号。丹尼尔·戈尔曼（Daniel Goleman）是情商领域的先驱者，在他的著作《情商3》（Working with Emotional Intelligence）中，戈尔曼指出，影响业绩和优秀程度最重要的因素就是情商。通过与世界各地的商业领袖的接触以及对500多个组织的研究，戈尔曼得出了一个惊人的结论：在每个领域要想成为业绩精英，情商的重要性比智商或专业技能高一倍。对领导者而言，区分精英与普通人的标准几乎90%都在于情商。

Intelligence）中，戈尔曼指出，影响业绩和优秀程度最重要的因素就是情商。通过与世界各地的商业领袖的接触以及对500多个组织的研究，戈尔曼得出了一个惊人的结论：在每个领域要想成为业绩精英，情商的重要性比智商或专业技能高一倍。对领导者而言，区分精英与普通人的标准几乎90%都在于情商。

培养情商是个很实际的问题，但也会为具备职业生涯思维的人提供一个切实的机会。有一个名叫雷蒙德（Raymond）的年轻人曾找过我，他当时刚刚步入职场，在一家领先的国际咨询公司担任商业分析师。他是纳米科学领域的高才生，之前就做过一些与科学和分析相关的实习工作。他向我提了一个很好的问题。

虽然我并不能完全回答他的问题，但还是给雷蒙德提供了一些实用性建议。我鼓励他将培养情商设立为一项为期两年的个人发展任务。我确信这会帮助他在这个领域的高智商人才中脱颖而出，并增加长期成功的机会。我向他推荐了一些这方面的好书，其中包括丹尼尔·戈尔曼的《情商3》与布拉德伯利（Bradberry）和格里夫斯（Greaves）的《成功EQ密码》（Emotional Intelligence 2.0）。但是对雷蒙德而言，看书并不是难事，关键是他必须创造实践经验才能发现和磨炼情商技能。他应当找机会获取公司和行业里的团队领导经验，他需要主动听取同事对其情绪领导力的反馈。这样，他就会发现，重要的不是他意图发出什么样的情绪信号，而是他的听众实际收到了什么样的信号。他应该密切关注周围那些感性的人，无论他们是否善于管理业务。我鼓励雷蒙德留意公司里的领导者在人际交往中的言谈举止，分辨其中的优劣。我让他尽量多发表一些公开演讲，因为亲眼看到现场听众的反应是一种很有价值的经验。他应该继续到家乡以外的地方去旅行，离开自己的舒适圈。如果他迫切想要有所进步，就应该报名参加即兴表演或戏剧表演的课程。哪怕这会让他感到很不适应，但没有什么能比这更快推动他去理解情绪并了解如何应对情绪和掌控情绪了。虽然培养情商可能要付出好几年的努力，但这是完全值得的。

1．如何与别人进行眼神交流和握手。我有一个经营房地产开发公司的朋友，他总是跟我谈论自己在大学时期养成的一个受用终身的技能。他说：“在我参加大学篮球队的最后一年，教练给我们上了最经典的一课。他说，我们在作为老运动员的这段时间以及整个人生中都会遇到许多重要的人。所以比起练习上篮或者控球，我们无时无刻不在练习如何与人打招呼、与别人进行眼神交流以及握手。这绝对是金玉良言。”在面试时，我惊讶于有的人要很努力才能直视我的眼睛，更糟糕的是有人甚至还在摆弄手机。

2．如何搜索信息。所有人都会用搜索引擎来寻找答案，但大部分人都做得不怎么样。他们不知道该如何核实搜索结果，不知道如何区分可信和虚假的信息来源，也不知道该如何用清晰、有说服力的方式呈现数据。我时不时会给大家分配一些小任务，去寻找某个特定的事实或信息来源。他们完成这些任务的方式千差万别，让人大开眼界。那些搜索能力强的人在他们的整个职业生涯中都将具备一定的优势。

3．如何呼吸。工作要求我们全神贯注，同时保持放松。早在职业生涯的初期，我参加过一些课程，学习了基础的呼吸和放松方式。如今，在大型演讲和会议之前，我依然会运用其中的一些技巧。这些简单的课程用处奇大，我当初要是再多学点儿就好了。

有意义的经验结合起来可以让你在职业生涯中既成为复合型人才，又很稳健。新的经验会让你离开舒适圈，建立新的职业技能。我倾向于拒绝那些在某一种可控的环境中可能才会有所发展的职位候选人，他们就像温室里的花朵。我通常会在候选人的背景中寻找多样性经验，确保他们拥有适应性和灵活度。

Sutherland）是行为改变方面的知名演讲人和思想领袖。罗里发现，在不同的环境中尝试不同的事情、试验不同的做事方法，这样能创造出更强的决策技能。如果我们一直用同一种方法做事，虽然会变得很有效率，但这种状态很脆弱。我们都知道，在遗传学中，一定程度的遗传多样性和基因突变会创造出更有活力的物种。也许一个拥有多样经验的“职场杂种”要比只能做同一件事的“职场纯种”更有优势。

Sutherland）是行为改变方面的知名演讲人和思想领袖。罗里发现，在不同的环境中尝试不同的事情、试验不同的做事方法，这样能创造出更强的决策技能。如果我们一直用同一种方法做事，虽然会变得很有效率，但这种状态很脆弱。我们都知道，在遗传学中，一定程度的遗传多样性和基因突变会创造出更有活力的物种。也许一个拥有多样经验的“职场杂种”要比只能做同一件事的“职场纯种”更有优势。

许多人问我，哪些职场路径拥有光明的前景。虽然可靠的选择成百上千，但有一条是我最喜欢的。我认为，如今身处商界的每个人都应该至少把职业生涯中的一个篇章放在电子商务上，即使只待几年时间。因为电子商务是个拥有美好远景的巨大产业。它的价值已经达到了数千亿美元，预计在接下来的10年内还将以每年超过15%的速度增长。由于电子商务涉及整个销售流程，从产品开发、供应链的运作、营销到客户服务等，所以它能教会你如何用总经理的头脑来思考。你将有机会接触到品牌塑造和用户体验等商业“软技能”，以及利润管理、数据分析等“硬技能”。最棒的是，电子商务的工作意味着你会每天收到即时销售的业绩单。电子商务中的一个职位就像是整个商业的缩影。这是一个多么神奇的个人学习和发展的加速器啊！如果我现在要开始自己的职业生涯，那么一定会把至少一个阶段放在电子商务上。

你的上司。这是你会感受到的第一号人际关系。没有人比你的直属上司对你更有影响力，不管这种影响力是好还是坏。你学到的是不是最好的工作方法和习惯？你是否在为一位业绩突出、值得尊敬的职场专业人员工作？你师从的是否为一位能传授你如何承担风险和其他可迁移技能的企业家？

你的客户。这些个人联系对任何职业而言都至关重要，在市场营销、销售或专业服务领域尤为突出。如果客户非常欣赏你，当你转移到别的角色、公司甚至行业时，他们都对你不离不弃，这就能说明很多问题。我在关于“人才引力”的章节中提到的“eBay因素”也适用于客户关系。我时常问奥美的领导者：“如果把你放在网上拍卖，会有哪些客户为你‘竞价’，点名要你呢？”

你的客户。这些个人联系对任何职业而言都至关重要，在市场营销、销售或专业服务领域尤为突出。如果客户非常欣赏你，当你转移到别的角色、公司甚至行业时，他们都对你不离不弃，这就能说明很多问题。我在关于“人才引力”的章节中提到的“eBay因素”也适用于客户关系。我时常问奥美的领导者：“如果把你放在网上拍卖，会有哪些客户为你‘竞价’，点名要你呢？”

商业伙伴。你是否正在与优秀的商业伙伴合作，例如能够在你的职业道路上起到支持和推动作用的顾问、合作机构、技术供应商或猎头？职业生涯后期的工作可能会令人恐惧、孤独。因为作为一名老将，一方面，你时常会觉得自己应当无所不知，另一方面，你有时还要与后来者竞争。如果你的身边伴有一系列有能力且支持你的伙伴，那是多棒的一件事情啊。

身边的人才。你是否在职业生涯早期遇见了顶尖的领导者和相关领域的专家？你应该问自己这样一个问题：“如果我自己创建公司，周围的人里，我愿意带上谁，以及他们是否会接受我的邀请？”

找到你的同类。在过去，许多职场人脉都是围绕着俱乐部建立起来的。如今，职场人脉越来越多地以社群为中心建立起来。盘点一下你的职场人脉，探索一下像“顶峰”（Summit）和“一万杯咖啡”（Ten

我们之所以需要对前文这三类职场燃料进行重点储备，原因有好几个。首先，它们令我们有了选择，即行为经济学家所说的“选择权”（optionality）。你不会希望自己建立的一系列技能只能适用于一家公司、一个行业或一座城市。具备深厚的基本技能将使我们能够胜任各种更强大的角色。不管我们是否选择追求这些目标，储备好这样的职场燃料会让我们免遭淘汰。其次，这几种职场燃料可以帮助我们获得自主力。每天都有行业和公司在经历起起落落，没有人能够准确地预言5年后的职场会是什么样子，更不用说10年或40年之后了。我们需要更灵活。社会学家查尔斯·汉迪（Charles Handy）提出了一项很好的假设性练习：想象一下，当你40岁时不得不永远告别自己的工作，以一己之力创立一家公司，你会怎么做？这是一个很好的测试自主力的练习。

=== 五个数字，树立正确的职场思维

我认识到能完成一场马拉松不仅是一项运动成就，而且是一种心理状态，一种一切皆有可能的心理状态。 约翰·汉茨（John Hanc）马拉松运动员兼作家

1．职业生涯的长度：用62减去你目前的年龄。算出的结果是你距离提前退休的年数。美国的一般退休年龄为62岁，而大多数西方职场的退休年龄都与之相仿或稍微大一点。(5)在过去的20年里，退休年龄在不断延后，而且这种趋势看样子还会持续下去。许多人之所以延迟退休，主要原因在于社会保障和退休金一直在逐步减少或延期发放。有的人还会主动选择延迟退休，因为他们在六七十岁时还享有良好的健康状况和有趣的工作。无论什么原因，大多数人都会在62岁左右退休，对此我们需要严阵以待。如果你现在正值20多岁的青春年华，那就还剩下将近35年的职业年限。许多人认为职业生涯到40岁就已经差不多结束了。实际上，就算到了40岁，你其实还没走完一半呢。大部分人都严重低估了职业生涯的长度。

2．精通一项技能所需的时间：要花多少小时才能在某一方面达到“精通”？在著作《异类》（Outliers）中，马尔科姆·格拉德威尔（Malcolm

仅有天赋是不够的，无论你拥有多高的智商或天赋，成功都需要花费超乎想象的时间进行高强度的练习。观察一下你感兴趣的行业，研究一下别人的发展轨迹，你会逐渐发现，获取关键的技能和经验必须花费一定的时间。虽然具体情况会随着行业而变化，也会因人而异，但是它们都会让你认识到为了前进必须付出。小野二郎被誉为全世界最好的寿司师傅之一，他要求手下的学徒在烹饪任何食物之前先花10年时间磨炼刀功。你对需要学习的技能了解得越多，就越能为职业生涯做最佳决策，从而将你获得长期成功的可能性最大化。

3．40岁之后能赚到的个人财富百分比：在40岁之后，你赚到的钱会占你一生个人财富的百分之多少？大部分人的估计是60%。年轻人倾向于估一个比较小的数字，例如40%。真正的答案其实是85%～90%。一个人的个人财富往往在65岁左右达到巅峰，而他们在40岁时的个人财富只有那个数字的10%～15%。(7)个人财富的积累绝大部分都发生在40岁之后，原因非常简单。第一，根据我们之前的发现，40岁之后的职业年限要比之前的更长，而且往往薪水也更高。第二，你可以享受到复利。第三，当不需要再付房贷和与孩子相关的费用之后，许多支出都会逐渐减少。尽管个人财富在生命的最后阶段的确会减少，尤其是在80岁后会增加医疗开支，但大多数人的财富积累是要到40岁、50岁甚至60岁才爆发出来的。大多数人完全没想到这一点。

4．社交货币：你有多少社交网络好友？思考这个问题的目的是，搞清楚根据手上的社交和商业关系，自己拥有多少“社交货币”。我听过的这个问题的答案一直都在数百人以上，有的时候能达到数千人，尤其是在年轻的人群当中。在Facebook上，每个活跃的成人用户的好友数量一般都在200个左右，而在18～25岁的人群中，这个数字为300。他们领英联系人的平均数量则是339。许多人觉得成功的职业生涯的关键是拥有尽可能多的社交联系人。不过，正如我们接下来讲的以及在关于职业生态系统的章节中会看到的，这一观点并不全面。

5．职场支持者的人数：你认为能在“职业生涯的天堂”里遇到多少人，也就是说有多少人能对你的职业生涯和人生带来真正的变化？当然了，这个问题并没有什么标准答案，不过我会用它来与上一个问题进行对比。就我个人经验而言，当人们在庆功宴和退休派对上回忆自己漫长的职业生涯时，常常会关注几个给他们的职业生涯留下重要印记的人。他们不会说：“我要谢谢领英上的1

职业生涯的长度：用62减去你目前的年龄。 精通一项技能所需的时间：到至少需要10 000小时的密集训练和练习。 40岁之后能赚到的个人财富百分比：85%～90%，因为大多数人的财富积累要蓄力到40岁、50岁甚至60岁才爆发出来。 社交货币：并不是越多越好。 职场支持者的人数：找到3～5个真正能称为导师的人。

=== 四大黄金问题，评估职业价值

没有人能孤军奋战，摇滚明星不行，职业运动员不行，软件业的亿万富翁不行，就连天才也不行。 马尔科姆·格拉德威尔《异类》

1．联系人是职业生态系统中未经改良的原料，包括我们的领英联系人、邮箱联系人、校友、同事等。定期衡量一下自己有多少职场关系吧。你最近建立过新的关系吗？你的数据库始终保持更新不过时吗？在你的人脉中，有没有哪个值得尊敬的人正在与你渐渐疏远呢？

在建立人脉关系网和真正的人际关系之间存在重要的区别。人脉关系网的构建者的心态是交易性的，他们在追求人际关系时只考虑其他人能为他们做什么。而人际关系的构建者会首先尝试帮助别人，他们不会有所保留。虽然他们心里清楚大部分好意都会得到回报，但是并不会精于算计。他们还会时刻维护自己的人际关系，而不是在需要的时候才想起来。

2．专家团处于职业生态系统中一个较高的层次。这些专家是拥有特殊的知识和权力、能帮助你取得工作和职业生涯成功的人。他们会为你的难题提供专业知识和最佳解决方案，这会让你变得更优秀、更聪明。尽管这样的团体是要招募和培养的，但是最好的方法并不只是请求帮助，而是提供帮助。你可以在周围的同事圈子里培养这样的团体，也可以将远在天边的朋友组织起来。

3．关键同事是在目前的公司里对你的发展拥有决定性影响力的5～10个人。排在榜首的是你的上司，这个角色在各种研究报告中都一直被列为影响职业成功和幸福的头号人物。你上司的上司也是个至关重要的影响者。在大多数情况下，如果你的直属上司提议给你加薪或升职，那就总是需要先得到他的上司的签字认可。所以，如果你上司的上司觉得你是个天才（或傻瓜），就会给你的职场路径带来很大的变化。某些同事和下属也可以成为关键同事圈的一员。当你在审视自己的职业生态系统时，应当在目前的组织中找到10多个这样的黄金人际关系，将他们列出来。诚实地问一下自己，他们如何看待你？他们会支持你迈出下一步吗？如果答案是否定的，那么你需要怎么做才能消除误解或赢取更好的人际关系呢？

4．支持者是在职业生涯中帮忙提建议、拥护你、激励你的导师和帮手。他们通常为数不多，大概不到5个人。这些就是你在“职业生涯的天堂”中会遇到的那一类人。对职业生涯而言，支持者就好比时速25公里的顺风，也仿佛推动我们前进的一只隐藏的仁慈之手。支持者会在背后说你的好话，将你推荐给别人。

蟋蟀文化公司（Cricket Media）的首席执行官卡佳·安德烈森（Katya Andresen）为我们定义了三类人生导师：明星，他们是成功的行为榜样，告诉我们如何成功；贤者，他们就像苏格拉底，并不为我们提供答案，而是教我们如何思考；策动者，他们激励我们，鞭策我们，偶尔迫使我们踏出关键的一步。

League）的顾问。阿尔瓦罗说：“你得确保自己的导师不仅拥有过去的智慧，而且能在你的过去、现在和未来提供助力。”

5．你自己。任何职业生态系统的核心都是你自己。许多人都觉得这是显而易见的，这一点儿都没错。你就是你自己的品牌经理。作为品牌经理，你的工作之一就是关注职业生态系统，确保它积极、活跃地发展。我认识一个千禧一代的后起之秀，她每年都会对影响自己职业生涯的人做一次“能量评审”。她发现周围有一些人，他们尽管是很好的私人朋友，心地善良，过去也帮过很多忙，但是现在似乎正在妨碍她、拖她的后腿。他们是第一个说“这不可能”或者“你根本就不该尝试”的人。所以她会尝试花更多的时间与生态系统中的其他人在一起，那些人会让她感觉更强大、更聪明、更有活力。

我是否正在学习和成长？ 我是否正在对某些人、现在的公司，乃至整个社会拥有影响力？ 我体验到乐趣了吗？ 我是否得到了适当的奖励，并创造了经济价值？

=== 一百小时测试，合理投资时间

时间是你的人生货币。它是你唯一拥有的货币，而且也只有你能决定如何消费它。 卡尔·桑德堡（Carl Sandburg）

=== 职场路径向导，做出正确的职业决策

如果你的价值观很明确，做决定就变得更简单了。 罗伊·迪士尼（Roy E. Disney） 做出有益决定的关键是尊重未来的自己。 A．J．雅各布斯（A.J. Jacobs）

这些技术上的对比并没有击中要害，你需要在更大的环境下权衡自己的选择。我之所以将职场路径向导放在关于工具的最后一节，是因为我认为你需要先打好其他基础。学习职场数学能帮你树立起正确的思维框架；思考职业生涯的三个主要阶段能提醒你当前在这漫长旅程中的位置；盘点一下职场清单，总结目前的职业生态系统，这会让你了解自己的技能和关系的状态；仔细审视你的时间档案能帮你弄清在职场和生活中可以做出什么样的平衡调整。做完这些，你就万事俱备，可以做出一些明智的决定了。

你的职业理想是什么，或者至少假设一个你可能想要达到的目标。 你目前手上有什么职场燃料？ 你需要什么职场燃料才能实现这个终极理想？

奥朗认为，长期成功的基础是快速的成长。大多数大学毕业的聪明人每年的成长速度为10%。这意味着他们的能力在毕业7年后差不多会提高一倍。大多数29岁的人的薪资是他们大学毕业后第一份工作的两倍，不是正好说明问题了吗？如果要成长得再快一点，你就需要一份满足以下条件的工作： 你周围都是比你聪明的人； 你有失败的机会； 公司有让你这样的人肩负重大责任的传统。

奥朗·霍夫曼还说：“当你有33%～66%的概率失败时，成长的速度也是最快的。要想精进，就得主动站在可能失败的立场上。有一个现象非常常见，那就是人们会选择一份百分之百会成功的工作，尤其是刚毕业的学生。尽管板上钉钉的成功一开始会让人感觉很棒，但并不能助人成长。你应该寻找一个能让你参加高失败风险项目的组织。

“假设你是一个有远大目标的人，想要持续不断地成长，那就一定要找机会晋升，并承担越来越重的责任。那些有相应的机制并且增长速度很快的公司是最有可能快速提拔你的。寻找一些与你背景相似又加入了该公司的人，看看是否有人被赋予了重大的职责。”

“我们总是会低估在未来才能兑现的好处，这种现象被称为‘时间贴现’（temporal discounting）。我们都不愿意用当前的痛苦，比如更辛苦的工作、更低的薪水、更低的声望等，来换取未来的某样东西，即使未来的好处其实更加丰厚。作为人类，我们本能地不相信未来的好处能够兑现，所以会在当前对它们打很大的折扣。”克里斯还在观察中发现了“损失厌恶”（loss

discounting）。我们都不愿意用当前的痛苦，比如更辛苦的工作、更低的薪水、更低的声望等，来换取未来的某样东西，即使未来的好处其实更加丰厚。作为人类，我们本能地不相信未来的好处能够兑现，所以会在当前对它们打很大的折扣。”克里斯还在观察中发现了“损失厌恶”（loss aversion）的效应：“人们对后果和风险看得比好的方面更加清楚。我们的美梦很模糊，但噩梦却很清晰。”

发现新机会是有益的，毫无意义的变化则是有害的。

== PART 2　三大职业生涯阶段

=== 第一阶段：加添燃料，强势开局

流浪者未必都迷茫。 J．R.R．托尔金（J.R.R. Tolkien）

有的人对自己想做的事情一清二楚，一走出校门就很快置身于令人满意的岗位上。他们是稀有的“独角兽”，但大部分人并不是。很少有人能确切地知道自己想要干什么，尤其是在刚刚起步的时候。虽然我刚开始做的是会计，但很快就爱上了市场营销，并把职业生涯的其余部分都投入这一领域的奋斗中。我的一个女儿在剑桥拿到了中世纪史的博士学位，现在却在伦敦的金融服务行业担任研究员。

亚当·格兰特在《沃顿商学院最受欢迎的成功课》中说：“如果人们对职业生涯早期的期望能更现实一些就好了。”整个第一阶段往往长达15年，是一个学习和探索的过程，充满了尝试和错误。这时并不是为了找到一份你每天都津津乐道的神话般的工作，而是要找出你擅长什么、不擅长什么、喜欢做什么，以及不喜欢做什么。第一阶段并不仅仅是被动地增长年龄和阅历，像一块牛排一样“更加入味”，而是一个高度活跃和有目的性的阶段。

亚当·格兰特在《沃顿商学院最受欢迎的成功课》中说：“如果人们对职业生涯早期的期望能更现实一些就好了。”整个第一阶段往往长达15年，是一个学习和探索的过程，充满了尝试和错误。这时并不是为了找到一份你每天都津津乐道的神话般的工作，而是要找出你擅长什么、不擅长什么、喜欢做什么，以及不喜欢做什么。第一阶段并不仅仅是被动地增长年龄和阅历，像一块牛排一样“更加入味”，而是一个高度活跃和有目的性的阶段。

司徒慕德爵士（Mark Moody—Stuart）说过：“职业生涯绝不是一条笔直上升的路线。我们常常需要为了前进而后退，为了变得更好而变得更坏，为了获得进步而投入资本。最好的旅途总是发生在迷路时。”第一阶段的策略很简单：步入职场、迎接新发现，并为前方的漫长旅程储备职场燃料。如果你在第一阶段结束时能做到这些，那样的状态就是理想的。不过，执行这一策略并不轻松，所以下面我们来介绍一点实用的方法。

1．利用在读的时间储备早期形式的职场燃料。尽管我不认为大学这几年能带你按部就班地走向预先设定好的职位，但是毫无疑问，你可以打下基础，为今后能做出成功的职业生涯决策而做好准备。

2．制订求职作战计划。你可以通过建立电子表格和数据库来帮助自己找到第一份工作。作战计划能让你目标明确，并保持活跃。首先，根据行业、位置、规模、公司知名度，以及朋友、家庭、就业辅导员等的推荐，列出一份可能对你感兴趣的10～20家公司的初始清单。接着开始与这张目标清单里的公司和行业中的个人建立联系。一拿到目标公司的联系人信息，你就应该整理归档，包括公司的网站、电子邮箱地址、领英档案和电话号码。记录下你对每家公司采取的行动，以及对方的回应或下一步动作。时刻记得职位申请的最后期限。

3．积极参与校园招聘。许多高校都会举办校园招聘会。我强烈建议大家尽量多地参与进去。你会遇到一些很难在宣传册或网站上找到的行业和公司。有的时候，了解一下那些你不想效力的公司和行业也是有利无害的。如果你喜欢哪家公司，那么可以尝试一对一地沟通一下，例如拿一张名片、记下一个电子邮箱地址，或者后续再咨询。好好利用校园招聘资源，虽然你不能光靠它们来找工作，当然你也可以选择这么做，但这是一个很好的培养基本技能的地方，可以让你预先演练好在外面那个“巨大而可怕”的世界中会遇到的问题。

4．高效地进行在线申请。通过网络搜索和分析研究，你会知道谁在招聘，以及他们提供的具体职位。不必多说，申请吧，但要注意最后期限。几乎所有的面试都是在网上申请之后安排的。将你的简历草稿给一位或多位信得过的顾问过目，比如身处这个公司或者至少这个行业的人。听取建议，一击制胜。不过，在线申请很容易给人挫败感，因为它具有匿名性，反馈率非常低。你可能在得到第一份全职工作之前已经递交过几十甚至上百份申请了。一定要坚持下去。在线申请是求职作战计划中无法避免且必不可少的一部分。对一些职位而言，这是唯一能入职的方法，你能做的就是提高申请的效率。聪明、完美地进行在线申请，然后继续你的旅程。

5．最重要的是，用好你的联系人。市场营销有一句金玉良言，同样也适用于求职，那就是有关系可以大幅提高你的反馈率，所以要多多运用你的联系人，比如导师、校友、朋友、父母、其他家庭成员、邻居等。你可以利用他们来帮助自己了解那些可选择的职位，磨炼自己与某些行业、岗位和公司的“契合度”，也可以利用他们为你打开机会的大门。

5．最重要的是，用好你的联系人。市场营销有一句金玉良言，同样也适用于求职，那就是有关系可以大幅提高你的反馈率，所以要多多运用你的联系人，比如导师、校友、朋友、父母、其他家庭成员、邻居等。你可以利用他们来帮助自己了解那些可选择的职位，磨炼自己与某些行业、岗位和公司的“契合度”，也可以利用他们为你打开机会的大门。

有一种极好的建立新关系的方法，那就是好好利用校友网络和领英这样的人才数据库。在校友目录里找找，有没有哪位校友会成员就职于你的目标公司。到领英上瞧瞧，有没有哪个在目标公司工作的人与你来自同一所学校。如果能找到你们之间的联系，那就快联络他们吧。你会惊讶地发现，人们其实很愿意聊聊他们的工作。现在，让我们从列清单开始。一封简洁而有个性的电子邮件会给你开个好头。

6．在与联系人见面之前，做些功课。在有维基百科和领英的世界里，如果连对与你对话的人和他们所在行业的基本信息都一无所知，就太说不过去了。每一次碰面都是一场面试，即使你觉得这只是闲聊。准备好一些问题，做好笔记，事后再写封感谢的电子邮件。你的联系人正在考虑是否交你这个朋友，所以让他们愉快地做出决定吧。你不仅要为面试准备答案，还要花同样多的时间准备一些有水平的问题。

在与别人的交谈中，我被问过一些很有意思的问题： 这个行业有什么特别之处？ 你喜欢或不喜欢这份工作的哪些方面？ 在你的公司取得成功需要哪类技能？ 你是怎么得到这份工作的？ 你们公司的企业文化是什么样的，与其他公司的有何不同？ 人们现在都是如何进入你这个行业的？（可能与过去有所不同。） 有什么挑战会让你彻夜难眠？ 你认为这个行业的引领者是谁？ 你知道你的公司有什么合适的职位空缺吗？（直接问，没关系。） 还有一个你每次都必须提出的万能问题： 你能不能再推荐一家公司或一个人，让我跟它或他聊一聊？

7．但是，找到第一份工作依然难于上青天！如果有人告诉你，他们在找工作的时候碰到了多么多么大的困难，那就不如把他们介绍给善意实业的比尔·福里斯特（Bill

善意实业的团队找到了所谓“基于长板的模型”（strengths—based model）的成功方法。他们总是从一开始就关注个体的长板、能力和技能。这样可以建立起一个最基本的起点：自信心。在比尔和琳达看来，这是成功的核心前提。经过充分的准备和培训，尝过一些微小的胜利的滋味后，自信心就能树立起来。接着，比尔和琳达会帮助求职者明确地认识到他们与工作之间的障碍，并系统地加以分析他们可以采取什么样的建设性行动来克服一些基本的困难，例如孩子无人照管、公共交通不便、语言技能不熟练、不擅长使用计算机和仪容问题。善意实业有一名患有自闭症的年轻客户，在大部分的工作中，他都很难取得成功。但是善意实业发现他精通并且热衷于辨识颜色，于是他就在一家服装零售公司找到了一份分拣和补货的工作。

我们都能从比尔、琳达以及善意实业团队的身上学到很多。琳达说：“在每一次成功的求职背后都有两个关键点：成功的意愿以及联系人与支持者组成的后援团。”为了提高成功的机会，善意实业会指引求职者到最肥沃的狩猎场上去。他们通过市场调研(10)寻找需求较高的工作领域，并向求职者指出这些道路。需求最高的工作并不总是那些最显眼或最出名的工作。琳达认为，对于她的求职者，有许多非学术性道路可供追求，例如电工、管道工和家庭护理。在你所选的领域中，需求最火的工作是什么呢？

最后，善意实业发现，微小的成功对于培养动力和信心能起到很大的作用，比如收到第一次面试邀请或考取一门新技能的证书。没有人能一下子就找到工作，大多数电子邮件都会石沉大海，面试也常常会被取消，职位空缺的时间会被延后甚至从此杳无音讯。

我在善意实业那些勇敢的求职者身上明白了一个道理：外面的世界困难重重，但是没有人有资格抱怨这一点，总有人的情况比你更艰难。勇敢参战，坚持执行计划，你一定能成功步入职场。

8．探索。即使你一脚步入了职场，探索之旅也并没有终止，而是刚刚开始。你需要弄明白自己擅长什么、热爱什么，以及这个世界需要什么。

Greene）忠告我们在职业生涯的头几年里要耐心和开放。初期的这些时间应该被投入到竞争力、经验和关系的建立上。格林观察后发现，每一次成功都必得先经历10次尝试和前9次的失败。通过不断试验，才能发现真正的热情、道路或目标。他强烈建议人们在职业生涯的早期多多关注眼前出现的机遇和自己的反应，即你关注什么、你把精力放在哪里、你听信谁的声音，以及你选择阅读谁的文字。

2015年7月，“未来巨星”网站被“潘多拉”音乐电台收购。谦逊而踏实的亚历克斯很快指出运气在他的成功中所起到的作用。“我们一路上碰到的各种困难让人望而生畏，”他摇着头说道，“如果你只是为了入选《福布斯》30岁以下富豪榜而创建自己的公司的话，这么做就不值得。如果你想要成为企业家赚大钱，就别走这条路。如果你发现了某样让你着迷、让你夜不能寐的东西，那么这就是你应该追求的一条路。”

Hoffman）和萨米尔·雷亚尼（SamirRayani）的智慧，还有他们的情感支持。他说：“他们作为联合创始人陪伴我面对这一切。他们是唯一了解我们若想要实现目标，会面临什么样的挑战和压力的人。”在我们的访谈中，亚历克斯引用了一句金玉良言：“白天严格遵循计划才能给夜晚带来开放的选择。”这句话提醒我们每个人，要给自己的生活保留一些发现新事物的运气。亚历克斯将运气列为成功的一个重要因素。但他并不是光靠运气找到音乐和数学的交集的，机会总是留给有准备的人。

相反，何不拿出一个高层领导或客户正在苦思冥想的具体问题，跟你的老板讨论讨论呢？把它当作一个为期两周的秘密任务，从各个角度研究一番。翻阅你手上的资料，在一份简短的5分钟展示中给出你的解答，将你的论点和假设凸显出来。然后跟老板商量一个合适的时间，用5分钟完成一场重磅表演。展现你的才华，仔细倾听观众的反馈，并反复这么做。只要每过几个月就做一次这样的讨论，你就会在越来越多的专题中成为值得信赖的咨询对象。这会为你的职业生涯带来新的价值。

另一项值得培养的早期习惯是高效沟通。不管我们身处什么样的角色和行业，我们沟通的方式最能决定我们在他人眼中的印象。利用职业生涯早期的每一个机会磨炼你的沟通技能，这不仅限于你说什么，而且包括你怎么说和在哪里说。

首先，话题是什么？我们的听众的注意力正在不同的电子邮件和会议之间快速切换，有一半的时间他们完全不知道我们到底在说什么，所以每一次你都要说得一清二楚。

其次，写下你的三个重点，加上用于佐证的事实和原因加强说服力。这意味着你既有观点，又有支撑它的证据。

最后，直白地说出你希望听众接下来怎么做。这样一来，你的沟通至少是有力和清楚的。这能让你领先于世界上80%左右的人。

要想真正地出类拔萃，你就得成为一个能把故事讲好的人。尽管并非所有人都有这样的天赋，但通过刻意练习，我们都有机会成为一个好的说书人。对我而言，讲好故事的关键是利用简单且有画面感的情景，以及引发他人的共鸣。我很喜欢收听播客和“飞蛾”网站（Moth）。我会看比尔·克林顿和史蒂夫·乔布斯这样的演讲、说服大师的视频，我也会对自己的演讲视频进行评估。学习、实践，然后消化。

最后，我想分享一下关于书面文字的一点想法。尽管这个世界已经数字化了，但书面文字依然保留着它优雅的一席之地。在电子邮件和文本信息的海洋里，想象一下一张你亲笔书写的小小纸片会给别人带来多大的冲击力。我现在依然会给别人定期发送明信片、手写的笔记或信件，因为这是表达真挚情感的最佳方法。在工作和生活中，有什么能比“恭喜”、“很高兴有你在”、“谢谢”、“对不起”和“节哀顺变”更能传达情感的呢？

第一阶段的最后一项技能是理解自身的价值，以及为自己的贡献争取公平的奖励。许多人在职业生涯的早期都对这些话题表现得很天真，准备也不充分。他们常常会从同事、家人或招聘人员那里收到不良的建议。

我的建议很简单。首先，判断报酬和获得的认可合不合适，看的是贡献，而不是资历。没有人会因为你入职了一段时间就欠你一次加薪或升职。珍妮弗在入职16个月后得到了加薪，跟你这周二入职时间就要满18个月了没有丝毫关系，问题在于你给公司带来的价值。搞清楚公司对你这个职位的期望是什么，尽可能完美地满足它。当你想要评估自己的绩效和报酬时，首先将你的贡献列出来，包括“硬”贡献和软指标。例如，你有没有为公司带来收益和新客户，或者帮忙节省了公司的开支？有没有证据表明你让公司的顾客更满意了？你有没有发明在将来某一天能提高利润的新产品、想法或流程？你做的事情是否能提高公司的声誉，如发表一篇文章、参加一场颇受好评的演讲活动、赢得一个奖项等，或者是否为人才库增加了一些重要的新生力量？尽可能多地关注产出，而不是行动。光是做你的本职工作只能让你维系目前的职位和薪酬。

找你的上司一对一地聊一聊，最好再找至少一名导师沟通一下。问问他们，你所关注的优先事项和目标是否正确，也就是说，它们是不是对于公司及其业务有真正价值的东西，而不是细枝末节的小项目。问问他们，你的表现跟同事比起来又如何，你还能再做些什么，需要什么才能走向下一步。

没过多久，戴夫就退了学，全心全意追求创业之梦，这让他的家人和朋友都大感震惊和困惑。“他们想知道我是不是疯了，”戴夫回忆道，而他当时已经准备好迎头而上，“生活不是线性的，它无法在教室里学会，而是要在实践中学。而最好的作品是在你不工作的时候诞生的。”戴夫的第一家公司是一家营销公司，专门帮助公司和政府完善针对千禧一代的市场营销策略。两年后，戴夫明知道只要在营销公司努力工作，就能过上优越的生活，但他更想要干出一番持久和真正有影响力的事业。就是在那个时候，他开始围绕着“一万杯咖啡”的想法，计划开一家新公司。

对戴夫而言，帮助年轻人一直都是他职场路径的主要脉络，也是一种让他获得了使命感的追求。“年轻人是未来。对公司而言，在接下来5年左右的时间里，将有超过50%的劳动力都是千禧一代。各大品牌在数字和社会化营销上耗费了数百万美元，而主宰其成败的就是千禧一代。全世界的政府正在迎来由年轻人决定投票结果的选举，”他解释说，“当你看到这一变化时，就会意识到让年轻人更好地分享想法、收获思想和踏出第一步是多么重要了。”

=== 第二阶段：锚定甜蜜区，聚焦长板

高效管理者的基础是他们的长板。 彼得·德鲁克（Peter Drucker）

如果说第一阶段是寻找你的甜蜜区，那么第二阶段就是锚定它。你要不断问自己这三个难题：我擅长什么？我爱好什么？这个世界需要什么？

在第一阶段，我们关注的是培养专业知识、积累可迁移技能，以及成为某些方面的咨询对象。在第二阶段则要创造真正的差异。杜克大学的教授兼作家多里·克拉克（Dorie

精通的秘方就是意愿和时间

格林补充说，创造精通技能的秘方就是意愿和时间。“我们都知道，当我们充满干劲时能钻研得多深。如果这个主题令我们感到兴奋，如果它能激起我们最深的好奇心，或者如果我们为了丰厚的利益而必须学习，那么我们就会投入明显更多的注意力。我们吸收的东西会沉淀下来。如果我们身在法国，需要学会他们的语言，或者突然爱上了一个不怎么会说英文的法国美女，那么我们在几个月内学会的东西就会比在4年的法语课程中学到的更多，而不管当时的法语课老师有多厉害。换句话说，我们的专注度决定了学习的深度。”

保持一直向前的动力，就能持续成功

托德的职业生涯一路高歌猛进。如今，除了运动教练的业务之外，他还在那些渴望提高业绩的创业公司里开展培训和投资活动。他不断钻研自己的技艺，尝试写书，在行业活动上演讲，让自己始终走在行业前端。他崇尚“技能冲刺法”，即以90天为一个循环，为提高某一项特定能力而进行周期性密集训练。这也反映出托德的成功哲学：这是一种持续改进的不间断过程；或者用他自己的话来说，是“梦想要大，但前进的步子要小”。只要你能保持一直向前的动力，就能持续成功，即使中间有些挫折也不碍事。“总有些事情会失败，”他说，“这是不可能彻底掩盖的。但是你可以决定的是，是否从中吸取教训。”

领导者必须飞得足够高，才能用战略的眼光俯瞰全局。任何高级管理人员都必须做到这一点，因为他是少数几个，甚至是唯一一个能看清全局的人。与此同时，能力强的领导者还需要有极度关注细节的能力，这样才能解决棘手的问题或谈下一笔生意。做到这两点的关键技巧就是学会像一架俯冲轰炸机一样，随时调整自己的巡航高度。

领导者必须飞得足够高，才能用战略的眼光俯瞰全局。任何高级管理人员都必须做到这一点，因为他是少数几个，甚至是唯一一个能看清全局的人。与此同时，能力强的领导者还需要有极度关注细节的能力，这样才能解决棘手的问题或谈下一笔生意。做到这两点的关键技巧就是学会像一架俯冲轰炸机一样，随时调整自己的巡航高度。

你要能在高空中飞行，分析战局形势，找出主要问题或机会；一旦发现目标，你就要具备追踪并粉碎目标的能力。遇到重大危机，例如一场矿难或安全漏洞时，首席执行官要能直击问题的核心，并在完成任务之前亲力亲为、参与其中。但是一旦问题解决，你就得适时地“飞回高空”。我们都见过那种始终高高在上的领导者，也见过另外一类似乎离地面只有几厘米、一直插手问题的领导者。不要一直做飞在高空的宇航员，也不要一直做飞在低空的扫地机。在第二阶段初出茅庐的领导者面临的最大挑战之一就是，调整领导风格，从命令与控制转变为影响与感召。你需要学习如何调整巡航高度，当一架俯冲轰炸机。

1．你的仪容、态度和举止正受到高度的关注和广泛的效仿。员工们会比过去更加仔细地观察你，寻找蛛丝马迹来判断自己的表现如何。从今天开始，无论你表现出快乐、压力、自信、愤恨、失望的情绪，还是处于危机中的状态，员工们都会察觉你发出的信号，并据此调节他们自己的态度和行为。所以，请仔细思考你想要传达的信号。

2．一旦你确定了某个愿景，就应该简洁地表达出来，并且不停地重复重复再重复。人们很容易过高地估计一个组织消化愿景和战斗口号的能力。你需要寻找一些简单明了的词语，表达出你希望组织向哪个基本方向前进。它们只要在方向上正确，并令人牢记于心就够了，不必完美无缺。你以后可以将“新闻”和变化融入长期的信念和愿景之中。每次遇到机会时都要重复这种想法：“这种情况体现了我们深层的信念，那就是X很重要。”你可能觉得已经做得够多了，但其实还不够。要知道，每年的员工流动率高达20%左右，他们为什么还要记得去年的事情呢？

3．早早决定让谁上船。每个领导者都需要一支小型核心团队，由那些能够高质量完成任务的亲密同事组成。选择这样一支团队往往是领导者最重要的任务。虽然你并不需要立刻为每个位子找到对的人，但还是得尽早决定让谁上你这条船。不要选择和你相似的人，寻找那些能够增强你的长板和弥补你短板的人，并一对一地去了解这些参与者和候选人。探究一下他们的目标、信仰和关注点，看看它们与你的目标、信仰和关注点是否契合。

4．每一个有意义的商业问题都是少数人在一间安静的小会议室里解决的。观点之间的对抗是有益的，但要确保它发生在恰当的讨论中。来回对骂的电子邮件要尽量避免。有争议的问题最好是在较小的团队中解决，而不要放到严肃的大型公开会议上讨论。即便你是老板，也要明确地表现出你对其他人观点的理解。用你的耳朵来领导大家，不要只靠嘴巴。理清问题的前因后果，用自己的信念加以评判，最后做出决定。

5．你要表现得像个被人信赖的解答者，而不是高高在上的老板。你的办公室装潢并不重要，重要的是你对组织的影响力。信念、诚信和公正会给你带来力量。让消息在组织中透明地传播，告诉大家好消息和坏消息，帮助他们正确看待这些信息对组织的影响。证明你会对这些事情全力以赴，证明你关心它们，不会撒手不管。

6．你并不是无所不知。没人会无所不知，征询他人的意见才是明智之举。无知并不可怕，只要你能发现这一点，并做出适当的决定就行了。你可以先在特定阶段做个决定，而不必一锤定音。

学习：我是否正在积累有助于成长的新的技能、经验和关系？ 影响力：我是否正在改变个人、公司，甚至整个社会？ 乐趣：我的职业总体上算不算我生活中正能量和乐趣的来源？ 奖励：我是否正在积累经济价值？

1．诚实和契合。顶级候选人会展现出强大的个人价值，并且较多地谈到这些价值与雇主的文化之间潜在的契合性。较差的候选人就不会太多地探究组织和他们自身之间的契合程度。

2．智力上的好奇和敏捷。顶尖的准首席执行官能够将各种问题综合、联系起来。他们在工作之外拥有有趣和丰富的生活。他们读书看报，深入行业核心，提的问题很有水平。较差的候选人对行业和具体的工作的研究都不够深。这会被视为不可原谅的怠慢和傲慢的表现。

3．提升业务业绩的历史记录。这一点向来很难判断。判断候选人过去的业绩需要综合考虑他先前身处的行业和历史状况。在某些职位上，仅仅是让业务稳定就是一项很不简单的成就了。而在一些快速发展的行业里，一般水平的增长反而是低于标准的。招聘人员需要剔除掉那些从前任那里接手的或因偶然因素产生的业绩，识别由候选人贡献的真正成果。最优秀的候选人能够清楚地阐述现实目标和实现目标的过程。提升首席执行官业绩的一项潜在因素就是“决心和自控力”。决心是不畏艰险专注于某一目标的能力，自控力指抵抗分心和诱惑的能力。拥有极强的决心和自控力的领导者总是能取得更好的成果。(15)

3．提升业务业绩的历史记录。这一点向来很难判断。判断候选人过去的业绩需要综合考虑他先前身处的行业和历史状况。在某些职位上，仅仅是让业务稳定就是一项很不简单的成就了。而在一些快速发展的行业里，一般水平的增长反而是低于标准的。招聘人员需要剔除掉那些从前任那里接手的或因偶然因素产生的业绩，识别由候选人贡献的真正成果。最优秀的候选人能够清楚地阐述现实目标和实现目标的过程。提升首席执行官业绩的一项潜在因素就是“决心和自控力”。决心是不畏艰险专注于某一目标的能力，自控力指抵抗分心和诱惑的能力。拥有极强的决心和自控力的领导者总是能取得更好的成果。(15)

4．真实、自我意识以及平衡。有弱点、不完美都是很正常的。好的候选人对于他们的成就有着清晰客观的认识，并会吸取教训，从而进一步改善。如果对于成功和失败没有足够的自我反省和反思，就会被扣分了。太多的“我”、太少的“团队”会让候选人的吸引力降低，而不是提高。

5．活力和热情。顶级候选人会将他们的热情完全释放出来。如果他们对某个机会感兴趣，那就不会故作姿态，而是会完全表现出来。这让人们愿意加入他们的团队。

初任管理者的建议1：时刻注意你的仪容、态度和举止。 初任管理者的建议2：简洁地表达你的愿景，并且不停地重复。 初任管理者的建议3：尽快选好团队成员。 初任管理者的建议4：每一个有意义的商业问题最好能在较小的团队中解决。 初任管理者的建议5：表现得像个被人信赖的解答者。 初任管理者的建议6：你并不需要无所不知，而是应该多多找人咨询。

首席执行官的特质1：诚实，与公司的文化契合度。 首席执行官的特质2：智力上的好奇和敏捷。 首席执行官的特质3：有提升业务业绩的经验。 首席执行官的特质4：真实、自我意识以及平衡。 首席执行官的特质5：活力和热情。

=== 第三阶段：优化长尾，发挥持续影响力

有时，当我们自己的火焰熄灭，会有人用他们的火花将其重新点燃。每个人都应该对那些点燃我们内心之火的人满怀谢意。 阿尔贝特·施韦泽（Albert Schweitzer）

蒂姆在离开商学院后立刻就加入了宝洁的品牌管理部门，因为“他们的提问更好”。在接下来的15年里，他一步步升职。37岁时，他想要接受更大的挑战，于是进入宝洁在俄亥俄州辛辛那提市的总部，开始接手英国和美国的国际业务。之后，他又回归加拿大，风风火火地做了12年宝洁加拿大的总裁。我们会在第12章详细探讨他的这份跨越国界的职业生涯。作为一名身处第二阶段的高级管理人员，蒂姆努力在每周70个小时的工作和完整的家庭生活之间寻找平衡。对于自己的升职之路，蒂姆是这样评价的：“我从来没有喘息的机会。如果你真的擅长某件事情，他们就会给你更多的责任和工作，而不是更少。公司要看到的不是顺从，而是业绩。要想让你的老板和公司取得成功，除了努力工作，别无他法。”

蒂姆在第三阶段的转换做得比大多数人都好得多。他在进入第三阶段时进行了一些意义重大的试验，尝试不同的角色来契合这个新的人生阶段和新的目标。蒂姆清点了从之前几个阶段继承下来的技能，找出那些在新的组织中依然有用的部分。他成功接受了这次重大的思维转换，即从“行动者”到“建议者”，而许多人都没能在自己的职业生涯中完成这一转变。如今，身处第三阶段、名义上已经退休的蒂姆虽然每周依然会在工作中投入至少35个小时的时间，但是大部分都属于社区和非营利性事业。他将自己能够保持活力的原因归功于有意义的工作和每日的健身锻炼。蒂姆对成长和学习保持着一种健康的观念：“重要的不是管理你的职业生涯，而是管理你的学习曲线。你要让自己的学习曲线陡峭，要勇敢面对困难的问题，并自愿接受挑战。”

== PART 3　应对职场和生活的冲突


=== 如何做好职场父母？

1．不要让职业生涯和为人父母成为非此即彼的选项。不要因为觉得肯定会危害职业生涯而害怕生孩子。那些两头兼顾的成功人士已经指出了越来越多的兼顾工作和家庭的办法。即使为人父母意味着你要暂时退出全职工作的行列，也还有回归的机会。

2．找到一个热爱家庭的雇主。这样的老板可不少。不同的行业和雇主在灵活度和宜人度方面千差万别。你可以问问内部人士，实际情况究竟如何，也可以查询一下“在职父母最佳去处”榜单。奥美集团最近刚在北美地区宣布了改进后的产假政策：

3．如果没有后方的恰当支持，你就无法生存。专家们都说，如果在大后方没有有效的支援体系，你是成不了大事的。支援体系的选择是个见仁见智的决定，支持可以来自配偶、伙伴、家庭成员、托儿所、保姆或各种选择的组合。米莱娜·贝里表示，即便尝试在家里远程办公，你也需要别人的支持，才能度过一些关键时刻，例如早晨和放学的时间。一位管理着20

4．设立现实的期望和严格的界限。别在开始就为自己预设失败和不幸。将自己逼成一匹在任何时间、任何期限内都能完成任何工作的“驮马”或许并不是一种现实的定位。永不拒绝可能最终会招致灾难，你需要掌握“有条件地接受”的技能。你要清楚地表现出你有能力、有热情，也愿意为团队的成功而付出。虽然凡事好商量，但你也要有底线。

4．设立现实的期望和严格的界限。别在开始就为自己预设失败和不幸。将自己逼成一匹在任何时间、任何期限内都能完成任何工作的“驮马”或许并不是一种现实的定位。永不拒绝可能最终会招致灾难，你需要掌握“有条件地接受”的技能。你要清楚地表现出你有能力、有热情，也愿意为团队的成功而付出。虽然凡事好商量，但你也要有底线。

我非常清楚有些界限坚守起来有多困难。当夏兰泽成为美国运通公司在奥美的全球业务的领导者时，大家对她的期望都很高。她深受爱戴，而且经常被客户视为绝对不可或缺的人物。当美国运通邀请她参加一场为期一天的5年计划会议时，她的回答是要到下午一点才能到场，因为她已经跟其中一个孩子约好了一件重要的事情。她愿意做些额外的事前准备，有必要的话可以在晚上多留一会儿。在下午一点，夏兰泽在一些与会者惊奇的目光中准时走入了会议室。夏兰泽是这样解释的：“如果我在这间会议室里缺席了几个小时，没人会真的想念我。但我不能在学校开放日上放我儿子的鸽子。”夏兰泽还说：“你不可能永远都陪着他们。为了工作，你可能要连续几天离开孩子。你要让他们放心，知道他们才是你生命中最重要的东西。重要的不是时间，而是感觉。”

最善于划定界限的人都能清晰地指出，哪里有余地，哪里又有阻力。“是的，这是个很不错的任务，我可以在周二、周三或周五完成，但不能是周六中午。”如果说重点是避开“无条件地接受”的话，那么“无解释地拒绝”也是万万不可的。当职场父母对任务、工作或晋升说不时，别人就会以为他们不够灵活，而且已经不思进取了。你需要明确地化解这些误解。我认识一位女性高管，她得到了一次很大的晋升机会，但是知道自己当时无法让新的职位与家庭保持平衡。她并没有直接说不，而是说：

5．管理你的时间和精力。珍妮特·凯斯汀说，边工作边当父母是磨炼时间管理技能的终极方法。“刚开始的时候，我觉得接受或寻求帮助是一种弱者的表现。但后来我发现求助和托付是一门生存技能。做事不能盲目。在早上9点半带着一颗清醒的头脑上班可能比在9点压力重重、昏昏沉沉地出现更好。重要的不是时间，而是结果。”在谈到生产力时，米莱娜·贝里提出了“三宝”的概念：“你需要做对三件事情：睡眠、饮食和锻炼，这样才能管理好压力，过好生活。这是三件别人无法帮你完成的事情，你必须为自己做好这些事，因为它们是支撑你前进的动力。”米莱娜的工作离不开这三宝，她宁可牺牲工作的时间，也要保证工作的质量。

1．重新包装你的技能。如果你的技能过时了或派不上用场了，那么你就需要做些准备。或许你可以幸运地加入像“回归之路”的“回归生”那样的培训项目。你也可以找其他方法，让自己的技能年轻化、现代化，例如：在成人学校、大学、研究生院、在线课程或像“会员大会”（General

2．重新组织你的经验。尽管你拥有许多很好的经验，但如果过了很长时间才回归职场，你对这些经验的理解往往就会变得陈旧过时或不合时宜。我碰到过几个有目标的“回归生”，他们在整场面试中一直在列人名或说一些陈年的英勇事迹。他们高谈阔论着过去，提到未来的时候只表现出轻蔑（“这个疯狂的电子玩意儿”）或说自己并不了解。雇主怎么可能将珍贵的钞票拿来雇用这样的候选人呢？你必须重新组织自己知道的东西，并将其与现在和未来客观地联系起来。研究一下你想要重新进入的行业的未来愿景，订阅一些潮流的行业出版物和博客，将你的技能、智慧和经验与雇主的情况及他们的目标适当地加以结合。只有当你的过去能够帮助潜在雇主取得成功时，它才有意义。他们才不想要听你和朋友在1997年发明了互联网之类的光辉岁月。所以，请告诉他们你知道什么，以及能做什么来帮助他们取得今天以及接下去几年的成功。

2．重新组织你的经验。尽管你拥有许多很好的经验，但如果过了很长时间才回归职场，你对这些经验的理解往往就会变得陈旧过时或不合时宜。我碰到过几个有目标的“回归生”，他们在整场面试中一直在列人名或说一些陈年的英勇事迹。他们高谈阔论着过去，提到未来的时候只表现出轻蔑（“这个疯狂的电子玩意儿”）或说自己并不了解。雇主怎么可能将珍贵的钞票拿来雇用这样的候选人呢？你必须重新组织自己知道的东西，并将其与现在和未来客观地联系起来。研究一下你想要重新进入的行业的未来愿景，订阅一些潮流的行业出版物和博客，将你的技能、智慧和经验与雇主的情况及他们的目标适当地加以结合。只有当你的过去能够帮助潜在雇主取得成功时，它才有意义。他们才不想要听你和朋友在1997年发明了互联网之类的光辉岁月。所以，请告诉他们你知道什么，以及能做什么来帮助他们取得今天以及接下去几年的成功。

在更新了行业与公司的相关知识和语言之后，就该确定你与它们的契合点了。将这些东西写下来，稍加修饰并辅以佐证，将其打磨成一段两分钟的简短介绍，并事先排练好。

3．重新连接职业生态系统。如果你已经离开职场好几年时间了，那么我敢保证，你的职业生态系统需要好好地翻修一下，毕竟只拿出一些前同事和已经退休的高管的名字并没有什么用。你需要将职业生态系统中的主要元素都审视一遍，参见第5章，即你的联系人、专家团、关键同事和支持者。到领英、Facebook和其他任何能让你接近那些目标行业相关人士的社交网站上看一看；重新在校友会中活跃起来，加入行业团体，计划数十次，最好是数百次地请人共进咖啡。

4．重新建立你的自信。成功的“回归生”无不提到重建自信的必要性。正如一位在职母亲开玩笑时说的那样，在花了10年时间与智商只有两位数的孩子说话之后，自信心怎么可能不降低呢。这样的意见我已经听过无数遍了，后来我就发明了一个叫作“费瑟斯通豪家庭智商守恒定律”的玩笑性数学假说，这个假说是这样的。

如果雇主和员工无法找到方法，让职业生涯和为人父母不再成为非此即彼的选择，那么问题就严重了。雇主是那么渴望合适的人才，而家长又那么渴望合适的工作。组织需要为在职父母创造更灵活和开明的政策，与此同时，以职业为中心的父母需要制订策略并采取行动，其中包括：寻找对家长友好的雇主、找到可利用的后方支援体系、学着划清界限，以及管理时间和精力。“回归生”理应成为一个全球现象，其原则是重构过去的经验、重塑技能集合、重新连接职业生态系统和重建自信。配平职业生涯和为人父母的方程式会给你带来巨大的回报：更高的生产力、更强的创造力和更幸福的生活。

职业生涯与为人父母共存之道1：不要让职业生涯和为人父母成为非此即彼的选项。 职业生涯与为人父母共存之道2：找到一个热爱家庭的雇主。 职业生涯与为人父母共存之道3：找到后方的恰当支持。 职业生涯与为人父母共存之道4：设立现实的期望和严格的界限。 职业生涯与为人父母共存之道5：管理你的时间和精力。

回归正轨之法1：重新组织你的经验。 回归正轨之法2：重新包装你的技能。 回归正轨之法3：重新连接职业生态系统。 回归正轨之法4：重新建立自信。

=== 如何看待跨国工作？

环游世界的愿望一直都是人们最高的人生目标之一。有意思的是，这并不限于年轻的梦想家或手上有大把时间的老人。这是跨越几乎所有国家、所有年龄段人士的顶级目标。(19)大部分人都喜欢出国观光，但有多少人愿意出国工作呢？现在，越来越多的职场路径呈现出跨国的机会和竞争，你该如何决定在何时、何地以何种方式接受一份跨国工作呢？接受一个远离家乡的职位，其中存在什么样的好处、现实问题和陷阱呢？

国际化思维是一项可迁移性非常强的技能，因为它让我们能欣赏多种多样的思想和文化。它有助于开启新的机会之门，带来全新的经历。不管你对自己的职业生涯有没有野心，踏出舒适圈都会是一种有价值和意义的经验。卡尔鼓励学生和毕业生尽可能地接触国际市场。“活到老学到老，走到哪儿学到哪儿。不断接触别的家庭，”他建议道，“有时候虽然你很难或根本不可能学会他们的语言，但不要放弃。了解一下这个国家的历史、地理和文化。你知道如果你认真地去了解别人的历史、英雄人物和音乐，他们会有多高兴吗？”

=== 如何应对职场危机？

每个人都有一个计划，直到被打掉牙的那一刻。 迈克·泰森　世界重量级拳王

1．应对职场危机的第一步应该是清晰客观地认识问题。这是一个不可避免的事件、一个认知上的问题，还是业绩上的问题？如果这的确是一个不可避免的事件或单纯的坏运气，比如说你的公司意外地被收购了，那你就得尽快恢复过来。尽管短暂地悲伤或发泄一下没什么问题，但是最好的应对方法还是重新站起来，回归职场；体面、勤勉而优雅地将过去打包，向着前方进发。

2．有时候，职场危机可能是由他人对你的技能、目标或业绩的错误认识引起的。也许新来的老板并不知道你所有的技能或过去的重大贡献；也许你的公司并不知道你渴望着得到新的或更高的职位，于是就没有考虑过你；也许你因为某个与你并不直接相关的业绩问题而受到了不公正的影响。不要怪老板或公司没看见你的才能，你应该将这件事当成一个项目，以此来证明你真正的价值。如果你的产品确实很好，那么你只需要改善关系就行了。找出认知的偏差，让别人清楚地认识到，真正的你要比他们认为的更好。

3．在其他情况中，你的不足之处可能并不只是认知上的，而且是真实存在的。如果客观分析表明你实际的技能和业绩落于人后，那么你就需要正面对待这个问题了。认清正常的技能和业绩应该达到何种程度，然后朝这个方向努力，你不可能逃避问题。如果有人升职的速度比你快，那么不妨默默地找出是哪些技能让老板做出了这样的决定。然后积攒职场燃料，让自己有资格赢得下一次加薪、升职或新的好工作。

4．有的职场危机是可以预见并规避的。如果想得远一点，并时刻关注你的公司、你的行业和你自己的业绩的变化，就可以时常避免遭到突然袭击。如果你发现自己的行业、公司或职位已陷入了危机，那么就需要主动采取行动，准备好一份备用方案。所以，你需要培养一些能让自己免疫风险的技能和关系，在当前的环境之外留一些可选之路。

5．无论你的职场危机是不可预知的还是可以预料的，你都需要从逆境中快速恢复的方法。在第11章中提到过的关于“回归生”的“4个重新”就是一种迅速回归正轨的通用方法。如果你被开除了或被排挤了，就可以以“4个重新”为基础，加速回归正确的轨道。

与朱尔斯·戈达德一样，我也认为，恢复职业生涯最大的障碍之一就是骄傲。健康的自信心是好的，虚张声势、否认一切和痴心妄想却都是毁灭性的。脆弱是过度保护的恶果，逆境和压力是有益的。戈达德指出，在太空的失重环境下，我们的骨骼失去了压力，于是就会变得脆弱。你的自信心必须建立在有市场竞争力的东西上面。在职业生涯中，你时常会不得不偏离航线或干脆后退才能继续前进。因此，在遭遇职场危机时，请将骄傲放在一边，它会碍事的。

与朱尔斯·戈达德一样，我也认为，恢复职业生涯最大的障碍之一就是骄傲。健康的自信心是好的，虚张声势、否认一切和痴心妄想却都是毁灭性的。脆弱是过度保护的恶果，逆境和压力是有益的。戈达德指出，在太空的失重环境下，我们的骨骼失去了压力，于是就会变得脆弱。你的自信心必须建立在有市场竞争力的东西上面。在职业生涯中，你时常会不得不偏离航线或干脆后退才能继续前进。因此，在遭遇职场危机时，请将骄傲放在一边，它会碍事的。

与朱尔斯·戈达德一样，我也认为，恢复职业生涯最大的障碍之一就是骄傲。健康的自信心是好的，虚张声势、否认一切和痴心妄想却都是毁灭性的。脆弱是过度保护的恶果，逆境和压力是有益的。戈达德指出，在太空的失重环境下，我们的骨骼失去了压力，于是就会变得脆弱。你的自信心必须建立在有市场竞争力的东西上面。在职业生涯中，你时常会不得不偏离航线或干脆后退才能继续前进。因此，在遭遇职场危机时，请将骄傲放在一边，它会碍事的。

几乎没有人会像尼罗弗·麦钱特那样，在18岁时就几乎身无分文、无家可归，也很少有人会像阿兰·休斯敦那样被迫在30多岁时退役，但是我们可以从他们身上学到许多走出职业生涯逆境的方法：利用好奇和探索的武器培养技能和经验，建立起能抵挡不可避免的挫折的免疫系统；不断寻找自己的理想，如果不知道什么才是重要的，那么就回归人性；确保你的信心是有根据的，如果你的失败并不主要源于坏运气，那么就得采取行动，找出欠缺的关系或技能；不要让骄傲阻挡了重获新生的道路；你可能需要退一步才能海阔天空；坚持自己的核心价值观和真正的自我。

== 尾声　工作的未来

我只对未来感兴趣，因为我的余生将在那里度过。 查尔斯·凯特林（Charles Kettering）发明家 

幸福感源自内心。 威廉·阿瑟·沃德（William Arthur Ward）

预计到2025年，高达四分之一的工作将会被智能软件或机器人取代。牛津大学的一项研究则表明，在英国目前的工作岗位中，有35%在接下来的20年里都存在被自动化的风险。”该报告接着回顾了在牛津大学的研究中分析的282个岗位，评估了部分岗位被取代的风险。最脆弱的工作大部分本质上都是机械性和重复性的，比如从事写报告、做表格等重复性工作的办公室职员就很容易被软件取代，工厂工人也因为更加灵巧的机器人被开发出来而变得越来越危险。“随着更先进的工业机器人越来越多地配备了更强大的感知能力，手指和手掌的运动能力也越来越协调，从而能够进行更精细的操作和组装，这些机器人将有能力完成更多、更复杂的手工任务。不过，在无秩序环境下的操作，例如必须由清洁工完成的任务，在可预见的未来内依然不是自动化可以企及的范畴。”

《幸福有方法》大致描绘了12种“基于证据、得到科学研究支持的提高幸福感的策略”。其中包括： 

* 表达感恩；
* 培养乐观的心态；
* 避免思虑过度和社会攀比；
* 多行善事；
* 维护人际关系；
* 发展合作的策略；
* 学会原谅；
* 增加心流体验；
* 享受生活的乐趣；
* 努力实现目标；
* 信仰宗教，寻找精神寄托；
* 关注身体健康。


面临机器的竞争：明智之举是培养情商、创造力、协作能力和建立信任关系的技能。 

在哪里找工作：像领英这样的在线平台将成为公司寻找人才、个人寻找工作的主要场所。 

将时间投资在哪里：创业和自由职业将在不久的将来蓬勃发展，工作目标也将更多样化。
怎样保持收入稳定：退休并不代表就能安享晚年，继续工作才能获得稳定的收入。 

享受工作的快乐：想在工作中更快乐，就需要提高幸福感，试一试文中的12种策略吧！
