---
title: "《投资中最简单的事》之读书笔记（一）：投资理念"
date: 2022-02-24T23:38:00+08:00
draft: false
categories: ["阅读摘要"]
tags: ["书籍", "方法论", "投资理财","股票","金融"]
thumbnail: "images/books/the-simple-things-in-investment.jpg"

weight: 1
---

最近一位同事离职，在践行宴会上，大家聊到投资理财，D瓜哥推荐了 https://book.douban.com/subject/35000951/[《投资中最简单的事》^]。去年已经把这本书读完了，下班后把这本书的摘要笔记整理一下，按照章节，分四篇来分享：

* https://www.diguage.com/post/the-simple-things-in-investment-1/[《投资中最简单的事》之读书笔记（一）：投资理念^]

== 推荐序

天下武林，林林总总。名门正宗如少林武当，诚然名扬天下，而武林之大，但凡修得暗镖神剑者，亦可独步江湖。

即使最成功的投资人，也要心胸坦荡，认识到自我局限，不可以名门正宗自居，须认识到获得真理是一个学无止境、永远追求的过程。

在多数人都醉心于“即时满足”（ instant gratification）的世界里，懂得用“延迟满足”（ delayed gratification）去做交易的人，已先胜一筹了。

健康的环境和心情是长期修行的结果。

== 初版序

成长投资的价值支撑主要来自企业未来收入和利润的高增长，更强调公司未来的价值 V~n~ 要远大于公司现在的价值 V~0~，但这种投资需要预测未来的远见，只有极少数的人能够做到。

我努力奉行一些简单的原则，例如：

* **第一，便宜是硬道理。**即使是普通公司，只要足够便宜，也会有丰厚的回报。
* **第二，定价权是核心竞争力。**有核心竞争力的公司有两个标准：一是做的是自己可以不断复制的事情，比如麦当劳和星巴克可以不断地跨区域开新店，在全世界成功复制；二是做的是别人不可能复制的事情，具备独占资源、品牌美誉度、专利、技术、寡头垄断地位、牌照准入限制等特征，最终体现为企业的定价权。
* **第三，胜而后求战，不要战而后求胜。**百舸争流的行业，增长再快也很难找投资标的，不妨等待行业“内战”结束、赢家产生后再做投资。
* **第四，人弃我取，逆向投资。**无论是巴菲特、索罗斯，还是邓普顿、卡尔·伊坎，投资领域的集大成者大多数都具有超强的逆向思维能力。

这些规律性的东西虽然看起来是投资中最简单的事，却也是投资中最本质的东西，并不会因为时空的不同而产生大的差异。

== 第一部分　投资理念

=== 01　以实业的眼光做投资

下跌后，悲痛欲绝；上涨后，欢欣雀跃。两者均无必要。

以买企业的心态做投资，不因急跌而失措，也不因急涨而忘形。

在一个先发优势不断被颠覆、没有永远的赢家的行业里，只有勇于自我否定、因时而变才能生存。

成长是未来的，难预测；门槛是既成的，易把握。

第一，把客户的钱当作自己的钱来珍惜；第二，把二级市场的股票投资当作一级市场的实业投资来分析。

如果用自己的钱做实业投资，首先要考虑的问题就是：这是不是一门好生意。

人们只看到成功的“一将”，选择性地忽视了“枯了的万骨”。

什么行业易出长期牛股？行业集中度持续提高的行业。

用自己的钱做实业投资要考虑的第二个问题，就是这门生意的现金流状况如何，毕竟做生意的最终目的是赚取现金流。

好公司的两个标准：一是它做的事情别人做不了；二是它做的事情自己可以重复做。前者是门槛，决定利润率的高低和趋势；后者是成长的可复制性，决定销售增速。如果二者不可兼得，宁要有门槛的低增长（可持续），也不要没门槛的高增长（不可持续）。门槛是现有的，好把握；成长是将来的，难预测。

用自己的钱做实业投资要考虑的第三个问题就是行业的竞争格局以及公司是否具有比较优势。

作为一个后来者，想颠覆既有的龙头老大的地位，就得看自己能够为客户提供哪些不可比拟的价值，以及相对于竞争对手的比较竞争优势在哪里。

互联网的本质是“人生人”，优势在于能以极低成本服务无数客户，规模效应体现在“人多”，“二八”现象不明显，是典型的散户经济，得散户者得天下。银行业的本质是“钱生钱”，规模效应体现在“钱多”， 80%的业务来自 20%的客户，“二八”现象显著，得大户者得天下，而且那 20%的大客户是需要线下的高端服务的，这就是网上银行至今在欧美日韩都没有很成功的案例的重要原因。

互联网“人生人”主要靠两条：一是网络效应；二靠人多提升用户体验。

中国线下零售的分散和低效是中国线上电商迅速崛起的重要原因。

分析技术变化快的行业时不必看市场占有率，而要看是否适应最新的杀手级应用的潮流。

做投资要研究的就是这些不以人的意志为转移的规律，而不是整天去猜测市场的情绪变化。

宝石被人扔进泥里再踩上几只脚也仍是宝石，砖头被请进庙堂受人膜拜也仍是砖头。

市场的主题炒作往往是短期的，长期起决定性作用的仍然是行业竞争格局、公司竞争优势和定价权。只有坚持以实业的眼光去评估企业的价值，不受市场的极端情绪波动所影响，时间才会是我们的朋友。

=== 02　人弃我取，逆向投资的关键

众人夺路而逃时，不挡路、不跟随。不挡路是因为不想被踩死，不跟随是因为乌合之众往往跑错方向。

新兴行业讲的是需求快速成长的事，不必纠结于供给。而传统行业则只有控制供给，企业利润才能快速增长。

长期看表现好的传统行业要么是寡头行业，要么是淘汰落后产能的行业，二者的供给增长相对于需求而言都受到了有效控制。

很多人认为小股票的成长性普遍好于大股票。如果这是事实的话，那么大多数行业的集中度就会越来越低。

以高估值买新兴行业而落入成长陷阱的是沉迷于“未得到”，以低估值买夕阳行业而落入价值陷阱的是沉迷于“已失去”。投资中风险收益比最高的还是那些容易被低估的“正拥有”。

人弃我取、逆向投资是超额收益的重要来源。

一只下跌的股票是否值得逆向投资的关键在于以下三点：

* 首先，看估值是否够低、是否已经过度反映了可能的坏消息。
* 其次，看遭遇的问题是否是短期问题、是否是可解决的问题。
* 最后，看股价暴跌本身是否会导致公司的基本面进一步恶化，即是否有索罗斯所说的反身性。

买股票之前问问自己，下跌后敢加仓吗？如果不敢，最好一开始就别买，因为价格的波动是不可避免的。

食品饮料是个适合逆向投资的领域。

大家都挤在树上摘葡萄时，也许就是该在地上捡苹果的时候了。

A股的情绪波动容易走极端，因此“人多的地方不去”是至理名言。

牢记管子所说的“不处不可久，不行不可复”，不去“击鼓传花”，不接最后一棒，把选股范围基本限制在低估值的大盘蓝筹里，以此躲过中小盘中的许多“地雷”。

一般说来，趋势的初期和末期，就是真理在少数人手里的时候。

买早了还得熬得住，这是逆向投资者的必备素质。

顶部和底部只是一个区域，该逆向时就不要犹豫，不要在乎短期最后一跌的得失，只要能笑到最后，短期难熬点又何妨？只有熬得住的投资者才适合做逆向投资。

躲在冷门行业的好处是永远不用担心被“踩踏事件”伤着。

优质公司碰到短期问题时，往往是较好的投资时点，

=== 03　便宜是硬道理

贪婪有两种，一种是在 6000点时明知贵了，但还想等多涨一会儿再卖；另一种是在 2000点时觉得便宜了，但还想等多跌一会儿再买。

有销售半径的行业（如啤酒和水泥），重要的不是全国市场占有率，而是区域市场集中度。

从“军阀混战”的无序竞争过渡到“军阀割据”的有序竞争，是值得关注的行业拐点。

没有门槛的高增长是不可持续的。

做投资最重要的是什么呢？**投资中影响股价涨跌的因素是无穷无尽的，但是最重要的其实只有两点，一个是估值，一个是流动性。**

估值决定了股票能够上涨的空间；流动性则决定了股市涨跌的时间。

所有的价格其实本质上都是一种货币现象，就是说你的资金跟你所有东西的价格之和其实是一致的。

要分清楚什么东西先动，什么东西后动，什么东西是你更关心的其他东西的领先指标。

所谓的投资，就是牢牢抓住这个定价权。

**选股票，一定是先选行业。**就像买房子，一定是先看社区，社区不行，房子再漂亮也不行。买股票也是，股票本身再好，只要这个行业不好，一样很难涨起来。买房子先选社区，买股票先选行业，那么什么样的行业是好行业呢？很简单，有门槛、有积累、有定价权的那种行业。

定价权的来源，基本上要么是垄断，要么是品牌，要么是技术专利，要么是资源矿产，或者相对稀缺的某种特定的资产。

这和一个年轻人在选择行业的时候，一定是找那种有积累的行业一个道理。

技术变化快的行业就是这样辛苦，而像可口可乐，一个配方可以一两百年不变。

*投资还要想好你要做什么样的投资者。*

**通胀环境下买什么股票好？**常见的答案是资产资源类股票，因为投资者可以直接受益于价格上涨。更好的答案也许是那些有定价权的公司：通胀时它们可以提价，把成本压力转嫁给下游；通胀回落时，它们不必降价就享受更高的利润率。这些公司包括食品饮料等品牌消费品和工程机械、核心汽配、白色家电等寡头垄断的高端制造业。

==== 三个层次的悲观

* 第一个层次的悲观是基于流动性和供求关系的悲观。
* 第二个层次的悲观是对基本面的悲观。
+
--
随着世界慢慢进入一种胜者为王，赢家通吃的年代，我们确实会发现一部分公司具有强大的定价权：能够卖多少钱就卖多少钱，想收什么费就收什么费。

巴菲特所说的找那种“傻子都能管”的公司

谁都能做管理层的公司就是好公司。

有一定资产的人，必须不断思考一个问题：我的财富以什么样的形式存在才最容易保值增值。

过去 10年是涨还是跌跟今后会涨还是会跌，其实并不一定相关，关键是这个东西是不是物有所值。

我一直觉得一定要一分为二地看待投资的风险：一种风险是本金永久性丧失的风险， 100万元投进去，之后损失了 10万元、 20万元，再也不回来；还有一种是价格波动的风险，可能短期会跌但也会涨回来，波动的风险是投资者必须承担的。

所以永久性亏钱只有两个原因，一个是市盈率的压缩。

另一个是利润在历史高点的时候，夕阳行业就有本金永久性丧失的风险。
--
+
* 第三个层次的悲观是一种长期悲观，是对中国经济增长模式的悲观。

做投资真正想赚到比别人更多的收益，就要保持一个判断的独立性。

=== 投资随想录

同一件事，看多者和看空者往往作截然不同的解释——你看到的是你想看到的。

持同一种观点的人，其依据和逻辑往往是截然不同的——你证明的是你想证明的。

同一消息，在不同的市场环境下常有不同的解读——你听到的是你想听到的。

同一事情两种解读，往往是考虑的时间跨度不同。

趋势投资者喜欢追着狗（价格）跑；价值投资者喜欢跟着人（价值）走，耐心等狗跑累了回到主人身边。

个例令人景仰，但往往难以复制，顺着规律选股才能提高成功率。

传说中的“十倍股”成长股就像千里马一样可遇而不可求，还是脚踏实地找些价值股，也就是“普通好马”靠谱些。

**不为精彩绝伦的牛股倾倒，不被纷繁复杂的个例迷惑，不抱侥幸心理，不赌小概率事件，坚持按规律投资，这是投资纪律的一种体现，也是投资成功的必要条件。**
