---
title: "《投资中最简单的事》之读书笔记（三）：投资风险"
date: 2022-02-26T23:38:00+08:00
draft: false
categories: ["阅读摘要"]
tags: ["书籍", "方法论", "投资理财","股票","金融"]
thumbnail: "images/books/the-simple-things-in-investment.jpg"

weight: 1
---

最近一位同事离职，在践行宴会上，大家聊到投资理财，D瓜哥推荐了 https://book.douban.com/subject/35000951/[《投资中最简单的事》^]。去年已经把这本书读完了，下班后把这本书的摘要笔记整理一下，按照章节，分四篇来分享：

* https://www.diguage.com/post/the-simple-things-in-investment-1/[《投资中最简单的事》之读书笔记（一）：投资理念^]
* https://www.diguage.com/post/the-simple-things-in-investment-2/[《投资中最简单的事》之读书笔记（二）：投资方法^]
* https://www.diguage.com/post/the-simple-things-in-investment-3/[《投资中最简单的事》之读书笔记（三）：投资风险^]
* https://www.diguage.com/post/the-simple-things-in-investment-4/[《投资中最简单的事》之读书笔记（四）：投资心理学^]

== 第三部分　投资风险

=== 07　价值陷阱与成长陷阱

==== 价值陷阱

* 第一类是被技术进步淘汰的。
* 第二类是赢家通吃行业里的小公司。
+
集中度越来越高说明行业里的龙头企业比其他企业增长更快，不然就是越来越分散。
+
* 第三类是分散的、重资产的夕阳行业。
* 第四类是景气顶点的周期股。
+
--
对周期股价值的评估可以借助两个概念，一个是常态化的盈利（ Normalized Earnings），计算剔除了经济周期波动后的企业盈利；另一个是盈利能力（ Earnings Power），而不是某一时间的盈利数额，评估企业内在的可持续的盈利水平。

____
怎么操作?
____
--
+
* 第五类是有会计欺诈的公司。
* 最后一类是人不行、捧着“金饭碗”讨饭的公司。“

金玉之堂，莫之能守

==== 成长陷阱

成长陷阱比价值陷阱更常见。

* 估值过高
* 技术路径踏空
* 无利润增长
* 成长性破产
* 盲目多元化
* 树大招风
+
追随者挑战巨头的时候要小心，不要太早显露目的，以免遭到巨头的封杀和围剿。
+
* 新产品风险
* 寄生式增长
* 强弩之末
* 会计造假

各类价值陷阱的共性是利润的不可持续性，各类成长陷阱的共性是成长的不可持续性。

成长本身并不是陷阱，但人性的弱点中对未来成长习惯性地过高预期和过高估值却是不折不扣的陷阱。

管子说：“不为不可成，不求不可得，不处不可久，不行不可复。”

==== “黄金坑”还是“融化中的冰棒”

这有点像一根正在融化的冰棒，你拿在手中它就不断地融化。

价值陷阱大部分的问题主要出现在内在逻辑被破坏，这样整个公司的护城河、核心竞争力逐步丧失，整个公司要么被时代淘汰，要么被对手打败，这种大多数是价值陷阱。

我们需要理解什么是永久性的下跌，什么是暂时性的调整。

如果找到了每一个公司便宜的原因，就能判断相应的股票是价值陷阱还是“黄金坑”。

趋势投资是可以不断止损的，每一次错误最大的损失是有限的。所以，从这个意义上看，价值投资的风险比趋势投资更大。

=== 08　真假风险与安全边际

股市如围城，城内的人在往外逃，城外的人在往里冲。

在互联网时代，品牌的优势比渠道的优势更重要。

股票暴涨后，真实的风险上升，感受到的风险却在下降，在 6 000点股市最危险的时候大家感受到的都是歌舞升平；股票暴跌后，真实的风险下降，感受到的风险上升，在 2 000点股市相对低谷时人们感受到的却都是凄风苦雨。

黑色星期一之后暴露的风险很大，但是隐藏的风险不大；感受到的风险很大，但是真实的风险不大。能区分并利用这两种风险的不同，是成功投资的必要条件。

对于逆向投资者来说，最痛的时候，往往是最不该放手的时候。正如索罗斯所说，如果你承受不了失败的痛苦，就不要入市，因为没有人能够百战百胜。

==== 安全边际

. 东方不亮西方亮，给点阳光就灿烂
. 估值低到足以反映大多数可能的坏情况
. 有“冗余设计”，有“备用系统”来限制下跌空间
. 价值易估，不具反身性，可越跌越买
+
--
索罗斯所说的反身性是指股价下跌本身对公司基本面有负面作用，易形成自我强化的恶性循环。

____
贝尔斯登和可口可乐对比!多思考!!!
____
--

鼻莫如大，目莫如小

==== 止损

对于趋势投资者而言，止损不止赢是短线交易的第一法则，自不必多说。

*忘掉你的成本，是成功投资的第一步。*

不止损是有很严格的前提条件的：必须避开各种价值陷阱；所买的股票有足够安全边际；所承担的只是价格波动的风险而非本金永久性丧失的风险。

=== 09　价值投资的局限性

事实上，价值投资有其特定的适用范围和条件，清楚地认识到价值投资的局限性是成功投资的必经之路。

* 价值投资的第一个基本条件：所买的公司的内在价值应该是相对容易确定的。
* 价值投资的第二个基本条件：所投资的公司的内在价值应该相对独立于股票价格。
* 价值投资的第三个基本条件：要在合适的市场阶段采用。
* 价值投资的第四个基本条件：选取合适的投资期限。

价值投资和成长投资的区别在于：价值投资者认为未来充满不确定性，因此公司的价值应该主要来自现有的资产、利润和现金流；成长投资者认为买股票就是买未来，因此成长性是企业价值的主要来源。

[#chapter-10]
=== 10　四种周期、三种杠杆，行业轮动时机的把握

从国际分工看，每个国家都有自己的比较优势，这是国际贸易带来的必然结果，而且一个国家的长期牛股与其比较优势是一致的，

一个好的荐股逻辑包括三点：**估值**，这只股票为什么便宜（估值水平与同业比、与历史比；市值大小与未来成长空间比）；**品质**，这家公司为什么好（定价权、成长性、门槛、行业竞争格局等）；**时机**，为什么要现在买（盈利超预期、高管增持、跌不动了、基本面拐点、新订单等催化剂）。

==== 四种周期

. 政策周期
. 市场周期（估值周期）
. 经济周期
. 盈利周期

熊末牛初，股市见底时这四种周期见底的先后次序是：

* 政策周期领先于市场周期。在货币政策和财政政策放松后，市场往往在资金面和政策面的推动下进行重新估值。
* 市场周期领先于经济周期。美国历史上几乎每次经济衰退，股市都先于经济走出谷底（ 2001年的衰退除外）。
* 经济周期领先于盈利周期，换句话说，宏观基本面领先于微观基本面。过去 70多年中，美国的经济衰退从未长于 16个月，但是盈利下降经常持续 2 ~ 3年甚至更长。
* 熊末牛初，判断市场走势，资金面和政策面是领先指标，基本面是滞后指标。熊市见底时，微观基本面往往很不理想，不能以此作为低仓的依据。如果一定要等到基本面改善才加仓，往往已经晚了。


==== 三种杠杆

. 财务杠杆：对利率的弹性
. 运营杠杆：对经济的弹性
. 估值杠杆：对剩余流动性的弹性
** 第一阶段，熊市见底时，经济仍然低迷，但是货币政策宽松，利率不断降低，常常是财务杠杆高的企业先见底。此时，某些高负债的竞争对手已经或者正在出局（破产或者被收购），剩余的企业的市场份额和定价权都得到提高。
** 第二阶段，经济开始复苏，利率稳定于低位，此时的板块轮动常常是运营杠杆高的行业领涨，因为这类企业只需销售收入的小幅反弹就能带来利润的大幅提升，基本面的改善比较显著。
** 第三阶段，经济繁荣，利润快速增长，但是股票价格涨幅更大，估值扩张替代基本面改善成为推动股价的主动力，此时估值杠杆高，有想象空间的股票往往能够领涨。
** 第四阶段，熊牛替换时，不要太在意盈利增长的确定性，而应该关注股票对各种正在改善的外部因素的弹性。所谓的改善，并不一定是指正增长，也可以是下降的速度放慢，或者下降的速度低于预期。

运营杠杆高的行业里许多是低盈利、高波动、没有定价权的烂行业。

=== 投资随想录

芒格对年轻人择业有三个建议：别兜售你不相信的东西，别为你不敬佩的人工作，别和你不喜欢的人共事。

他长寿的秘诀之一是为他的私人医生们理财，而这些医生们自然会尽力地保证“摇钱树”的健康。

股市的历史就是政策与经济博弈的历史。

看得见的手经常干预看不见的手。

政策与经济的博弈，依据历史经验看，最终胜出的一般是政策，因为政策的特点是不达目标就逐步加码，直到达成目标为止。

政策底领先于市场底，市场底领先于经济底。

在估值低时贪婪，在估值高时恐惧。

什么行业最能代中国参与世界竞争呢？能代表中国参与世界竞争的行业应具备如下特点：本土市场巨大；横向已形成国内寡头垄断；纵向已实现产业链整合；相比国际竞争对手具有显著的规模和性价比优势（品牌和渠道优势目前还谈不上）。

日本、韩国的产业升级道路才是中国应该走的，转型必须依靠和发扬既有优势，而不是好大喜功地超前发展所谓的新兴行业。
