---
title: "关于制定公司内部 BOM 的一点想法"
date: 2022-08-29T09:19:59+08:00
draft: true
keywords: ["Java","Spring","依赖管理","Maven"]
tags: ["Java","设计","Spring","最佳实践"]
categories: ["Java","程序设计","软件工程"]
thumbnail: "images/java/spring-and-java.png"

weight: 1
---

到公司后，熟悉了一些项目后，发现大部分项目的依赖都比较陈旧，比如某些项目还在使用 Spring 3.x 的版本。所以，在进行需求开发时，也顺手把一些项目的依赖给升级了一下。周五，一个小伙伴问我关于升级 Spring 的经验。正好趁此机会，把一些经验总结一下。



== Spring Framework 升级

Spring Framework 从 3.2.6.RELEASE 开始提供 BOM。可以利用 BOM 简化 Spring 依赖声明：

[source%nowrap,xml,{source_attr}]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-framework-bom</artifactId>
            <version>5.3.22</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----

这样，就不需要重复声明 Spring 依赖的版本，直接使用即可。 Spring Framework Bom 保证了 Spring 自身依赖的版本统一。

这里，关于 Spring 的升级，还有几点需要说明：

. 从 Spring 3.0.0.RELEASE 到 Spring 3.1.4.RELEASE，Spring 有一个 `spring-asm`，如果不再使用这个区间的 Spring，请把这个依赖删掉。
. 如果使用了 Apache Velocity 1.X 作为前端模板，由于 Spring 5+ 将相关集成代码删除，所以，只能将 Spring 升级到 4.3.30.RELEASE。相关 BOM 如下：
+
--
[source%nowrap,xml,{source_attr}]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-framework-bom</artifactId>
            <version>4.3.30.RELEASE</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----
--
+
. 建议把 Spring XML 配置文件中，指明 `schemaLocation` 的 `spring-*.xsd` 的版本号删除掉，这样升级 Spring 时，会自动使用对应版本的 XSD 约束。


另外，Spring 全家桶还提供了很多其他的 BOM，这里列出一部分供参考使用：

[source%nowrap,xml,{source_attr}]
----
<dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-bom</artifactId>
    <version>2021.2.2</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
<dependency>
    <groupId>org.springframework.integration</groupId>
    <artifactId>spring-integration-bom</artifactId>
    <version>5.5.14</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
<dependency>
    <groupId>org.springframework.security</groupId>
    <artifactId>spring-security-bom</artifactId>
    <version>5.7.3</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
<dependency>
    <groupId>org.springframework.session</groupId>
    <artifactId>spring-session-bom</artifactId>
    <version>2021.2.0</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
----

WARNING: 这里只是列出来它们的最新版本，并没有测试它们的兼容性。

== Spring 4+ 与 iBATIS

Spring 4+ 删除了内置的 iBATIS 支持。可以通过添加下面这两个依赖来将使用 iBATIS 的应用升级到 Spring 4+。

[source%nowrap,xml,{source_attr}]
----
<dependency>
    <groupId>org.mybatis</groupId>
    <artifactId>mybatis-2-spring</artifactId>
    <version>1.1.0</version>
</dependency>
<dependency>
    <groupId>org.apache.ibatis</groupId>
    <artifactId>ibatis-sqlmap</artifactId>
    <version>2.3.4.726</version>
</dependency>
----

* 首先，iBATIS 与 MyBATIS 的代码包名不一样，无须担心存在冲突问题。
* 其次， `mybatis-2-spring` 就是将 Spring 删除的那部分代码重新打包了一下，和 MyBATIS 集成原理完全不同，也无须担心存在冲突问题。
* 最后，`org.springframework:spring-orm` 这个依赖是为了集成实现 JPA 标准的 ORM 框架准备的。所以，无论使用 MyBATIS，还是使用 iBATIS，都不需要这个依赖。

== MySQL 依赖升级

跟随 Spring Boot 的脚步，MySQL 依赖选择的是 `8+` 版。MySQL 依赖的版本从 `5.x` 升级到 `8.x` 时，一定要检查数据库连接字符串是否包含时区配置。如果没有，请添加 `serverTimezone=Asia/Shanghai` 的配置项。上线后，建议检查一下新增数据的日期字符数据是否正确。

具体原因请看： https://www.diguage.com/post/research-on-timezone-of-mysql-new-connection-driver/[关于 MySQL 新版连接驱动时区对齐问题的研究^]。

== Quartz

Quartz 的依赖坐标从 1.X 升级到 2.X 时发生了变化，需要做出调整。最新的依赖坐标如下：

[source%nowrap,xml,{source_attr}]
----
<dependency>
    <groupId>org.quartz-scheduler</groupId>
    <artifactId>quartz</artifactId>
    <version>2.3.2</version>
</dependency>
<dependency>
    <groupId>org.quartz-scheduler</groupId>
    <artifactId>quartz-jobs</artifactId>
    <version>2.3.2</version>
</dependency>
----

将 Quartz 升级到 2.X 版本，还需要修改关于 Quartz 的相关配置：

. 由于 `org.springframework.scheduling.quartz.CronTriggerBean` 不支持 Quartz 2.X，则需要将其替换为 `org.springframework.scheduling.quartz.CronTriggerFactoryBean`；
. 更新依赖引用的方式，由 `local=` 更新为 `bean=`，具体代码如下：
+
--
[source%nowrap,xml,{source_attr}]
----
<!-- D瓜哥 · https://www.diguage.com -->
<bean id="autoplanScheduler"
      class="org.springframework.scheduling.quartz.SchedulerFactoryBean">
    <property name="triggers">
        <list>
            <!-- 将依赖应用由 local= 更新为 bean= -->
            <ref bean="myCronTrigger"/>
        </list>
    </property>
    <property name="autoStartup" value="true"/>
</bean>
----
--

== Javassist

Javassist 从 3.12.1.GA 升级到 3.13.0-GA 时，将 `groupId` 从 `javassist` 改为 `org.javassist`。另外，它从 3.24.0-GA 开始，编译版本改为 `1.8`（测试编译版本为 `11`）。考虑到兼容性以及后续升级方便，最少需要升级到 3.24.0-GA。这里选择了当前最新版 3.29.1-GA。所以，在升级该 Jar 包时，需要注意修改 Maven 坐标声明中的 `groupId`。最新坐标如下：

[source%nowrap,xml,{source_attr}]
----
<!-- D瓜哥 · https://www.diguage.com -->
<dependency>
    <groupId>org.javassist</groupId>
    <artifactId>javassist</artifactId>
    <version>3.29.1-GA</version>
</dependency>
----

有几点需要特别注意：

. 由于 `groupId` 发生了变化，Maven 不能解决这类的“依赖冲突”，所以需要手动检查并排除低版本 Javassist；
. 如果同时依赖了两个版本的 Javassist，就要看加载顺序了。如果先加载了低版本的 Javassist，那么就可能会出现运行时异常，提示不能识别高版本的字节码。

== Validation API & Hibernate Validation

由于 Oracle 把 JavaEE 甩给了 Eclipse 基金会，但是却没有授权 Eclipse 基金会使用 `javax` 包名。所以，Eclipse 基金会投票决定将 JavaEE 改名为 JakartaEE，同时后续推出的新标准全部使用标准以 `jakarta.` 为包前缀，同时，一大批的相关依赖的坐标都发生了变化。其中，就包括 Validation API，由 `javax.validation:validation-api` 改为 `jakarta.validation:jakarta.validation-api`，从 `2.0.1` 开始，就发生了变化。但是，2.X 版本的依赖只是把 Maven 坐标发生了变化，从 3.0.0 开始，包前缀开始发生变化。

[source%nowrap,xml,{source_attr}]
----
<!-- D瓜哥 · https://www.diguage.com -->
<dependency>
    <groupId>jakarta.validation</groupId>
    <artifactId>jakarta.validation-api</artifactId>
    <version>2.0.1</version>
</dependency>
<!--或-->
<dependency>
    <groupId>javax.validation</groupId>
    <artifactId>validation-api</artifactId>
    <version>2.0.1.Final</version>
</dependency>
----

其实，这两个包没啥区别，只是“换了个马甲”。

Validation API 最主流的实现，Hibernate Validator 的坐标也有调整，根据 https://hibernate.org/validator/documentation/migration-guide/#6-0-0-final[Migration Guide - Hibernate Validator^] 显示，从 6.0.0 开始，将 `groupId` 由 `org.hibernate` 改为 `org.hibernate.validator`。值得一提的是， Hibernate Validator 为了方便迁移，还是使用旧的 `groupId` 跟踪发布了同等实现的依赖。最新的 6.X 的依赖如下：

[source%nowrap,xml,{source_attr}]
----
<!-- D瓜哥 · https://www.diguage.com -->
<dependency>
    <groupId>org.hibernate.validator</groupId>
    <artifactId>hibernate-validator</artifactId>
    <version>6.2.4.Final</version>
</dependency>
----

由几点需要注意：

. 这个版本的 Hibernate Validator 依赖了 `jakarta.validation:jakarta.validation-api:2.0.2`；
. 由于 `groupId` 发生了变化，Maven 不能解决这类的“依赖冲突”，所以需要手动检查并排除低版本 Hibernate Validator；
. D瓜哥遇到了一次线上问题，低版本的 Hibernate Validator 和高版本的 Hibernate Validator 起了冲突。所以，还请务必排除低版本的 Hibernate Validator 实现。


== ProtoBuf

有些应用还依赖了 ProtoBuf，在 https://groups.google.com/g/protobuf/c/HtNHEyT1pKk/m/49dOrhOXBwAJ[Status of protobuf-java 2.x / 3.x compatibility] 中讨论了 Protocol 2.x 与 3.x 的兼容性问题。可以考虑升级到 3.x，我升级过程中，没有遇到过啥问题。最新的依赖如下：

[source%nowrap,xml,{source_attr}]
----
<!-- D瓜哥 · https://www.diguage.com -->
<dependency>
    <groupId>com.google.protobuf</groupId>
    <artifactId>protobuf-java</artifactId>
    <version>3.21.5</version>
</dependency>
----

== Bouncy Castle

https://www.bouncycastle.org/java.html[Bouncy Castle Java Cryptography APIs^] 是 Java Cryptography APIs 的主流发布版。在发布 1.71 版时，他们发布了针对 JDK 1.8+ 的版本，同时将 `-jdk18on` 作为这系列 API 的 `artifactId` 后缀。详细介绍请看： https://www.bouncycastle.org/latest_releases.html[Bouncy Castle LATEST JAVA RELEASES] -- Bouncy Castle 针对 JDK 1.8+ 发布的新依赖使用的后缀是 `-jdk18on`。







== 外部 Jar 包选择标准

. 尽量将外部中间件统一到同一种依赖的同一个版本上。如数据库连接池全部使用 HikariCP；JSON 处理统一使用 Jackson。
. 选择最近两年发布的版本中，下载次数最多的版本为准。如果有发布的小版本升级，则在该版本基础上，该版本的最新修订版。例如，1.2.3 是最近两年下载最多的版本，但是 1.2.4 已经发布，则优先选择使用 1.2.4。
. 如果有两个大版本，高版本符合条件的情况下，优先选择高版本。低版本大概率是先淘汰的，高版本相对来说维护时间更长，另外高版本的代码优化得更佳。例如，Ehcache 的选择。
. 如果传递依赖造成依赖 Jar 包版本冲突，则尽可能选择高版本的 Jar。
. 持续演进的项目的依赖优先级更高；相反，临近淘汰的项目优先级降低，甚至不予考虑。
. 两年以上未更新的依赖，在 API 兼容的情况下，直接升级到最新版。
. 没有显示使用而是间接引入的依赖，不再单独声明，由直接依赖来引入。

对上面的选择标准做一些简要说明：

Spring 是全世界广泛使用的开发框架，在各种场景中都经受过考验。所以，Spring 选择的 Jar 在稳定性和兼容性方面都有保证。故而，我们选择以 Spring Boot 为底本，将 Spring 相关依赖删除掉，然后在其之上增加其他依赖而生成该 BOM。

另外，在稳定性方面，经过更多人检验的版本，则稳定性更有保障。所以，选择下载人数多的。

最后，更新的版本，更容易获得技术升级带来的红利。所以，在可能的情况下，优先选择高版本。



## 特别说明



## Spring Boot

1. 使用 Spring 5.x 的项目，建议通过 [Spring Boot Dependency versions](https://docs.spring.io/spring-boot/docs/current/reference/html/dependency-versions.html) 来声明依赖。为了保证本 BOM 与 Spring Boot BOM 的兼容性，本 BOM 与 Spring Boot BOM 共同包含的依赖，使用了 Spring Boot BOM 声明的变量来定义版本。
2. 如果在 Spring Boot Dependency 中没有声明某个依赖，则从上述网页提到的 `spring-integration-*` 中查找相关依赖，以查找的依赖版本为准。例如：ZooKeeper 版本的选择。

Spring Boot Dependency

```xml
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-dependencies</artifactId>
            <version>2.7.1</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
```



## 内部 Jar 包选择标准

内部情况比较简单，选择标准也比较简单。

1. 尽可能选择最新稳定版，享受技术升级带来的红利。比如 JSF 1.7.2 以上版本，默认使用 Hessian，避免添加字段的大坑。
2. 只选取比较稳定而不是经常发布 Jar 包。例如，内部中间件依赖，JSF，JMQ 等。反例，小组对外暴露的接口依赖。



## 更新机制

1. 有重要漏洞修复时，则立即更新并发布新版本，相关应用也需要强制及时升级。
2. 每半年升级一下相关依赖，发布新版本。时间定在 618 和双十一以后。发布新版本后，相关应用跟随需求进行升级。不做强制要求。
3. 其他项目使用该 BOM 后，后续升级该 BOM 声明的 Jar 包，**只需要将该 BOM 的版本升级到最新版即可。**

## 升级注意事项

1. 很多依赖仅支持 Java 8 及其以上版本，所以要求项目也必须升级到 Java 8。最典型的例子就是 Spring 5+ 仅支持 Java 8+。
2. 为了防止声明 Spring 导致的强绑定，该 BOM 没有声明 Spring 相关的依赖。需要的话，建议使用 Spring Boot Dependency，上文提到，这里不再赘述。
4. AspectJ 的依赖 aspectjrt 和 aspectjweaver 对 JVM 的版本号也有要求。低版本的依赖在 Java 8 上启动时报错，运行时不生效。所以，请务必升级。
5. 由于 Oracle 抛弃了 JavaEE，Jakarta 社区来维护 JavaEE，并被强制改名为 Jakarta EE。由此导致很多依赖都做了修改。完整列表见： [Jakarta EE Specifications | The Eclipse Foundation](https://jakarta.ee/specifications/) 。 **Spring 5 会继续支持旧版 API，所以，可以保持不动。** Spring 6 才需要切换到 Jakarta EE。涉及到我们项目的依赖如下：
1. `javax.activation:activation:jar:1.1` 改为 `javax.activation:javax.activation-api:jar:1.2.2`。该 API 对应的实现由 `javax.xml.bind:activation:jar:1.0.2` 改为 `com.sun.activation:jakarta.activation:jar:1.2.2`。???检查 `jakarta.activation-1.2.2`

3. `javax.annotation:javax.annotation-api:jar:1.3.2` 改为 `jakarta.annotation:jakarta.annotation-api:jar:2.0.0`。
4. `javax.el:javax.el-api:jar:3.0.0` 改为 `jakarta.el:jakarta.el-api:jar:3.0.3`。
5. `jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3` 的变化。比较凌乱，稍后给出更详细的说明。 [Jakarta XML Binding](https://eclipse-ee4j.github.io/jaxb-ri/) 。

9. [Bouncy Castle LATEST JAVA RELEASES](https://www.bouncycastle.org/latest_releases.html) -- Bouncy Castle 针对 JDK 1.8+ 发布的新依赖使用的后缀是 `-jdk18on`。建议切换到新版依赖上。Spring 5.3.22+ 已切换到新版依赖。（在 `cf-bom` 中，使用了新版依赖。）

## 维护人员

最好有一两个人专门负责维护该项目的更新。建议选有代码洁癖，痴迷技术，有版本控的人来更新项目，其他人员负责 Review 更新。

