---
title: "沟通方法总结"
date: 2019-10-17T21:47:00+08:00
lastmod: 2019-10-17T21:47:00+08:00
draft: false
tags: ["沟通技巧", "个人提升", "团队建设"]
categories: ["方法论"]

weight: 1

# You can also close(false) or open(true) something for this content.
# P.S. comment can only be closed
# comment: false
# toc: false

---


== Talk和Code同等重要

Talk is cheap，show me the code.

**有效的沟通是事业成功的必要条件。**不管你的目标是成为一名卓越的管理者，还是成为某个领域的技术牛人，你都应该提高自己的沟通能力。

=== 沟通的原理和问题

沟通是指运用语言、文字或一些特定的非语言行为（面部表情、肢体动作等），把自己的想法、要求、信息等内容传递给对方。

* 约定术语
* 反馈确认
* 达成共识


== 沟通阻碍和应对方法

=== 信息不准确

在沟通之前，首先要想清楚沟通的目的是什么，然后整理自己的措辞。

沟通就是要来来回回的确认。

沟通效率的关键不在于快，而是准确！


=== 信息太多

不要绕弯子，有话直说，这是最高效的沟通方式。这既是对对方的一种信任，也是一种对自己的尊重。这样沟通，事情往往能得到更好的解决。

=== 没有交互

找到对方的兴趣点，降低表达自己真实想法的门槛，培养让大家畅所欲言的自由环境，把自己的答案变成问题，让其它人有参与感，这样才可能有好的沟通，也能够有好的结果。

=== 表达方式

沟通中有两个非常重要的因素，一是沟通的内容，二就是表达方式和态度。

=== 二手信息

到信息的源头，向当事人去求证，会让这个世界更加和谐，也会让你变得更有智慧。

=== 信道被黑

在面对负面信息的时候，最好的方式不是隐瞒，而是公开以及给出解决方案。


== 沟通方式及技巧

=== 尊重

. 我可以不同意你，但是会捍卫你说话的权利。
. 赢得对方的尊重需要先尊重对方。

你一定要和对方有观点上的交互，甚至是碰撞。沟通的目的不是为了附和对方，而是产生一种更完整更全面的认知。

=== 倾听

一定要学会倾听，掌握到更多的信息，因为掌握不了足够的信息就会信息不对称，信息不对称就会做出错误的假设。

倾听其实不仅仅只是听，还要思考，要思考更深层的原因，不要被表象所迷惑，才会有更高效率的沟通，这才有助于你做出正确的决定。

=== 情绪控制

. 不要过早或者过度打岔和反驳。
. 求同存异，冷静客观。
+
切莫在冲动之下，说出很多一些过分或过激的话，因为言语的力量是巨大的，杀伤力有时难以预估。

有时候，我会自己告诫自己，情绪是自己的，不是别人的，不应该被别人 hack 了。

=== 沟通技巧

. 引起对方的兴趣
. 直达主题，强化观点
+
确定自己的目标，学会抓重点，知道自己要什么和不要什么，这样你要的才会更鲜明。当一些事情变得简明和鲜明起来时，你才会表现出有力量的观点和话语。而这些被强化过的观点和话语，只需要一句，就会在对方脑子里形成一个小爆点，要么击中了对方的软处（扎心），要么会让对方产生深度思考。
+
. 基于数据和事实

== 沟通技术

=== 逻辑

在逻辑层面说服对方，是一种非常高级的手段。

=== 信息

信息要全面、准确。

重点提一下 X/Y 问题。

=== 维度

能够站在更高的维度来沟通是我们需要努力的目标。

如果站在客户的角度，最好用高维度。但如果站在技术细节的角度，这是低维度。

高维度容易拉拢对方，而在低维度更容易说服对方。

=== 共同

共情，共享，共利，共识以及换位思考。

寻找共同的过程就是化“敌”为“友”的过程，帮助大家在共赢的大思路和环境下，共同思考问题的解，从而实现高效沟通。

=== 三本书

无论干什么，你一定要有一个非常犀利的观点，也就是金句。

推荐你看三本书《清醒思考的艺术》、《简单逻辑学》和《重来》。


== 好老板要善于提问

=== 引导

管理者要学会问问题，问员工怎样做。

作为 Leader，你要记住，**永远不要给员工答案，要让员工给你答案，而且不要只给一个答案，一定要给多个答案。**

=== 倾听

通过倾听更多地了解员工，了解他们的生长环境和背景，可以帮你对每个员工建立更加合理的预期，从而更好地进行任务分配和人员管理。

=== 共情

共情，又被称为同理心，或者换位思考，它指的是站在对方立场设身处地思考问题的一种方式。换句话说，在人际交往过程中，你需要能够体会他人的情绪和想法、理解他人的立场和感受，并站在他人的角度思考和处理问题。

=== 高维

=== 反馈

1-2-3 反馈机制：

. 不管你遇到什么问题，如果自己在那儿憋一个小时找不到解决方案，或者说没有任何思路，就要反馈到高级工程师这边来。
. 如果跟高级工程师在一起两个小时内，找不到任何解决方案或者没有思路，那么就要反馈到一线 leader。
. 如果一线 leader、高级工程师，花了三个小时，依然找不到方案，那么这个事就可能是个大事了，要向上级反馈了。

对于任何反馈机制的建立，只需要记住两点：一是及时反馈；二是能够形成正向循环。

=== 小结

* 引导，用提问的方式，“倒逼”员工找到答案，从而提高员工的参与感和成就感。
* 倾听，心态平和，毫无偏见，全面接收和理解对方的信息，而不是只听自己想听的信息。
* 共情，换位思考，站在对方立场设身处地思考和处理问题，动之以情，晓之以理。
* 高维，提升自己的格局观，能从全局利益、长远利益思考问题，解决问题。
* 反馈，建立反馈机制，及时发现问题、解决问题，形成正向循环。

== 好好说话的艺术

=== 跟员工沟通

==== 一对一会议

一对一会议时，管理者需要做的是倾听，而非“喋喋不休”地教育。

. 工作状态
. 个人发展
. 公司组织
. Leader 自己

诀窍是让员工畅所欲言，不要有任何的忌讳，能够讲出最真实的想法，哪怕想法是很偏激很不中听的，只要是真实的都应该获得尊重。


==== 绩效沟通

沟通一定要放在平时，不要搞成像秋后算账一样！因为你是管理者，不是地主监工。

要注意的是，反馈的过程中，不是我在指责员工，而是我在帮助员工。一定要有帮扶的态度，这样员工会更容易接受。

==== 特立独行的员工

. 第一个方法是给他找到匹配的人，要么是比他牛的人，要么是跟他旗鼓相当可以在一起共事儿的人，跟他一起工作。
. 第二个方法是给他一些独立的工作，把他隔离出去。

当你在一个人身上花的精力和时间成本，大于你到外面找一个更好的人或者能力相当的人来替代他的时候，你就要坚决地把他替换掉。


==== 挽留离职员工

要知道他离职的原因。

生意不行，友情在。

既然不能在此时挽留下来，那就放眼未来，人生还很长，能在一起工作的机会还有很多。

==== 劝退员工

任何人都应该有可以纠正错误的机会，公司应该给员工这样的机会，员工也应该给公司同样的机会。


=== 跟客户沟通

==== 吸引客户的兴趣

==== 帮客户发现问题

* 结合客户的痛点，了解客户做过的尝试。
* 深入细节，了解细节才会有更准确的信息。
* 小心 X/Y 问题，找到 X 问题。
+
一定要分析客户问题背后的本质原因，从根本上帮助客户解决问题。

==== 管理客户的期望

永远不要跟客户说不，要有条件地说是，告诉客户不同的期望要有不同的付出和不同的成本。不要帮客户做决定，而是给客户提供尽可能多的选项，让客户来做决定。

讨价还价是这个世界能运转的原因之一，要学会使用。


几个原则。

* 一定要给客户选择权，永远不要说不，要有条件地说是。
* 降低期望的同时给予其他的补偿。
* 提高期望的同时附加更多的条件。
* 对于比较大的期望要分步骤达到客户的期望。
* 不要帮客户做决定，而是给客户提供尽可能多的选项，然后引导客户做决定。

=== 跟老板沟通

==== 了解你的老板

. 首先，你需要了解老板的做事风格。
. 其次，你还要了解老板的目标和 KPI 是什么。
. 最后，要知道老板的老板是谁，他的风格是什么，他的目标和 KPI 是什么，因为你老板的目标和 KPI 是你老板的老板给的。

所以，倾听老板会有一些出乎你的意料的发现，你要能了解老板背后的苦衷，那些才是最重要的。

==== 赢得老板的信任

==== 管理老板的期望

==== 非暴力“怼”老板

